### ISSUE TITLE
Documentation of `FOR` is insufficient

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#1003]
The documentation of `FOR` isn't explicit about the meaning of its _stop_ argument. The documentation currently says that the value "increments from _start_ to _stop_", but in actuality `FOR` breaks right _before_ the value would reach _stop_. This should be documented explicitly — right now the documentation improperly assumes familiarity with Python, as this is only made clear by comparing the semantics with Python's `range` generator.

**Comment by ISSOtm** [comment]
"increments from *start* to *stop* excluded"?

**Comment by Rangi42** [comment]
Right below the table is says that "The `FOR` value will be updated by *step* until it reaches or exceeds *stop*", and gives an example demonstrating that the value *does* reach *stop* but that the body of the `FOR` loop is not executed for this value (same as a C `for (int value = start; value < stop; value += step)` loop).
