### ISSUE TITLE
-r argument results in zero byte input file and warning/error

### ISSUE THREAD

**Issue by tbsp** [gbdev/rgbds#1016]
After running the following command in Windows 10 using the v0.6.0-rc1 release build:

`rgbgfx -r 128 -o test.png test.rom` or `rgbgfx -r 128 -o test.png test.2bpp`

The test.rom/test.2bpp files become 0 bytes, and the following is shown:

`warning: While writing reversed image ("test.gb"): Image height is zero in IHDR
FATAL: Error writing reversed image ("test.gb"): Invalid IHDR data`

Note: The same error seems to occur with any -r value that isn't a multiple of 256, for example 43. Multiples of 256 lead to issue #1015.

Edit: It looks like these arguments are not the right ones when using reverse. I'm looking into how to call it correctly.

**Comment by tbsp** [comment]
I'm sure this is 100% user error, but I can't figure out the combination of inputs that would allow me to convert an entire ROM (or even just a simple 2bpp file) to a PNG. I'm aware that I need to pass "tile data", but passing that as the input file doesn't work, and I can't see how else to specify it.

**Comment by tbsp** [comment]
Figured it out: `rgbgfx -r 128 -o test.rom test.png`

The most important "output" `-o` being the input is certainly a little disorienting, but I get it.

**Comment by ISSOtm** [comment]
If `test.png` didn't exist beforehand, this should have failed. Right?

The "Image height is zero" error is another problem.

**Comment by tbsp** [comment]
If the input (`-o` when using `-r`) file doesn't exist I would expect to see an error to that effect. If _neither_ test.rom nor test.png exist, and my original command (`-o test.png test.rom`) is run, the original error is shown, possibly because the input is zero bytes, and a 0 byte `test.rom` is created.

**Comment by ISSOtm** [comment]
If neither exist, the input file (`-o`'s `test.png`) doesn't exist, and that should yield an error.

**Comment by tbsp** [comment]
That only yields the image height is zero warning/error.

**Comment by ISSOtm** [comment]
Turns out that was fixed by 6a51e39a, which is *not* in v0.6.0-rc1! Mystery solved.
