### ISSUE TITLE
[Feature request] Warning when passing a character through for characters without a charmap entry

### ISSUE THREAD

**Issue by tbsp** [gbdev/rgbds#1022]
In some cases it might be useful to know when a character you're using doesn't have a mapping in the current charmap (which I believe will always be the case by default unless you define one). This could help catch unexpected bugs if you don't realize your charmap is incomplete.

A possible warning flag might be: `-Wcharmap-passthrough`

**Comment by Rangi42** [comment]
If you have not declared any `charmap`s at all, and are using the default charmap, I don't think this error should occur, since you're clearly relying on the default ASCII/UTF-8 mapping. So:

```
SECTION "test", ROM0
  db "Hello world!" ; no warning
  pushc
    newcharmap custom
    db "Goodbye" ; this warns, since the charmap is non-default, even though it has no mappings
  popc
  charmap "A", $41 ; same value as default, but explicit
  db "Hello again!" ; this warns, since the default charmap now has mappings
```
