### ISSUE TITLE
`FOR` loops have some unexpected edge cases

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1033]
As mentioned in #1003.

```
FOR x, $8000_0000, $6000_0000, $4000_0000
  PRINTLN x
ENDR
PRINTLN "done ", x
```

This prints `$80000000` and then `done $C0000000`.

```
FOR x, $8000_0000, $7000_0000, $4400_0000
  PRINTLN x
ENDR
PRINTLN "done ", x
```

This prints `$80000000` and then `done $C4000000`.

**Comment by aaaaaa123456789** [comment]
The most obvious edge case would be a step size of 0. (Is that even valid?)
Bar that, any case involving overflow should lead to this kind of strange behavior. For instance, from the documentation, I'd assume that `for x, $80000000, $70000000, $44000000` loops 16 times.

**Comment by Rangi42** [comment]
No, `FOR cannot have a step value of 0`. And yes, arguably the documentation should clarify how `FOR` behaves with overflow, but it's not actually different from how anything else behaves with overflow, so maybe there should just be a section noting that numbers are internally 32-bit signed two's complement.

**Comment by aaaaaa123456789** [comment]
Is that the current behavior? I thought those loops would currently run four times.

**Comment by Rangi42** [comment]
The logic of `FOR` loops, from fstack.c:

```c
	/// Values specified by the FOR loop in asm:
	/// int32_t start, int32_t stop, int32_t step

	uint32_t count = 0;

	if (step > 0 && start < stop)
		count = (stop - start - 1) / step + 1;
	else if (step < 0 && stop < start)
		count = (start - stop - 1) / -step + 1;
	else if (step == 0)
		error("FOR cannot have a step value of 0\n");

	if ((step > 0 && start > stop) || (step < 0 && start < stop))
		warning(WARNING_BACKWARDS_FOR, "FOR goes backwards from %d to %d by %d\n",
			start, stop, step);

	if (count == 0)
		return;

	/// The FOR loop will run for `count` iterations, starting at `start`
	/// and adding `step` to it at the end of each iteration.
```
