### ISSUE TITLE
[Feature Request] Ability to load "inline format" color specs from a file in RGBGFX

### ISSUE THREAD

**Issue by SuperDisk** [gbdev/rgbds#1048]
According to the current docs, the valid formats for `-c`'s external file loading are `act`, `aco` and `psp`. Additionally, `-c` can accept an "inline" format which is just plain text hex codes separated by commas. It would be nice to load that text format from file as well, since it seems like the Adobe formats are binary and not easily created (not sure about `psp`).

You can probably work around this currently by using `cat` or something but it would be a nice addition.

**Comment by ISSOtm** [comment]
Do "at-files" not fulfill that use case? You'd store the `-c #000,#555,#aaa,#fff` in, say, `img.pal.txt`, and then you can do `rgbgfx -o img.2bpp img.png @img.pal.txt`.

**Comment by SuperDisk** [comment]
Oh interesting, that does look like it would address my use case.
