### ISSUE TITLE
Explicitly initialize static variables to zero values

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1049]
C initializes static variables by default to zero values (`0`, `0.0f`, `NULL`, `{0}`, etc). We'd prefer to be explicit about this.

**Comment by aaaaaa123456789** [comment]
There's also a slight difference between default initialization and `{0}` in C23, and you _don't_ want that can of worms :)

**Comment by ISSOtm** [comment]
Specifically, be explicit about it *when it matters*, i.e. only for variables that *need* to be default-initialised. Some variables are always overwritten before they are first read, and I'd prefer no initialiser for those.

**Comment by Rangi42** [comment]
`git grep -E '^static [^=]+;' src` turns up 36 such declarations.

**Comment by ISSOtm** [comment]
Turns out this is iffy with some more complex types, so I'd rather do this together with a C++/Rust port. It's mostly fine as-is, anyway.
