### ISSUE TITLE
Cache build dependencies in CI

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#1082]
Sometimes, testing fails because it can't access an online resource. Caching them (using [`actions/cache`](https://github.com/actions/cache)) would avoid that problem, as well as speed up testing.

Candidates for caching:
- [ ] The external repos pulled by `test/run-tests.sh`
- [ ] The libpng sources pulled by `.github/actions/mingw-w64-libpng-dev.sh`

...any anything else that gets `wget`/`curl`/`git clone`d and that I missed.

**Comment by SaumyaBhushan** [comment]
@ISSOtm Can you provide little help? How can I start working on this ?

**Comment by Rangi42** [comment]
Hello! https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows might help.

**Comment by ISSOtm** [comment]
Hi!

Since the caching action expects a key, I think the best course of action is to hoist the "versions" (Git commits for the former, URLs for the latter?) into a separate file, and using that as the "key". Alternatively, [setting an output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) from a Bash script and reusing that later.

Let us know if you'd like any additional help :)
