### ISSUE TITLE
Allow installing multiple versions of rgbds

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1090]
`make install` could name its executables as `rgbasm0.6.0`, `rgblink0.6.0`, etc, and symlink `rgbasm`, `rgblink`, etc to the latest version. This would let older projects continue to use old rgbds without having to keep a local copy somewhere.

**Comment by ISSOtm** [comment]
Sounds more like a job for the distro packager.

This would not let old projects work without specifying e.g. `make RGBASM=... RGBLINK=...` explicitly, at which point you don't even need `make install` anyway.

**Comment by aaaaaa123456789** [comment]
I think it's a bit more conventional to do `rgbasm-0.6.0`, etc.

**Comment by mid-kid** [comment]
I agree this should be left up to the distro pacakger, but it'd be nice to have an upstream convention. Many autotools projects allow passing a `--program-suffix=-$VERSION` flag, to help with this.
Personally I'm torn between both installing the bins in a separate directory and using different names, might do both.
