### ISSUE TITLE
v0.6.0 compilation errors

### ISSUE THREAD

**Issue by maij** [gbdev/rgbds#1109]
Sorry in advance if this is the wrong place to be putting this.
I am having trouble building from source in Ubuntu 22.04. I have followed the instructions, I have gcc 11.3, bison 3.8.2, pkg-config 0.29.2 and clang 14.0.0. I have attached the output from when I run make.

[dump.txt](https://github.com/gbdev/rgbds/files/10036598/dump.txt)

**Comment by ISSOtm** [comment]
You appear to be using libpng 1.2.x, which is very incompatible, [and also deprecated due to various security issues](http://www.libpng.org/pub/png/libpng.html). I would advise installing [the `libpng-dev` package](https://packages.ubuntu.com/jammy/libpng-dev).

**Comment by maij** [comment]
Thanks, that did the trick once I had located all of the old libpng installs.
