### ISSUE TITLE
[Feature request] `ds` in linker scripts

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#1110]
This is simply to simplify automated linker script generation from map files: slack space can be simply represented as such.

Semantics: exactly the same as `org` with the appropriate value. (For instance, if the current address is $4700, `org $4800` and `ds $100` would have the same semantics.) If the former allows the linker to place floating sections in the gap, so should the latter.

**Comment by ISSOtm** [comment]
What simplifications would this enable?

**Comment by aaaaaa123456789** [comment]
Literally just converting a `SLACK: $xxxx` bytes in a map file into a linker script gap, without forcing fixed addresses that would hinder further modifications to the program.
The ultimate goal here is to allow an easy way of "fixing" a ROM's section placement by converting the map file into a linker script.

**Comment by ISSOtm** [comment]
That seems inconsistent, since what would the point of "pinning" all sections like this be if further modifications are anticipated?

**Comment by aaaaaa123456789** [comment]
Anything related to reproducibility. Verifying which one out of a series of modifications changes a ROM, for instance.

**Comment by ISSOtm** [comment]
I'm not following: if any of those modifications cause a section's size to change, the map files would differ and show the difference; and otherwise, fixing the addresses is sufficient.
Am I missing something?

**Comment by aaaaaa123456789** [comment]
One of those "modifications" may be a modification in the toolchain (see: a recent discussion in #rgbds about what would happen if the section placement algorithm changed). A simple way to protect against that is to convert the map file into a linker script, update the toolchain, and check for changes — that way, changes in section placement won't happen, but other sorts of breaking changes (like the recent trigonometry change) would be detected.

**Comment by ISSOtm** [comment]
Okay, yes, but what's wrong with only specifying addresses for the sections even then?

**Comment by aaaaaa123456789** [comment]
I forgot about this thread, my bad!
Anyway, it's just convenience/readability: mapping clearly empty space to empty space, in a way that the quantity is shown directly. Semantically it's exactly the same.

**Comment by ISSOtm** [comment]
Then I'm "meh". We will keep this open for others to maybe weigh in, or until someone submits a PR.
