### ISSUE TITLE
Build fails on Debian 9.13

### ISSUE THREAD

**Issue by squishypixel** [gbdev/rgbds#1115]
Attempting to `make` on Debian 9.13 (through Windows WSL) and getting the following error:

`src/gfx/main.cpp:25:23: fatal error: string_view: No such file or directory`
` #include <string_view>`
`                       ^`
`compilation terminated.`
`Makefile:169: recipe for target 'src/gfx/main.o' failed`
`make: *** [src/gfx/main.o] Error 1`

**Comment by ISSOtm** [comment]
Looks like your libstdc++ is too old, at least libstdc++ 7.1 is required. Debian "stretch" ([Debian 9](https://www.debian.org/releases/)) ships [6.3.0](https://packages.debian.org/stretch/libstdc++-6-dev), so you must upgrade your distro.

**Comment by ISSOtm** [comment]
(The minimum libstdc++ version for `string_view` [is listed here](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017).)

**Comment by CasualPokePlayer** [comment]
Note to that [Debian 9 went completely went EOL on June 30, 2022](https://wiki.debian.org/LTS), you should update ASAP
