### ISSUE TITLE
Bug: rgbgfx: Indexed pngs not treated correctly

### ISSUE THREAD

**Issue by dannye** [gbdev/rgbds#1117]
Example png: https://github.com/pret/poketcg/blob/master/src/gfx/hand_cards.png

This png is indexed with a palette of 4 colors:
![image](https://user-images.githubusercontent.com/5231310/209689066-f1e545d8-067f-4345-98ae-d6d37f7fede2.png)

It is supposed to end up in the rom like this:
![image](https://user-images.githubusercontent.com/5231310/209689104-6c2f671a-bcd2-4279-8768-eaa6c44b4c91.png)

But with rgbds v0.6.1, for some reason the black (color 3) is being turned into color 2:
![image](https://user-images.githubusercontent.com/5231310/209689205-727e7c6e-c90c-4db7-ac43-4862ca2037a9.png)

**Comment by Rangi42** [comment]
That's being converted without any specific rgbgfx flags, just `rgbgfx -o hand_cards.2bpp hand_cards.png`. Previously in 0.5.x, rgbgfx would automatically use the indexed palette if one was present -- which meant that two identical-looking PNGs might convert differently based on an invisible detail (unless you view them in some heavyweight program like GIMP). In 0.6.0 rgbgfx will generate its own palette unless you explicitly specify one with `-c`, and `-c embedded` is how you specify to use the indexed palette of the PNG itself.

That said, grayscale PNGs like this one should probably just be encoded as 2-bit grayscale PNGs, like the ones in pokered and pokecrystal. Those convert as expected to 2bpp without needing `-c embedded`, and with no possibility of the colors being out of order.
