### ISSUE TITLE
[Feature request] Raw strings, without backslash escapes or interpolation

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1121]
String "literals" are not actually literal: the lexer's `readString` routine still expands macro args like `\1` and interpolations like `{x}`, as well as understanding certain backslash escapes like `\n`. (This is done as special handling within `readString` itself; the expansions in `peek` are disabled while reading a string literal, so the expanded contents can be contained as-is inside the string.)

Sometimes it would be more useful not to do this. If you don't need to expand and values within your string, it can be annoying to write `"()[]{}"` and then have to turn it into `"()[]\{}"`. Likewise if you either don't need literal whitespace characters or are using a `"""multi-line string"""` for them, you have to turn `\n` into `\\n`.

This issue proposes "raw strings", like the ones in many programming languages. Syntax could be anything; a few ideas:

- `#"hash strings"` (or `#"""multi-line"""`) would be like Rust.
- `@"at-sign strings"` (or `@"""multi-line"""`) would be like C#.
- `'single-quoted'` strings (or `'''multi-line'''`) would be like PHP and Bash (although we may want to reserve that syntax for possible character literals or something).
- Prefix `r"raw"` like Python could also work, but currently that lexes as `r "raw"`, e.g. passing `"raw"` to macro `r`. `@` and `#` are okay because `@` is always defined as the PC, and `#` is not a valid identifier or operator.
- Any unambiguous punctuation prefix, e.g. `$"dollar strings"`.

(A more niche use case: regular expression literals. `#"\w+[\/]\w+\.\w{3}"` would be like `"\\w+[\\/]\\w+\\.\\w\{3}"`.)

**Comment by ISSOtm** [comment]
I'd prefer `@` as the prefix, to keep `#` unused for now.

**Comment by Rangi42** [comment]
@ISSOtm Summarizing the discussion from `#rgbds`: we were also wanting to add syntax for "raw identifiers", as requested by arkamnite, so rgbasm-reserved keywords may still be used as symbols if necessary. Proposed syntaxes include ``​`​`a``, `#a`, `'a'`, and probably others. I'd like to copy C# and have some consistency in the syntax for raw identifiers and raw strings (C# has "verbatim identifiers" like `@for`, and "verbatim strings" like `@"C:\Users"`.) So I don't think we should use `@` as a raw string prefix, because `@name` has been suggested for auto-purged locally-scoped symbols. We could have ``​`​`"raw strings"`` and commit to using the same prefix for raw identifiers; or (my preference) use `#`. (What would we avoid using it for?)
