### ISSUE TITLE
[Documentation] Description of padding (-p) option for RGBASM is confusing

### ISSUE THREAD

**Issue by Calindro** [gbdev/rgbds#1125]
Currently, the description is as follows:
```
[-p](https://rgbds.gbdev.io/docs/v0.6.0/rgbasm.1#p) pad_value, --pad-value pad_value
    When padding an image, pad with this value. The default is 0x00.
```
I can't make any sense of `image` in this context and it isn't at all obvious that it affects the value used for `ds` directives that do not specify which value to use.

I think this could use some clarification. :)

**Comment by aaaaaa123456789** [comment]
"When padding a ROM image..." would do it, I'd say?

**Comment by ISSOtm** [comment]
No, because what it actually is, is what's used for one-argument `ds`, and nothing else.

"When padding ROM images" would apply more to RGBLINK and RGBFIX's `-p`.

**Comment by aaaaaa123456789** [comment]
Then it should be "when padding a _ROM section_...", since that's what it's doing. And you can reference `ds` explicitly.

**Comment by Rangi42** [comment]
"when padding within a ROM section", since "padding a ROM section" sounds to me like padding that goes at the end of the section to fill out the bank, which this is not.

**Comment by ISSOtm** [comment]
Considering that the single place it's used is one-argument `ds`, whose name does not even evoke the word "padding", I would outright say "`ds` with only a length argument will fill ROM with this byte".
