### ISSUE TITLE
the download checksum has changed at least twice in a week

### ISSUE THREAD

**Issue by jrmarino** [gbdev/rgbds#1128]
has version 0.6.1 been retagged multiple times?
The checksum of this tagged version has changed at least twice this week.
If that's indeed what happened, this is really bad form -- it gives packagers that rely on the checksum to validate downloads fits.

Better to mark it v0.6.1a, v0.6.1b, etc than to rewrite git history.
please consider not doing this anymore.

**Comment by DarkRTA** [comment]
Nobody has retagged this as far as I am aware, otherwise I would have issues with building the Arch Linux `PKGBUILD`.

If you are downloading the source zip that is automatically generated by GitHub rather than the released tarball, GitHub pushed out and then reverted an update that caused the hashes to change.

**Comment by jrmarino** [comment]
oh wow.  if they left that in place it would have wrecked repositories everywhere.  Those systems do run checksums against generated tarballs.

Sorry about that and thanks for the information.

**Comment by ISSOtm** [comment]
FWIW, for this exact purpose, we distribute a tarball ourselves. (Bentley said a long while back that GitHub's own were not guaranteed to be stable. Maybe history just vindicated him :P)

If you have any problems with our tarballs, please do not hesitate to report them!

We don't re-tag releases, or at least not so long after they've been published—and even then (we've had breakage during the release process last time ><), we commit not to until after the GitHub release has been published.

**Comment by ISSOtm** [comment]
Separately, thank you for packaging RGBDS! ^^

**Comment by aaaaaa123456789** [comment]
@jrmarino You might want to remove that "known to reroll!" line you added in the package now that you know what happened — same for any other packages in a similar situation.

**Comment by jrmarino** [comment]
Okay, done.  It showed up twice because I accidently committed it to a closed branch.
