### ISSUE TITLE
RGBDS as a Threat to AVG?

### ISSUE THREAD

**Issue by P0W3** [gbdev/rgbds#1140]
AVG thinks that RGBDS is a threat.

![image](https://github.com/gbdev/rgbds/assets/18279115/311f98b7-2636-4234-96c7-fc929ac7c891)

![image](https://github.com/gbdev/rgbds/assets/18279115/4311dca9-b4a9-4d9d-9e53-d589774e26c5)

**Comment by aaaaaa123456789** [comment]
As you can see, it's blacklisted. Why? I assume because it's a githubusercontent URL.

Nothing can be done here — get a better antivirus, or use common sense in its stead.

**Comment by ISSOtm** [comment]
Yeah, unfortunately antiviruses have a tendency to screw over less popular software like us. The only two options are for you to disable the AV's URL blocking, or to disable it entirely.

There is nothing we can do, so, closing this.
