### ISSUE TITLE
[Feature Request] RGBLINK should notify a user when a label exists but is not exported.

### ISSUE THREAD

**Issue by eievui5** [gbdev/rgbds#1142]
Currently RGBLINK will fail if `Foo` is defined in another translation unit but is not exported. This error could be made more useful if RGBLINK reported the locations of the non-exported symbols so that the user could export them.

**Comment by Rangi42** [comment]
The error message is just "Unknown symbol"; `rgblink` doesn't know that the symbol is defined in another translation unit, and it may be defined in none or in more than one.

**Comment by ISSOtm** [comment]
The request is for

```asm
; a.asm
Label:
```

```asm
; b.asm
ld hl, Label
```

...to have the error message from `b.o` mention that a symbol with the same name is defined in `a.o` but is unreachable. It would be a good idea to mention the source file as well, `a.asm`.

In case there are multiple, well, the multiple options would be mentioned. Perhas we'd want to cap the number of options, and sum then up to "and N more"?

If there are none, then it's truly an unknown symbol, and the current error is perfectly sufficient.

**Comment by Rangi42** [comment]
I think users would find it pretty frustrating if they saw an error like:
```
error: b.asm(2): Unknown symbol "Label"
    A label "Label" is defined but not exported at a.asm(2)
```
because the obvious next question is "if rgblink knows where the one possible `Label` is, why doesn't it use it!?"

This would be a much happier change when there are multiple possibilities:

```
error: b.asm(2): Unknown symbol "Label"
    A label "Label" is defined but not exported at a.asm(2)
    A label "Label" is defined but not exported at c.asm(3)
    A constant "Label" is defined but not exported at q.asm(5)
```

**Comment by ISSOtm** [comment]
Perhaps this could reduce frustration:

```
error: b.asm(2): Unknown symbol "Label"
help: The symbol is not defined in the same object file, and symbols from other object files can only be used if exported.
    A label "Label" is defined at a.asm(2), but not exported
```
