### ISSUE TITLE
Warn when `--sgb-compatible` is passed, but the old licensee code is not 0x33

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#1150]
Since RGBFIX sees all of the header anyway, we should be able to just check for this?

**Comment by Rangi42** [comment]
This was done in https://github.com/gbdev/rgbds/pull/664:

```c
	if (sgb && oldLicensee != UNSPECIFIED && oldLicensee != 0x33)
		fprintf(stderr,
			"warning: SGB compatibility enabled, but old licensee is %#x, not 0x33\n",
			oldLicensee);
```

**Comment by ISSOtm** [comment]
Yes, but we only do this when it's being set explicitly via RGBFIX. To clarify, the intent was to also check the pre-existing value in the header if it's not being overridden.
