### ISSUE TITLE
Sort local symbols before global ones in sym files

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1151]
Sym files "may or may not be sorted by location" [according to the spec](https://rgbds.gbdev.io/sym/), and the [rgblink docs](https://rgbds.gbdev.io/docs/v0.6.1/rgblink.1/) do not mention sorting. The current implementation claims "Symbols are ordered by address, or else by original index for a stable sort". It may be preferable to sort local labels differently from global ones, so debuggers will be more likely to show the correct symbol when they share an address.

Action:

```
$ cat foo.asm
SECTION "test2", ROM0[3]
Quux:
 ret
 .end
SECTION "test", ROM0[0]
Foo:
 ret
 .end
Bar:
 ret
 .end
Baz:
 ret
 .end
 
$ rgbasm -o foo.o foo.asm
$ rgblink -n foo.sym foo.o
$ cat foo.sym
```

Current output:

```
; File generated by rgblink
00:0000 Foo
00:0001 Foo.end
00:0001 Bar
00:0002 Baz
00:0002 Bar.end
00:0003 Baz.end
00:0003 Quux
00:0004 Quux.end
```

Desired output:

```
; File generated by rgblink
00:0000 Foo
00:0001 Foo.end
00:0001 Bar
00:0002 Bar.end
00:0002 Baz
00:0003 Baz.end
00:0003 Quux
00:0004 Quux.end
```

**Comment by ISSOtm** [comment]
Note that we do not always want this.

```asm
Bar:
.sub
```

...should emit

```
00:0000 Bar
00:0000 Bar.sub
```

...and not

```
00:0000 Bar.sub
00:0000 Bar
```
