### ISSUE TITLE
Error in rgbasm.5 symbol interpolation example 

### ISSUE THREAD

**Issue by quinnyo** [gbdev/rgbds#1152]
Trying to assemble the first example in the 'Symbol interpolation' section causes an error.

The error is on the last line (`PURGE topic, meaning, {meaning}`) -- `Interpolated symbol "meaning" does not exist`

I'm assuming the symbols/arguments are purged left to right and interpolated after the preceding one has been purged. So, in effect, it's doing `PURGE meaning` _then_ `PURGE {meaning}`.

Swapping the order of the arguments `PURGE topic, {meaning}, meaning` eliminates the error and purges the all of the defined symbols (i.e. `topic, answer, meaning`).

**Comment by Rangi42** [comment]
Nice catch! The left-to-right order should be explicitly documented, especially since that example illustrates its importance.

**Comment by ISSOtm** [comment]
I think we should instead make the above supported, i.e. by building a list of symbols to be purged *before* deleting any of them. This is an implementation detail showing through, and it honestly doesn't make much sense imo.
