### ISSUE TITLE
RGBGFX documentation inconsistency

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#1153]
`-L`:
> `-L` is ignored in reverse mode, no padding is inserted.

`-r`:
> _width_ is the image's width, in tiles (including any margins specified by `-L`).

**Comment by Rangi42** [comment]
Providing both `-r` and `-L` warns "`"Sliced-off" pixels are ignored in reverse mode`", so the `-r` docs need updating.
