### ISSUE TITLE
zlib has updated to 1.3

### ISSUE THREAD

**Issue by pinobatch** [gbdev/rgbds#1163]
On Friday, August 18, 2023, the maintainer of [zlib](https://zlib.net/) released zlib 1.3 and removed zlib 1.2.13 from availability. This caused both of my outstanding pull requests (#1159 and #1161) to start failing because the Windows build could no longer download zlib 1.2.13. All future pull requests will also fail on Windows. Please update the Windows build process to download and build the more recent version of zlib.

**Comment by ISSOtm** [comment]
Fixed in #1159.
