### ISSUE TITLE
RGBGFX producing wonky image

### ISSUE THREAD

**Issue by maxwedwards** [gbdev/rgbds#1165]
I'm not sure if this is something I'm doing wrong but I'm getting weird output from RGBGFX. I've included the source image and the command being run. The reverse image generation looks exactly the same as it appears when I load this image on an emulator. I've tried an indexed image and RBG image and both look the same. Interestingly if I cut a lot of the detail out of the image it does render correctly. Any help appreciated.

Input image
![input](https://github.com/gbdev/rgbds/assets/1204616/f01bff84-f6a3-42e7-979c-eeba6bd4c757)

command: 
```
rgbgfx -c "#FFFFFF,#cbcbcb,#414141,#000000;" \
                --tilemap title-screen.tilemap \
                -vvvvvv \
                --mirror-tiles \
                -o title-screen.2bpp \
                input.png
```
Output
![Output](https://github.com/gbdev/rgbds/assets/1204616/56533551-8965-432f-b02b-6657ab5c4fac)

**Comment by ISSOtm** [comment]
This seems to come from you passing `--mirror-tiles`, but this seems to be a DMG, which has no mirroring on BG?

**Comment by maxwedwards** [comment]
Ah good spot. I switched to `--mirror-tiles` as part of my efforts to try and correct it. This is how it looks with only `--unique-tiles`. The bottom of the image is still messed up. Any more ideas?

<img width="639" alt="Screenshot 2023-08-26 at 18 59 04" src="https://github.com/gbdev/rgbds/assets/1204616/fe7e9342-52f3-497a-8ba9-d15a9e763b82">

**Comment by ISSOtm** [comment]
You may want to check your emulator's tile viewer to confirm whether the tiles are being loaded, and if so, check the tilemap viewer to check where they are expected to be loaded from.

**Comment by maxwedwards** [comment]
I just created a blank project that only displays this image and there's nothing wrong with it. I feel really embarrassed!

Going to have fun figuring out where I'm overwriting the tilemap with blank tiles in my main project now!

Thanks for time @ISSOtm
