### ISSUE TITLE
Clarify what "deduplicating" means for rgbgfx

### ISSUE THREAD

**Issue by LiamGiiV** [gbdev/rgbds#1169]
In the context of creating a tilemap it was unclear to me what "deduplicating" was, seen here with option -t:

https://rgbds.gbdev.io/docs/v0.6.1/rgbgfx.1/#ARGUMENTS

Rather than talking about deduplicating duplicate tiles, perhaps the manual could just talk about only saving unique tiles? It matches the flag better, and while the idea of deduplicating things is not totally insensible it's a little strange. 

"Save only unique tiles to the tile data file. Useful with a tile map (see -t) to keep track of the duplicated tiles.

Note that if this option is enabled, no guarantee is made on the order in which tiles are output; while it [should](https://rgbds.gbdev.io/docs/v0.6.1/rgbgfx.1/#should) be consistent across identical runs of a given rgbgfx release, the same is not true for different releases."

Additionally I would suggest adding a use case for this under Examples: https://rgbds.gbdev.io/docs/v0.6.1/rgbgfx.1/#EXAMPLES. I wouldn't presume to speak for how other folks are using this tool, but I should think that demonstrating the generation of tiles and a tile map will be helpful to some.

"The following will output a tile data file with only unique tiles and a tile map file for the given PNG:
`` $ rgbgfx \256-indexed-4colour.png -o TileData.2bpp -t TileMap.tilemap -u``
"

**Comment by LiamGiiV** [comment]
Looks like a big improvement to me!

**Comment by LiamGiiV** [comment]
I guess it's worth taking a peak at -m as well which talks about deduplication.

**Comment by ISSOtm** [comment]
Right. Would you like to take a shot?

**Comment by Rangi42** [comment]
"Deduplicate" is a standard English word, "eliminate duplicate or redundant information", and its positive counterpart "uniquify" is much less common. I agree that its meaning could be explained and exemplified better.
