### ISSUE TITLE
Publish docker image to the Packages registry when a new version is tagged

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbds#1170]
Now that we have (https://github.com/gbdev/rgbds/commit/7a39e9e569783962d54265809d8ec654b91c318b) a working Dockerimage to build and run rgbds, a GitHub action should upload and tag a new image every time a version is tagged.

See https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

https://github.com/gbdev/rgbds/pkgs/container/rgbds should get updated.

See https://github.com/gbdev/homebrewhub/blob/main/.github/workflows/build-container-image.yml for an example.

**Comment by Rangi42** [comment]
@avivace Can you possibly handle this one? You seem like the most informed about Docker here.

**Comment by avivace** [comment]
Yes, I can work on this @Rangi42 !

**Comment by Rangi42** [comment]
@avivace Just a reminder about this issue; we expect to release 0.9.0 this or next month.

**Comment by avivace** [comment]
See also https://github.com/gbdev/rgbds/issues/1509

**Comment by avivace** [comment]
Done in https://github.com/gbdev/rgbds/commit/a870f7de10fc393f1c56e14b18e43f389d2a2458
