### ISSUE TITLE
[Feature request] Check if a charmap character is defined

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1175]
We have `DEF(somename)` to see if `somename` is defined as a symbol; and `DEF("somestring")` to see if `"somestring"` is defined as a section. I've come across at least one use case where it would be convenient to see if some string has a charmap definition.

To avoid a new keyword, I think `DEF(CHARMAP "<some>")` would be appropriate. It would be 1 if `charmap "<some>", $xx` is in the current charmap, else 0.

(A sort of workaround is to check whether `CHARLEN("<some>")` is exactly 1; but that can give an "Unmapped character" warning.)

**Comment by ISSOtm** [comment]
Using identifiers or keywords inside of DEF is a big footgun, because the lexer has to preemptively disable EQUS expansion... so this usual syntax trick is a liability here.

```asm
def chaotic_evil EQUS "charmap"
println DEF(chaotic_evil "c")
```

The functionality is good, this specific syntax I'm not sold on.

**Comment by Rangi42** [comment]
Oh, good point. I wouldn't mind a new keyword then, like `DEFCHAR` or `CHARDEF`.

Or, what about `CHARMAP("some")` assuming that's unambiguous?
