### ISSUE TITLE
RGBGFX can't use input slice without deduplication

### ISSUE THREAD

**Issue by quinnyo** [gbdev/rgbds#1182]
Invoking RGBGFX with an input slice and _without_ deduplication fails `assert(remainingTiles == 0)` [here](https://github.com/gbdev/rgbds/blob/7a39e9e569783962d54265809d8ec654b91c318b/src/gfx/process.cpp#L784).

The issue is that the initial value of `remainingTiles` doesn't account for the reduced number of tiles due to the input slice being set. The tiles visitor does use the correct count, so the loop would exit "early", with `remainingTiles > 0`.

A simple fix is to just start with the number of tiles in the slice if one is set, otherwise default to use the whole image size as it currently does. This works, but otherwise seems like a low quality fix:

- `remainingTiles` seems to only be for dealing with the trim option? Doing more with it seems to be moving in the wrong direction.
- `remainingTiles` & `visitAsTiles` are both doing the 'how many tiles' calculation/logic which is not good and this duplication is seemingly to blame for the issue.
- The tile visitor/iterator should have a known length and could be trimmed (ended early) based on that -- which appears to be more or less what the 'optimised' (deduplicated) path does.
- If `visitAsTiles` accessing the options is OK (it currently does), it could just check trim as well.

**Comment by ISSOtm** [comment]
Doesn't a lack of slice default it to the image's size? I feel like we shouldn't need to have two branches here, since we should be able to have a unified "area we're going to process" at some point..?
