### ISSUE TITLE
Remove previously deprecated things for 0.7.0

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1194]
- [ ] `\,` inside strings
- [ ] `name: MACRO`
- [ ] `__LINE__`
- [ ] `__FILE__`
- [ ] The next step in #986

**Comment by RubenZwietering** [comment]
The deprecated predeclared symbol __LINE__ still appears in the rgbasm documentation at https://rgbds.gbdev.io/docs/master/rgbasm.5#Printing_things_during_assembly

**Comment by ISSOtm** [comment]
True! Thank you :)
