### ISSUE TITLE
Add tests to improve code coverage

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1229]
Follow-up to #996, lots of particular test gaps discovered by #1221.

Covered by #1257:

- [x] Test more invalid `STRFMT` format strings.
- [x] Test expanding macro args or interpolated symbols which contain `\n` `\r` `\t` characters.
- [x] Test illegal character escapes.
- [x] Test line continuations in string literals.
- [x] Try defining a macro inside a `REPT`, and invoke it inside+outside.
- [x] Test `BREAK` outside a `REPT`.
- [x] Test too-long, non-numeric, zero, and undefined `\<symbol>`.
- [x] Test invalid characters after line continuations.
- [x] Test `ELIF` after `ELSE` block.
- [x] Test invalid `OPT` values (also from the command line).
- [x] Test `PURGE` on an undefined symbol.
- [x] Test `EXPORT` on an anonymous label.
- [x] Test nested `REPT`/`FOR` blocks.
- [x] Test `BANK()` of a symbol in a fixed section.
- [x] Test defining data in RAM section.
- [x] Test impossible alignment in a fixed `SECTION UNION`.
- [x] Test impossible alignment in a fixed `SECTION FRAGMENT`.
- [x] Test `BANK()` for WRAM0 or HRAM symbols.
- [x] Test `SECTION` inside `UNION`.
- [x] Test `SECTION` inside `LOAD`.
- [x] Test `LOAD` inside `LOAD`.
- [x] Test `UNION` outside a section.
- [x] Test `UNION` inside `UNION`.
- [x] Test `NEXTU` and `ENDU` outside `UNION`.
- [x] Test unterminated `UNION`.
- [x] Test `ENDSECTION` outside a `SECTION`, and within a `UNION` or `LOAD`.

Covered by #1256:

- [x] `charmap_Delete` is an unused function.
- [x] Test `ATAN2`.
- [x] Test invalid fixed-point constant, e.g. `3.14q`.
- [x] Test integer constants that are too large.
- [x] Test no-digit `$` and `` ` `` constants.
- [x] Test an .asm file with CR-LF newlines.
- [x] Test macro args in string literals.
- [x] Test the `>=` operator.
- [x] Test `/` in a macro arg that isn't part of `/*`.
- [x] `macro_FreeArgs` is an unused function.
- [x] Test more than 4 `STRFMT` args so it reallocates.
- [x] Test more than 2 `PURGE` args so it reallocates.
- [x] Test `ASSERT FATAL`.
- [x] Test `FAIL`.
- [x] Test diff marks at the beginning of lines.
- [x] Test unary `+`.
- [x] Test `ldi` and `ldd`.
- [x] Test `ld [hl], [hl]`.
- [x] Test `ld` without `a`.
- [x] Test `rst` with an invalid address.
- [x] Test modulo by zero.
- [x] Test exponentiation by negative.
- [x] `sect_String` is an unused function.
- [x] `sym_FindUnscopedSymbol` is an unused function.
- [x] Test `@` outside a section.
- [x] Test `REDEF EQU` with a not-yet-defined name.
- [x] Test `REDEF EQU` on a built-in symbol.

**Comment by Rangi42** [comment]
@ISSOtm Proposal to organize the tests into subdirectories. One could be for "error conditions", since so many of these uncovered cases are such. (Of course sometimes one test case will be able to cover everything, but other times an error would interfere with or halt subsequent processing.) Some existing tests could be moved into such a subdir.

**Comment by ISSOtm** [comment]
Sure. The directory's listing is indeed huge.
