### ISSUE TITLE
Rename the RGBGFX `--output-*` options to `--auto-*`

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1243]
RGBGFX `-A -P -Q -T` are like `-a -p -q -t` but with automatically determined output filenames. Their long options are all names `--output-*`, but this is confusing. Proposal from #1240 to rename them `--auto-*` and deprecate the `--output-*` long names.

**Comment by ISSOtm** [comment]
Not necessarily deprecating the old names, but maybe only hiding them from the documentation.

**Comment by aaaaaa123456789** [comment]
Is there a reason not to deprecate them?

**Comment by ISSOtm** [comment]
To avoid people complaining. Maybe the flags are niche enough that this would be acceptable.

**Comment by ISSOtm** [comment]
Fine by me, then.
