### ISSUE TITLE
[Feature request] Allow negative alignment offsets

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1248]
From @aaaaaa123456789 's comment in #1181 :

Negative offsets should be allowed (just normalized), because people do use them occasionally. In fact, the constraints for the offset are very similar to the constraints for `-Wtruncation=1`, so why not use the same boundaries for a warning? (And this should be an enabled-by-default warning, not an error — an alignment of `4, 20` is equivalent to an alignment of `4, 4`, so this shouldn't be an error because it can be interpreted unambiguously.)

**Comment by Rangi42** [comment]
As a workaround, `align[n, -off]` is equivalent to `align[n, 2**n - off]` or `align[n, (1 << n) - off]`.

**Comment by aaaaaa123456789** [comment]
And `align[n, off]` is equivalent to `align[n, off & ((1 << n) - 1)]` in the general case, but I'd say that's just unclear.
