### ISSUE TITLE
Add generic Linux x86_64 binaries to old releases

### ISSUE THREAD

**Issue by Moth-Tolias** [gbdev/rgbds#1263]
contrary to what https://rgbds.gbdev.io/install states, https://github.com/gbdev/rgbds/releases does not offer any linux binaries, 86_64 or otherwise; only macos x86-64, win32, win64, and the source code are listed.

**Comment by ISSOtm** [comment]
Indeed, those binaries are planned for the upcoming 0.7.0 release, and we want to make them retroactively available for previous releases as per https://github.com/gbdev/rgbds/pull/1148#pullrequestreview-1515087704, but nobody on the team has managed to find enough time for it yet.

Anyone willing to spend some time is welcome to build such binaries; please post in this thread if you need any assistance ^^

**Comment by Moth-Tolias** [comment]
compiled from the 0.6.1 release: [rgbds.zip](https://github.com/gbdev/rgbds/files/13583624/rgbds.zip)

**Comment by avivace** [comment]
The two latest majors (0.5.2 and 0.6.1) now have linux amd64 builds attached

**Comment by ISSOtm** [comment]
And thank you for that! o/
