### ISSUE TITLE
Add more RGBGFX tests

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1276]
Run `contrib/coverage.bash` to see exactly what still needs testing.

- [x] GBC color curve
- [x] Reverse mode
- [x] Reading palette file formats (note that Tilemap Studio can help in generating these)
  - [x] [ACT](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577411_pgfId-1070626)
  - [x] [ACO](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577411_pgfId-1055819)
  - [x] GBC
  - [x] [PSP](https://www.selapa.net/swatches/colors/fileformats.php#psp_pal)
- [x] `-X` and `-Y` for limited mirroring
- [x] `-i/--input-tileset`

**Comment by ISSOtm** [comment]
Consider adding the files from #1519 to the test suite.
