### ISSUE TITLE
Warning/error function refactoring

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1277]
src/error.cpp defines `warn`, `warnx`, `err`, and `errx`. We only use `errx`. All warnings are currently manually coding their `"warning: "` prefix; we should use `warnx`. Also, instead of the `err` variant, we manually pass `strerror(errno)` (if that's technically necessary, then we should remove `err` and `warn` as useless).

**Comment by Rangi42** [comment]
This was a misunderstanding due to code coverage output that hadn't triggered warnings/errors.

**Comment by ISSOtm** [comment]
Yeah, some of the formatting is inconsistent, especially across tools; but I intend to have that fixed in rsgbds by making all of that common anyway.
