### ISSUE TITLE
Declared version can be affected by another Git repository

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1288]
If you download GitHub's .zip file and extract it in the presence of another Git repository, that repo's tags can influence the declared version of RGBDS when you build it.

I would call this an edge case not worth handling, except that it actually happened--someone built RGBDS inside my project, and then `rgbasm -V` would print `rgbasm v3.0.0-beta-dirty`.

We could check the repository's identity as well as its tags. If `git config --get remote.origin.url` ends with `/rgbds.git`, that might be a reliable check.

**Comment by ISSOtm** [comment]
What we really want is to pass `--git-dir` to `git`.
