### ISSUE TITLE
Why can’t use newer 7.0version in nix

### ISSUE THREAD

**Issue by carlostmgps** [gbdev/rgbds#1291]
Please update the package version in nix pleaseeeeee cuz I can only use nix to install rgbds (don’t ask me why) and it only covered to 6.? Verizon T.T

**Comment by ISSOtm** [comment]
Unfortunately, we don't control when downstream distributions update.

[Someone already opened an update request](https://github.com/NixOS/nixpkgs/issues/283282), you can add a thumbs-up reaction there to signify that you'd appreciate the update.

**Comment by ISSOtm** [comment]
(Also, FWIW, the version is 0.7.0, not 7.0 :P)

**Comment by carlostmgps** [comment]
Thankyou
