### ISSUE TITLE
Security vulnerability through fuzzing

### ISSUE THREAD

**Issue by RootUp** [gbdev/rgbds#1293]
I couldn't find any other way to report it, hence I have reported it here, hope someone could look into it.
Ref -  [GHSA-x433-53p6-jwc9](https://github.com/gbdev/rgbds/security/advisories/GHSA-x433-53p6-jwc9)

**Comment by Rangi42** [comment]
Thanks! We've reproduced and identified the bug, and are considering how best to address it.
