### ISSUE TITLE
Refactoring and style cleanup with C++

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1315]
- [x] Don't use redundant `struct` keyword in types.
      This regex will fix the single-lines ones: `perl -pe 's/\bstruct (\w+)\b(?! \{)(?=.+[;{)]$)/\1/g'`; just double-check for wrapped `for (...;` lines.
- [x] Use `nullptr` instead of `NULL`.
- [x] Use `()` instead of `(void)`.
- [x] Use references instead of `NONNULL` pointers (C++ doesn't support `[static 1]`)
- [x] Use `std::variant` instead of `union`
- [x] Replace functions with methods: `foo_Bar(struct Foo *foo, ...)` into `Foo::bar(...)`
- [x] Get rid of `((m|c|re)alloc|strdup)`
- [x] Define constructors with default field values (and optimize some `push`es to `emplace`ment)
- [ ] Get rid of `new (std::nothrow)` in favor of automatic allocation with RAII
     - [x] This will require the rgbasm parser to use [variants](https://www.gnu.org/software/bison/manual/html_node/C_002b_002b-Variants.html) and [complete symbols](https://www.gnu.org/software/bison/manual/html_node/Complete-Symbols.html) like the linker script one does
     - [ ] Re-enable ASan for rgbasm if this succeeds
    ```
    src/asm/lexer.cpp:2206:  lexerState->captureBuf = new (std::nothrow) std::vector<char>();
    src/asm/symbol.cpp:503:  std::string_view *macro = new (std::nothrow) std::string_view(body, size);
    ```

**Comment by ISSOtm** [comment]
We should look into updating `NONNULL` to use `[[gnu::nonnull]]` instead.

(Also, in general, replacing `__attribute__((ATTR))` with `[[gnu::ATTR]]` instead. This would make less code platform-specific!)

**Comment by Rangi42** [comment]
Most if not all of the `NONNULL`s should be references, as should many other functions which take pointers assumed not to be null.

**Comment by Rangi42** [comment]
After the last few weeks of refactoring, RAII, smart pointers, etc, I'm declaring this done. There are two `new (std::nothrow)`s left, both involved with how the lexer's files/mmaps/EQUs/interpolations/macro args can "leak as a feature", and fixing that (and re-enabling ASan) is a matter for #709.
