### ISSUE TITLE
[Feature request] Allow `expr * 0` to be constant 0

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1402]
As of #1399, we allow `expr && 0` and `expr & 0` to be constant 0, and `expr || non-0` to be constant 1.

`expr * 0` should also be valid to allow as constant 0. I don't *think* there would be any issues with that, and it could be helpful with `(cond * val1) + (!cond * val2)` "ternaries".

**Comment by Rangi42** [comment]
From @ISSOtm : "It feels unintuitive to me that `a * b` is *potentially* constant".

**Comment by pinobatch** [comment]
For comparison, ca65 treats `Mystery * 0` and `0 * Mystery` as constant if `Mystery` is imported.
[times0-const-testcases.zip](https://github.com/user-attachments/files/16381200/times0-const-testcases.zip) contains test cases for ca65 and RGBASM.

**Comment by Rangi42** [comment]
Besides `x * 0 == 0 * x == 0` being constant 0 even with a non-constant `x`, there are also some mathematical identities that would allow simplifying RPN expressions:

- `x + 0 == 0 + x == x`
- `x - 0 == x`
- `x * 1 == 1 * x == x`
- `x / 1 == x`
- `x & $ffffffff == $ffffffff & x == x`
- `x & -1 == -1 & x == x`
- `x | 0 == 0 | x == x`
- `x ^ 0 == 0 ^ x == x`
- `--x == x`
- `~~x == x`

Omitting the "no-op" RPN operations from those expressions would allow further simplification. For instance, right now `FloatingLabel - @` can be constant, but `FloatingLabel + 0 - @` cannot.

**Comment by ISSOtm** [comment]
I am against this, because it creates behaviour I find too astonishing:

```asm
IF DEF(ok)
    def OFS equ 0
ELSE
    def OFS equ 1
ENDC

println Label + OFS - Label ; Error if OFS is (known to be) nonzero.
```
