### ISSUE TITLE
[Feature request] Push and modify stacks in one step (for PUSHS, PUSHO, and PUSHC)

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1418]
A common pattern is to push some context and immediately add a new current context. Examples:

```asm
; section stack
pushs
section "Subsection", ROM0
...
pops

; option stack
pusho
opt b.X, goxOX
...
popo

; charmap stack, creating
pushc
newcharmap special
...
popc

; charmap stack, using
pushc
setcharmap special
...
popc
```

It would be convenient to have single commands for this. Examples:

```asm
; section stack
pushs "Subsection", ROM0
...
pops

; option stack
pusho b.X, goxOX
...
popo

; charmap stack
pushc special
...
popc
```

I'm not sure how the charmap stack would work; perhaps "new if it doesn't exist, set if it does".

**Comment by ISSOtm** [comment]
I think making the behaviour context-sensitive is a bad idea, I think it should error if it doesn't already exist.

The current syntax should be fine, there'll be a bunch of lines to define the charmao anyway, so one extra is negligible.

**Comment by aaaaaa123456789** [comment]
I'd say it should be exactly identical to the two-line version, for clarity and simplicity. So `pushc foo` should be exactly the same as `pushc` followed by `setcharmap foo`.
