### ISSUE TITLE
More accurate error when redefining the "undefined" `_NARG` and `@`

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1500]
Noticed in [this comment](https://github.com/gbdev/rgbds/pull/1498#discussion_r1752601664): `DEF(_NARG)` is false outside of macros, but you can't define or purge it yourself:

```console
% rgbasm - <<EOF
println DEF(_NARG)
def _NARG equ 0
EOF
$0
error: <stdin>(2):
    '_NARG' already defined at <builtin>
error: Assembly aborted (1 error)!
```

We could have a more accurate error message for built-ins here. (The same applies to `@` outside of sections.)

**Comment by ISSOtm** [comment]
How about “The name '_NARG' is reserved for a builtin symbol”?
