### ISSUE TITLE
syntax error, unexpected EQU, expecting : or ::

### ISSUE THREAD

**Issue by z3ugma** [gbdev/rgbds#1521]
Documenting this issue and its fix because I could not find it in the docs or on GitHub, I had to go into Discord to get an answer so I couldn't search for my problem online. 

Error:     syntax error, unexpected EQU, expecting : or ::
Fix:   add a DEF at the start of each line that uses equ

I'm getting an error message that I can't find referenced anywhere online or in the search. I've downloaded about 5-10 project repos from GitHub, each is 2+ years old, and in several of them I get this error: 
```
    syntax error, unexpected EQU, expecting : or ::
error: main.asm(32):
    syntax error, unexpected EQU, expecting : or ::
error: main.asm(33):
    syntax error, unexpected EQU, expecting : or ::
error: main.asm(34):
    syntax error, unexpected EQU, expecting : or ::
error: main.asm(37):
    syntax error, unexpected EQU, expecting : or ::
error: main.asm(40):
    syntax error, unexpected EQU, expecting : or ::
```

The statements are of the variety 
```
PLAYER_WIDTH   EQU 7
PLAYER_HEIGHT  EQU 7

TARGET_COL     EQU 16
TARGET_ROW     EQU 7
```

most of these are made for RGBDS pre-0.7.0 that expected different syntax (equ without def)
add a def at the start of each line that uses equ
```
DEF PLAYER_WIDTH   EQU 7
DEF PLAYER_HEIGHT  EQU 7

DEF TARGET_COL     EQU 16
DEF TARGET_ROW     EQU 7
```

enhancement: Could the parser catch this and describe the fix in the error message?

**Comment by z3ugma** [comment]
I will reference this commit as an example of a project that went back and added `DEF` 
https://github.com/ISSOtm/gb-starter-kit/commit/aa5d9a7a4344343436ded80de27da7bcdb2dfb15

**Comment by Rangi42** [comment]
Yeah, [release 0.7.0 deprecated](https://github.com/gbdev/rgbds/releases/tag/v0.7.0) defining symbols without using `DEF`, and [0.8.0 removed it](https://github.com/gbdev/rgbds/releases/tag/v0.8.0). Before it was officially deprecated, we already supported `DEF`, and [0.6.0 documented it](https://rgbds.gbdev.io/docs/v0.6.0/rgbasm.5#:~:text=You%20may%20use%20the%20older%20syntax).
