### ISSUE TITLE
ci: clean old container images, document how to push images

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbds#1530]
Following up https://github.com/gbdev/rgbds/issues/1509 : 

- [x]  document how to manually push an image (e.g. old tag, without having to repush it)
- [x] find a way to clean up the old artifacts

**Comment by Rangi42** [comment]
@avivace Any updates on auto-deleting all those `sha256:...` packages?

**Comment by ISSOtm** [comment]
`GITHUB_TOKEN` [cannot be granted `admin` permissions](https://github.com/gbdev/rgbds/actions/runs/12076617500/workflow) for a scope ([only `read`, `write`, or `none`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions)), and `admin` perms [are required to delete](https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages#about-scopes-and-permissions-for-package-registries) containers.

So I think what needs to be done, is for @avivace to generate a PAT for the `gbdev` org (so it's not tied to a specific maintainer), and pass that to the action via secrets.

**Comment by Rangi42** [comment]
@avivace I'm just a "member" of gbdev so can't do this myself, but please [generate a fine-grained PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token) for this.

**Comment by avivace** [comment]
This is now "fixed" by using a PAT from a user that has the `write:packages` scope. We should investigate how to do this properly with a fine-grained token (that apparently can access the 'delete packages from an org' endpoint but only if it's of the type 'GitHub App').
