### ISSUE TITLE
[Feature request] `LOAD FRAGMENT`

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1537]
`LOAD FRAGMENT` was originally supported since #736, but was removed in 1d012682497e5060df257a12c2a3e3388d43e4ab. #869 has more explanation:

> `LOAD FRAGMENT` needs to be removed anyway, as its semantics are buggy.
All sections in RGBDS are assumed to be contiguous; this is the basis for a *lot* of the implied behavior. `LOAD FRAGMENT` breaks that assumption.
>
> `LOAD` causes a "RAM" section to mirror (size-wise and label-wise) a segment of a "data" section. This makes sense. `LOAD UNION` merely allows the RAM block of data to share space with others, like the well-known "overlay" feature present in a lot of systems.
>
> `LOAD FRAGMENT`, however, enables breaking the RAM section's *actual* contents across several, non-contiguous ROM sections. This breaks the implicit assumption that there is a 1:1 mapping between the ROM and "RAM" sections.

#1535 brought up the possibility of adding it back, if we can avoid buggy semantics.

**Comment by aaaaaa123456789** [comment]
```
SECTION "Test", ROM0[0]
A:
  db 1

LOAD FRAGMENT "RAM section", WRAM0[$c000]
B:
  db 2
ENDL

C:
  db 3

LOAD FRAGMENT "RAM section"
D:
  db 4
ENDL```

I'd expect the ROM contents to be `01 02 03 04`, and the symbols to be:
```
00:0000 A
00:0002 C
00:C000 B
00:C001 D
```

**Comment by Rangi42** [comment]
@aaaaaa123456789 Your example assembles as expected with #1552:

```console
$ cat foo.asm
SECTION "Test", ROM0[0]
AA: db 1
LOAD FRAGMENT "RAM section", WRAM0[$c000]
BB: db 2
ENDL
CC: db 3
LOAD FRAGMENT "RAM section", WRAM0
DD: db 4
ENDL
$ ./rgbasm -o foo.o foo.asm
$ ./rgblink -x -o foo.gb -n foo.sym foo.o
$ xxd foo.gb
00000000: 0102 0304                                ....
$ cat foo.sym
; File generated by rgblink
00:0000 AA
00:0002 CC
00:c000 BB
00:c001 DD
```
