### ISSUE TITLE
RGBGFX bugs

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1556]
RGBGFX still has some bugs left before 0.9.0 can be released.

- [x] `-C/--color-curve` is breaking somehow on 32-bit MinGW. (See #1554)
- [x] `-r/--reverse` with `-d/--depth 1` is breaking inconsistently somehow on different platforms. (See #1555)
- Anything else we might discover?

**Comment by ISSOtm** [comment]
Since the platforms specific breakage is fixed in those PRs, I'll be closing this issue. We'll keep finer discussion to the PR itself; closing this helps reduce mental overhead IMO
