### ISSUE TITLE
[Feature request] Allow multiple labels per line

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1558]
Based on [leaderjord's question on Discord](https://discord.com/channels/303217943234215948/790920525253836912/1310025072886546482).

Now that `Global:` and `.local` labels are both column-independent, it should be possible to unambiguously lex and parse multiple labels per line. This would avoid surprise based on an implementation detail of the parser rules, and would allow use cases like these:

```asm
MyColor: MyColour: dw $7fff
```

```asm
ZeroFill:
    xor a
Fill: .loop
    ld [hli], a
    dec c
    jr nz, .loop
    ret
```

```asm
MyData: MyDataRow: my_data_macro "-"
    MyDataRowEnd:
    my_data_macro "A"
    my_data_macro "B"
    my_data_macro "C"
; data size is MyDataRowEnd - MyDataRow
```

**Comment by Rangi42** [comment]
Or even:

```asm
Fill: .loop: ld [hli], a :: dec c :: jr nz, .loop :: ret
```

:3

**Comment by ISSOtm** [comment]
This breaks more of third-party tools' assumptions than it brings benefits, IMO. I'd rather reject this unless a compelling argument is made for it.

Current workaround, if you *really* value your vertical space:

```asm
def NL equs "\n" ; NewLine
Fill: NL .loop: ld [hli], a :: dec c :: jr nz, .loop :: ret
```
