### ISSUE TITLE
[Feature request] Warn about `PUSHC/PUSHO/PUSHS` without `POPC/POPO/POPS`

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#1559]
This file assembles without any warnings, even at `-Weverything`:

```asm
section "test", rom0
pushc
pusho
pushs
```

We have `-Wunterminated-load` for `LOAD` without `ENDL`; maybe we should have `-Wunterminated-push` for these directives.

**Comment by ISSOtm** [comment]
I'd call it `unmatched-directive`, maybe? And, yes, that's a good idea.
