### ISSUE TITLE
Provide debian binaries

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbds#278]
If this is an appreciated contribution, I'd like to work on providing debian binaries for debian-based systems.

As standalone `deb` files and/or with a repository offering the last version.

**Comment by AntonioND** [comment]
Sure, go for it. What exactly do you plan to add to the repository, just an extra folder?

**Comment by avivace** [comment]
I think that a separate repo containing the files for the build would be better, so I won't fill the commit history with tests and debian rules files.

Ideally, I could use a separate branch too.

**Comment by AntonioND** [comment]
Well, in principle I wouldn't mind having the rules in the master branch. After all, many projects have folders just to build it for different platforms. Of course, if someone else wants to add rules for other distros, that would be fine, too.

**Comment by Ben10do** [comment]
Sounds like a nice idea! I personally think that the [GitHub releases page](https://github.com/rednex/rgbds/releases) is *really* the place for this, but I wouldn't mind the binaries being in the main repo if that's easier (e.g. to submit pull requests for, or to clone from the command line).

**Comment by AntonioND** [comment]
I think it's just easier to have the package generation files in the master branch. We could have a `dist/debian` folder with the needed files, for example. If someone wanted to add scripts for other distros, they could be added to.

Of course, I'm not talking about the final `.deb` file, just the files needed to generate it.

**Comment by rtandy** [comment]
Not sure if this is still wanted. I created Debian packaging of rgbds for my own use: https://github.com/rtandy/pkg-rgbds. If there is enough interest, I'd be willing to work on pushing that into Debian itself (and from there into derivatives e.g. Ubuntu).

**Comment by ISSOtm** [comment]
What's your status on this, @rtandy @avivace?

**Comment by rtandy** [comment]
Unfortunately I put this in one of my backlogs and then ended up never working on it again. It's still something I'm interested in, but don't treat me as a blocker to anyone else working on it. I would absolutely be willing to review or co-maintain any packaging work aimed at submission to Debian.

**Comment by ISSOtm** [comment]
Alea jacta est, lol https://mentors.debian.net/package/rgbds/

**Comment by rtandy** [comment]
That's great, thank you for working on it! I can't sponsor the upload 
but I can at least provide a review. I'll try to do that soon.

**Comment by ISSOtm** [comment]
Thank you very much! If it can help with the sponsoring process, that'd be a good start.

I asked on IRC, and there's essentially no way that it'll make it into bullseye (they should be hitting the hard-freeze today, and are already in the soft-freeze), but it's still worth getting done, imo.

**Comment by ISSOtm** [comment]
There's been no significant updates from this, but the overall reactions I got from the Debian people I interacted with was "if you're not using Debian, you shouldn't propose a Debian package". So while I'd love to provide better support (and despite setting up a Debian chroot just for this), it seems that furthering this must be done by a regular Debian user.

Hence: if you're a Debian user, and wish for RGBDS to be packaged for your distro, please hmu (either reply to this issue, or use the contact info near the top of the README).

**Comment by pinobatch** [comment]
My main GB dev PC runs Xubuntu. I used to regularly use Debian stable until a couple weeks ago. The Ubuntu docs seem to imply that the easiest way to get a package into Ubuntu is to get it into Debian first. From [Ubuntu Packaging Guide > Packaging New Software](https://packaging.ubuntu.com/html/packaging-new-software.html):

> There are a number of paths that a package can take to enter Ubuntu. In most cases, going through Debian first can be the best path. This way ensures that your package will reach the largest number of users as it will be available in not just Debian and Ubuntu but all of their derivatives as well. Here are some useful links for submitting new packages to Debian: \[links to Debian Mentors FAQ and WNPP]

What did the people you interacted with think of Ubuntu pushing people their way?

**Comment by avivace** [comment]
> There's been no significant updates from this, but the overall reactions I got from the Debian people I interacted with was "if you're not using Debian, you shouldn't propose a Debian package". So while I'd love to provide better support (and despite setting up a Debian chroot just for this), it seems that furthering this must be done by a regular Debian user.
> 
> Hence: if you're a Debian user, and wish for RGBDS to be packaged for your distro, please hmu (either reply to this issue, or use the contact info near the top of the README).

Debian user and I'd love to help with the packaging - but still, I have little time for this

**Comment by pinobatch** [comment]
Toward this end, I filed #1160 to allow building a slice of the regression test suite that conforms to the Debian Free Software Guidelines. A user asked in a tongue-in-cheek reply why I was so focused on RGBDS as a means to the end of packaging SameBoy.

Mostly it's that SameBoy and compelling Free games that build-depend on RGBDS might serve to convince sponsors that [SM83 support in Binutils](https://sourceware.org/binutils/docs-2.41/as/Z80-Options.html) isn't quite enough. I've noticed that the Debian project discourages requesting redundant software to perform the same task as an existing package. From ["Introduction for maintainers: How will my package get into Debian?"](https://mentors.debian.net/intro-maintainers/):

> Debian is a distribution, not a general purpose repository. Many of us do not believe every piece of free software necessarily belongs in Debian. Please do not treat Debian as a platform to advertise your own software, unless there is some real request for it.

**Comment by ISSOtm** [comment]
I'd argue that RGBDS stands out on its own despite any Binutils SM83 support, for the same reason that nasm/yasm are included despite much more extensive x86 support in Binutils. More arguments in that regard are of course useful, though I'm not sure if being a build-dep of SameBoy would be worth much if Debian doesn't want to distribute SameBoy in the first place.

**Comment by ISSOtm** [comment]
Update: the current effort is https://mentors.debian.net/package/rgbds/, borne by @Robbi-Blechdose at https://github.com/Robbi-Blechdose/rgbds-deb/tree/debian

**Comment by avivace** [comment]
Closing this as we moved @Robbi-Blechdose work to https://github.com/gbdev/rgbds-deb
