### ISSUE TITLE
[Feature request] Explicit build time specification

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#286]
As @bentley mentioned in #170, build non-determinism can be a bad thing. Right now, the time- and date-related symbols (such as `__UTC_YEAR__`) always take the current value of the system clock, which can become a problem for repeatable builds.

What I'm proposing is to add a command-line option to rgbasm that would select a build time for these symbols, overriding the system clock. This way, repeatable builds are easier to achieve.

The exact format would be a matter of discussion, but I think that at least raw UNIX timestamps (`-T 1528248225`) and/or ISO 8601 timestamps (`-T 2018-06-06T01:23:45`) should be supported.

**Comment by AntonioND** [comment]
I've left a comment in #649 to this respect. We should be using this: https://reproducible-builds.org/docs/source-date-epoch/
