### ISSUE TITLE
Maintainership of the project

### ISSUE THREAD

**Issue by AntonioND** [gbdev/rgbds#369]
Hi all,

It's no secret that I haven't been as responsive as a maintainer should be. Maintaining this project hasn't been a priority for me for some time and I don't want to be responsible for merging changes such as https://github.com/rednex/rgbds/pull/329 without proper review. I just have other things going on in my life.

Basically, there are two options:

1. External contributors decide to review code and make it easier for me to trust PRs so that I can merge them quickly (please, use the code review features of GitHub so that it's clear that you agree with the PR). If this is the case I'm happy to keep merging PRs and dealing with the admin stuff of this project.

2. Someone else decides to take maintainership of the project and deal with all possible issues that arise in the future. I would step down as maintainer in that case.

I should also mention that I'm not the only one with write access to this repository. In case something happened to me there are other 2 people that could take care of this (I think).

I will try to take a look at all PRs in the following days (sorry about the huge delays).

I should also mention I'm concerned about the possibility of something like this happening (as unlikely as it may be with this niche project): https://github.com/dominictarr/event-stream/issues/116

**Comment by Ben10do** [comment]
I can certainly empathise with your situation, but first: I'd like to thank you for doing a great job maintaining rgbds! Going forward, I think either of these are sensible options.

As for what I can do to help you out:

**Regarding Option 2:** I'm personally in a similar situation to you, so I haven't contributed much lately, and would be reluctant to take over maintenance of rgbds (at the moment, at least).

**Regarding Option 1:** However, I have still been keeping an eye on the project, so, @AntonioND, if you ever would like a another pair of eyes to look at a PR (such as the one you linked), feel free to request a review from me, and I'll take a look as soon as I can. _(Though I can't guarantee that I'll take a look at all of them without being prompted)_

Of course, the more reviewers, the better – so it'd be great if we could get code reviews, approvals, and change requests from other people with an interest in these PRs!

---

(w.r.t. write access: if you're referring to the three members of the rednex organisation, I don't seem to have write access to this repo, but I do have access to Travis… Apologies if you're referring to someone else!)

(also, thanks for linking to that issue; that certainly was a scary situation! 😰)

**Comment by dbrotz** [comment]
You're not getting paid for this. It's perfectly understandable that you have other priorities.

I can try to help review some PRs.

**Comment by ISSOtm** [comment]
I would like to apply for push access to this repository.

While I don't know the code base nearly as much as any of you three, I believe I know enough that I can learn as I go, especially from other members' reviews; however, I am very active and willing to tackle issues and review PRs, especially as a [regular](https://github.com/ISSOtm/gb-boilerplate) and [power](https://github.com/ISSOtm/rgbds-structs) user of RGBDS.

I know asking this is pretty blunt of me, but you seem to be really lacking time and/or motivation lately (and it's fine, honestly), and nobody else seems willing to take the position.

As for what damage I could do to the code base (referring to that event-stream problem), I think I've been in GBDev for long enough, and that my real identity is clear enough, that there is no risk.

**Comment by AntonioND** [comment]
@ISSOtm fine by me, I've added you.

**Comment by ISSOtm** [comment]
Thank you!
