### ISSUE TITLE
`version.o` not being rebuilt

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#376]
RGBDS compiled from a fresh clone and from a clone just `pull`ed report different versions (`rgbasm -V`)

@NieDzejkob pinpointed it to `version.o` not being rebuilt.

**Comment by AntonioND** [comment]
I guess this happens because of ``BUILD_VERSION_STRING`` changing but the object file being already there. I guess that the fix would be to let the build system create a header file with ``BUILD_VERSION_STRING`` and make ``version.c`` include that header.

**Comment by ISSOtm** [comment]
Wouldn't making `version.o` a phony target basically do the trick?

**Comment by NieDzejkob** [comment]
I feel like that could work. I don't have the time to test that at the moment, though.

**Comment by ISSOtm** [comment]
> I guess this happens because of `BUILD_VERSION_STRING` changing but the object file being already there. I guess that the fix would be to let the build system create a header file with `BUILD_VERSION_STRING` and make `version.c` include that header.

But unconditionally emitting the string would cause the file to be updated, therefore Make would always remake it, which is strictly equivalent to making the target phony.

**Comment by ISSOtm** [comment]
Fixed by #465.
