### ISSUE TITLE
Can't terminate macro definitions using `equs`

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#388]
The following program fails to compile:
```
issotm@link-panda tmp.wc2tR3fCpU% cat test.asm
end_macro equs "endm"

x: MACRO
endm
issotm@link-panda tmp.wc2tR3fCpU% rgbasm test.asm
issotm@link-panda tmp.wc2tR3fCpU% cat test2.asm
end_macro equs "endm"

x: MACRO
end_macro
issotm@link-panda tmp.wc2tR3fCpU% rgbasm test2.asm
ERROR: test2.asm(3):
    Unterminated MACRO definition.
```

This is relevant to the workaround I'm trying to make for #256. ~~A solution without this is possible, but basically entirely disregards the Principle of Least Astonishment.~~ Actually, without this, a clean solution isn't possible at all.

**Comment by dbrotz** [comment]
The way that the parser finds the `ENDM` that terminates a macro is kind of a hack. It scans the source code itself instead of using the lexer, so no `EQUS` substitutions are performed.

It should be noted that if we start doing `EQUS` substitutions inside macro definitions, it will break backwards compatibility.

```
X EQUS "printt \"a\\n\""

m: MACRO
	X
ENDM

PURGE X

X EQUS "printt \"b\\n\""

	m
```

Currently, this prints "b". If X were substituted in the definition, it would print "a" instead.

**Comment by ISSOtm** [comment]
That would only happen if the substitution was written into the buffer, but if it's found that a symbol is actually a string equate, we could expand it *after* writing it to the buffer.

This could also fix things like
```
stealthy_macro equs "MACRO"

assert: MACRO
internal: stealthy_macro
ENDM
ENDM
```

**Comment by dbrotz** [comment]
I'm not sure what you mean by that. What would you expect the `assert` macro's buffer to contain?

**Comment by ISSOtm** [comment]
```
internal: stealthy_macro
ENDM
```

**Comment by ISSOtm** [comment]
The idea is that whenever a symbol is encountered, it's pasted into the buffer as-is, but then it's expanded and its expansion is processed without being emitted into the buffer.

This means that symbols relevant to the macro's parsing will be expanded at two different times, though. This could cause breakage, but either:

- We assume it won't happen; or
- If a token contains a symbol relevant to parsing (`ENDM`), the symbol is expanded in place

The former can cause some hard-to-debug errors if misused, the latter might violate the Principle of Least Astonishment.

**Comment by dbrotz** [comment]
OK. I see what you're saying now. In my opinion, it would be kind of confusing to expand string equates in both the definition and the invocations, but with different rules. What are you trying to use this for?

**Comment by ISSOtm** [comment]
The symbols would only be expanded to look for macro defs and `ENDM`s.

It can make sense to have the double evaluation if you consider the compiler as reading the macro definition once to store it, and a second time each time it's called.

I agree this can sound confusing, but `equs` straight up not working also confused me a bunch

**Comment by dbrotz** [comment]
The way it currently works can be described as the assembler treating everything between `MACRO` and `ENDM` as a black box until you invoke the macro, but the documentation doesn't explain that.

Anyway, I can see how this new behavior could enable more complex macro meta-programming. The documentation should be updated to explain exactly how macros and `EQUS` interact.

**Comment by ISSOtm** [comment]
I wanted to implement #256 by having macros that generate macros using built-in assembler commands (namely, `charmap`) but then I needed a way to declare the macro and run a tiny bit of code afterwards. This is not possible due to this; if `equs` were expanded for `ENDM`, I could have `end_charmap equs "ENDM\n<some setup>`, but I can't.

**Comment by dbrotz** [comment]
I think it would be easier to implement #256 in RGBDS itself than changing the way macros work.

**Comment by ISSOtm** [comment]
Whichever will come first :p

**Comment by dbrotz** [comment]
#256 doesn't look too hard to implement. It's just that's there no clear proposal on what the feature should look like. `setcharmap` looks like a good idea, but there are some unanswered questions. I can expand on this in #256.

**Comment by ISSOtm** [comment]
Let's call this "unlikely to be added", but I'd rather keep the issue open in case one day someone attempts to tackle it.
