### ISSUE TITLE
[Feature suggstion] REPT with automatic index

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#432]
This is a common pattern:
```
X = 0
REPT n
    ; ...
X = X + 1
ENDR
PURGE X
```

Would it be better to write it like this?
```
REPT n, X
    ; ...
ENDR
```

```
REPT [X] n
    ; ...
ENDR
```

```
REPT FROM a TO b
    ; ...
ENDR

REPT FROM c TO d IN X
    ; ...
ENDR
```

**Comment by aaaaaa123456789** [comment]
Since you're suggesting something that is basically a for loop (the traditional kind, not the C kind), I'd suggest a new keyword for it. While it is semantically similar to `REPT`, the difference (particular if you introduce start and end values, or even better, start, end and step values) is significant to the reader.

**Comment by ISSOtm** [comment]
So basically `FOR X FROM a TO b [STEP c]`?

**Comment by aaaaaa123456789** [comment]
Pretty much. Not sure if `FOR` is available as a keyword, but it should be.

**Comment by ISSOtm** [comment]
What separators would you use, then?

**Comment by pinobatch** [comment]
`REPT n, X` is almost identical to the [syntax accepted by ca65](https://cc65.github.io/doc/ca65.html#ss11.92).

**Comment by aaaaaa123456789** [comment]
That syntax is probably very natural for ca65 users, but it definitely looks out of place if you've never used the tool. (Upon seeing `rept foo, bar`, I'd first think it's a mistake, and after checking that it does build, that it is a range of some sort. There's nothing at all in that syntax telling you that a variable is being declared.)

The question is which group to favour. I'm definitely in the latter group; I don't even know where to get ca65 from, let alone how to use it. But there's probably quite a few people who write code for both the GB and the NES around, so the point is worth considering from both sides.

**Comment by pinobatch** [comment]
Practical example of the ca65-inspired syntax:
```
div10table:
  rept 256, val
  db val / 10
  endr
bitreversetable:
  rept 256, val
  db ((val&$80)>>7) | ((val&$40)>>5) | ((val&$20)>>3) | ((val&$10)>>1) \
     | ((val&$08)<<1) | ((val&$04)<<3) | ((val&$02)<<5) | ((val&$01)<<7)
  endr
```

**Comment by aaaaaa123456789** [comment]
Hopefully you wouldn't write `val&$40` without spaces in code you expect people to read...

Anyway, that syntax looks completely unnatural to me. Nothing at all points to `val` being declared or assigned; there's not the slightest hint that it's a new variable being used as a loop counter.

**Comment by ISSOtm** [comment]
@aaaaaa123456789 Again, if none of those syntaxes are good, what would be a better one?

**Comment by Rangi42** [comment]
I'd appreciate something that supports nonzero start values like 1 or -1, and ideally non-unit step values as well. And ax6 with ax6 that `rept` is not an obvious keyword for a for loop. `for`, or `foreach` in case projects are more likely to already define "`for`", could work. With arguments like Python's `range`: one is the exclusive endpoint, two are the inclusive start and exclusive end points, three are start, end, step.

```
; db 0, 1, 2, ..., 253, 254, 255
foreach X, 256
    db X
endf
````

```
; db 1, 2, ..., 9, 10
foreach Y, 1, 11
    db Y
endf
```

```
; db 2, 4, 6, 8, 10
foreach Z, 2, 12, 2
    db Z
endf
```

**Comment by aaaaaa123456789** [comment]
I'd argue for the endpoint to be inclusive, because that tends to be more natural. (Python loves doing things its own particular way, as always.)

**Comment by Rangi42** [comment]
Really? If the default is zero-indexing, I'd expect an exclusive endpoint, since the N items would be 0 to N-1 and you probably have `N` defined as a constant.

**Comment by ISSOtm** [comment]
The good part of exclusive end-points is being able to specify `[begin, begin+end[` without an extra `- 1`.
For implementation / my sanity's sake, `ENDR` will terminate that block no matter what. Given the special-casing treatment they get, I *really* to avoid introducing additional control block keywords.

**Comment by Rangi42** [comment]
That's easy to rationalize; `foR` / `endR`.

**Comment by ISSOtm** [comment]
Same goes with the opening one, then. They need to be paired by the "copier" code, and that part is a hack already.

**Comment by Rangi42** [comment]
These should be equivalent:

```
FOREACH <var>, <start>, <stop>, <step>
	<body>
ENDR

<var> = <start>
REPT (<end> - <start> - 1) / <step> + 1
	<body>
<var> = <var> + <step>
ENDR
```

One difficulty is that updating `<var>` for each iteration would need some kind of special handling, since current `MACRO` and `REPT` expansion just "pastes in" lines and lets the parser handle them. This *could* add extra `<var> = ...` lines to get the right behavior, but that would give odd reported line numbers.

**Comment by ISSOtm** [comment]
There is a handler for `REPT`'s "wrapping" behavior (in `yywrap`)
