### ISSUE TITLE
HTML man pages for master as well?

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#458]
Currently, the `docs` folder contains man pages exclusively for the current release, which makes sense; however, some users do use `master`, and it means the final HTML render is only "tested" at release time.
Would it be a good idea to add a `master` (tentative name) folder containing the HTML man pages, so both are present?

**Comment by bentley** [comment]
How about continuous deployment on https://rednex.github.io/ instead?

Contributors are often afraid to edit any kind of markup when adding new features, and I’m concerned large diffs of autogenerated HTML in the history might discourage them further.

**Comment by ISSOtm** [comment]
Doable as well, we'd just need to discuss the implementation details.
For the infrastructure, GitHub has conveniently rolled out their new [Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions), but what I'm less sure about is, for example, under which URL the pages should be deployed, if they should be in a separate repo, etc.

**Comment by JL2210** [comment]
Fixed: https://rgbds.gbdev.io/docs/master/
