### ISSUE TITLE
Allow RGBGFX to take an external palette specification

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#487]
Rationale: everybody's having headaches regarding the "indexed PNG" thing. It makes sense, it *should* work properly, but tooling for it is in practice abysmal.

Proposal: support input palettes like SuperFamiconv. Input formats:
- PNG (4 pixels/stripes)
- Bin data (quadruplet of either RGB888 or RGB555 colors)
- Text (CSS specs directly via CLI args)

Problem: how to make this work with CGB images?

**Comment by Hawkbat** [comment]
Would it also be possible to make an "inferred palette" with the first four RGB values encountered?

**Comment by ISSOtm** [comment]
That's already the case, with the inferred palette being sorted by brightness. But sometimes you want to have white in your sprites, for which this solution isn't satisfactory.

**Comment by Rangi42** [comment]
GBA has 16 palettes of 16 colors each, rather than 8 of 4. pokeruby/pokeemerald sometimes have grayscale images, but other images are colored entirely with the first palette in a set. For example, <https://github.com/pret/pokeemerald/blob/master/graphics/frontier_pass/tiles.png>. So CGB images could do the same: let the input palette file specify 4xN colors for N palettes, and expect the input image to be either grayscale or colored with the first 4.

**Comment by ISSOtm** [comment]
Suggested workflow after a lot of discussion: first, create a "default" palette—either by following the PLTE chunk if any, or by gathering all colors in the PNG otherwise. Then, if a palette is specified on the CLI, override.

Also useful: taking the spec both as a list of colors directly (`--palettes 000,555,aaa,fff;012,345,678,9ab`), or as a separate file (`--palette @file`)

Suggested: a `--bgp` shorthand? Maybe `--dmg-pal` instead, since it also works for OBJ palettes.

**Comment by Rangi42** [comment]
`--dmg-pal` as shorthand for `--palettes fff,aaa,555,000` would be convenient.

**Comment by ISSOtm** [comment]
I meant `--dmg-pal 0xE4`, `--dmg-pal 0x11100100`. I considered accepting the RGBASM syntax directly, but `$` is problematic on Linux, and `%` on Windows.

**Comment by Rangi42** [comment]
Base-4 like `rgbasm`'s "Gameboy graphics" numeric format would also be convenient (it matches with how you'd input graphics directly, and the four values are obvious). Maybe `--dmg-pal G3210` since backtick would need escaping.

**Comment by ISSOtm** [comment]
Or prefix-less?
