### ISSUE TITLE
Reduce space taken by file names in object files

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#491]
> <@mid-kid> that's a funny when I have an 8.2MB object file (for a 2MB game) sitting here 'cause the format has a string containing the full file stack for every single one of the relocations, in case it needs to show an error.

Suggested fix: make a table of file names, and index into that. That would require some work from RGBASM (maintaining a hash table of file names, plus the associated memory management).

Also, what should be the format of each entry? Should each entry directly point to its parent (better if macros are called only once), or file stacks be stored separately (better if a macro is invoked from several places)?

**Comment by Rangi42** [comment]
Macros are likely to be invoked more than once, and deep macro nesting is likely to be using very common "utility" macros further in, so probably the latter.

**Comment by ISSOtm** [comment]
Here's a proposal for the structure to use, then:

File paths are stored in a table of size 256 (it is an error to reference more than 256 unique files)
Macro names are stored in a table of size 256, same as above
File stack entries are also stored in a table of size 65535:
```
  WORD: ID of parent entry, -1 = no parent
  BYTE: ID of file name
  BYTE; ID of macro name, -1 = none
  BYTE: Number of REPT levels
    REPT <nb of levels>
      BYTE: Iteration #
    ENDR
  BYTE: Line number
```

**Comment by Rangi42** [comment]
> it is an error to reference more than 256 unique files

You mean one file can't `INCLUDE` more than 257 others? That could be a problem:

- https://github.com/huderlem/pokered/blob/expand-dex/main.asm#L4928
- https://github.com/Rangi42/polishedcrystal/blob/master/data/maps/scripts.asm
- https://github.com/pret/pokecrystal/blob/master/data/maps/blocks.asm
- https://github.com/pret/pokecrystal/blob/master/gfx/pics.asm

**Comment by ISSOtm** [comment]
It means that there can only be up to 256 files included that generate a patch, per translation unit.

**Comment by AntonioND** [comment]
Yeah, I don't see the reason to save a couple of bytes and create an artificial restriction. 16 bits should be fine.

**Comment by aaaaaa123456789** [comment]
Considering that `assert` can generate patches, and that macros with assertions could easily be included in many places, I wouldn't be too shocked if 65,536 was reachable too. I'd recommend storing a special "unknown" value instead of just failing if this limit is exceeded — it's not going to be a good day for whoever hits the limit and suddenly can't build anymore.

**Comment by daid** [comment]
Why put in a 16bit limit? Both memory and diskspace are relatively cheap. 32bit all the things I would say.
Also, I'm pretty sure I will go over the 256 different macros in the FFA disassembly at some point.


And, it's not uncommon for intermediate files with debug information being a lot bigger then the final result. For example, other project of mine, 20MB executable, of which 15MB is debug information. I'm willing to argue, keep the current "large" implementation, as it's simpler (and thus less likely to break), doesn't cause any real-world issues.

**Comment by ISSOtm** [comment]
I think the best course of action is to implement this, measure on several projects, and assess whether the limits are reasonable. Since they are only coupled to the bit width of a variable, they should be easy to change once all the facilities are in place.
