### ISSUE TITLE
Anonymous labels

### ISSUE THREAD

**Issue by NovaSquirrel** [gbdev/rgbds#497]
I would like anonymous/unnamed labels that function the same way that ca65's do: https://cc65.github.io/doc/ca65.html#ss6.6

These are very helpful for short branches or loops that might not justify a more descriptive name, but currently require one.

**Comment by pinobatch** [comment]
Example from the [ca83](https://github.com/pinobatch/little-things-gb/tree/master/ca83/src) demo:
```
  ld a, %00001100
  ldh [rBGP], a
  ld a, LCDCF_ON|LCDCF_WINOFF|LCDCF_BG8000|LCDCF_BG9800|LCDCF_OBJOFF|LCDCF_BGON
  ldh [vblank_lcdc_value], a
  ldh [rLCDC], a

:
  rst wait_vblank_irq
  jr :-
```

**Comment by ISSOtm** [comment]
Does ca65 require no whitespace between the colon and pluses/minuses? This is important for dealing with
```asm
    jr :+ + 1
:
```

**Comment by NovaSquirrel** [comment]
Yes, as far as I can tell no whitespace is required. `bra : + + 1` is a syntax error

**Comment by ISSOtm** [comment]
Welp, I hoped that this would be simple to implement, but that requires a new token type... I guess that's one more blocked by #485...
