### ISSUE TITLE
[Feature request] Forward declarations of labels

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#506]
It often makes sense to have code above the entry point of a function:

```
DelayFramesContinue:
  pop af
  dec a
DelayFrames:
  and a
  ret z
  push af
  call DelayFrame
  jr DelayFramesContinue
```

(This particular function was an `rst`, which explains the strange style in part.)

This forces creating a new global label (assuming that you'll eventually want to jump to that code above the entry point), which for longer functions also requires juggling two local label spaces. It's overall a bad thing.

So what I'm asking for is the ability to forward-declare a global label. Something like this (as always, feel free to propose a syntax that would be nicer/easier to parse/more understandable/dog-friendly/etc.):

```
DelayFrames: forward
.loop
  pop af
  dec a
:
  and a
  ret z
  push af
  call DelayFrame
  jr .loop
```

This creates a new local scope as any global label, etc., but defers setting the actual value of the label until a special marker is encountered. (I used a lone colon here because that's an invalid label otherwise, but I'm not particularly attached to it.)

**Comment by NieDzejkob** [comment]
I would have imagined a solution like this:
```
DelayFrames.loop:
    pop af
.some_other_local_if_needed:
    dec a
DelayFrames:
    and a
    ret z
    push af
    call DelayFrame
    jr .loop
```
I feel like this is a bit better, since it uses concepts the user already knows.

**Comment by aaaaaa123456789** [comment]
The issue with that version is that it declares the main label twice. That's very accident-prone, and it's also a lot harder to read when the function isn't ten lines long. ("Is this the same label as before?")

**Comment by NieDzejkob** [comment]
Fair point. I suppose we could have either a lone `:` or `.` replace `DelayFrames:`. The issue with `.` is that, by analogy:
```
Foo:
    jr .   ; jr Foo
```

**Comment by ISSOtm** [comment]
I would simply use
```
DelayFramesImpl:
.loop
  pop af
  dec a
.entryPoint
  and a
  ret z
  push af
  call DelayFrame
  jr .loop

DelayFrames equ DelayFramesImpl.entryPoint
EXPORT DelayFrames
```
Granted, this doesn't work if RGBASM doesn't know the address of the section, but then you can use an `EQUS` instead, at the cost of having to `include` it in every file.

**Comment by aaaaaa123456789** [comment]
> Fair point. I suppose we could have either a lone `:` or `.` replace `DelayFrames:`. The issue with `.` is that, by analogy:
> 
> ```
> Foo:
>     jr .   ; jr Foo
> ```

How is this an issue? Note that this is currently not valid syntax.

**Comment by NieDzejkob** [comment]
What I meant is that, the definition-by-lone-dot suggests the above syntax is available, which *might* be undesirable.

**Comment by ISSOtm** [comment]
> The issue with that version is that it declares the main label twice. That's very accident-prone, and it's also a lot harder to read when the function isn't ten lines long. ("Is this the same label as before?")

Unless it's required that the label be defined, such that the following without the `DelayFrames:` declaration is an error:
> ```asm
> DelayFrames.loop:
>     pop af
> .some_other_local_if_needed:
>     dec a
> DelayFrames:
>     and a
>     ret z
>     push af
>     call DelayFrame
>     jr .loop
> ```

**Comment by aaaaaa123456789** [comment]
Perhaps a lone dot could _always_ refer to the main label of the current scope, then.

**Comment by ISSOtm** [comment]
I'm also thinking #497 may offer a different solution to this problem. Thoughts?

**Comment by aaaaaa123456789** [comment]
How would that work?

**Comment by ISSOtm** [comment]
```asm
:
  pop af
  dec a
DelayFrames:
  and a
  ret z
  push af
  call DelayFrame
  jr :-
```

**Comment by aaaaaa123456789** [comment]
That would only work with no intervening anonymous labels, although I guess it would solve the simple cases.
~(unless you allow specifying a number to jump back more than one anonymous label at once)~

**Comment by ISSOtm** [comment]
Correct, for feature parity with [ca65](https://cc65.github.io/doc/ca65.html#ss6.6).

**Comment by ISSOtm** [comment]
Considering this obsoleted by #497. If a new use case appears, this will be reopened.

**Comment by aaaaaa123456789** [comment]
Will anonymous labels work beyond a non-local label's scope?
In other words, will this work? If so, this is pretty much done indeed.

```
:
  ld [de], a
  inc de
CopyString:
  ld a, [hli]
  and a
  jr nz, :-
  ret
```

**Comment by ISSOtm** [comment]
Anonymous labels do not interact with the label scope.
