### ISSUE TITLE
[Feature request] Inline comments

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#537]
Particularly in longer lines (such as those containing complex macros), it's often useful to add a comment in the middle of a line, like `/*  ... */` in C. This is not currently supported.

I'd personally recommend braces (`{comment goes here}`), since they are currently unused in the language and there doesn't seem to be any use for them.

**Comment by AntonioND** [comment]
I think something like ``;;`` or any derivative from ``;`` is a better idea. It would be weird to have something completely different, in my opinion.

**Comment by aaaaaa123456789** [comment]
The issue with semicolons is that they show up in sentences.

**Comment by AntonioND** [comment]
Yeah, true. We could just use C comments. Other assemblers accept them as well.

**Comment by NieDzejkob** [comment]
Braces are already used in the language:
```
num EQU 3
PRINTT {num}
```

**Comment by Rangi42** [comment]
Adding `/* */` and removing the deprecated first-column `*` would make sense.

**Comment by ISSOtm** [comment]
C-like comments seem OK to me. That said, this is yet another issue to add to #485's casualty list.
