### ISSUE TITLE
[Feature request] Allow underscores in numeric literals

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#539]
These are useful for long numbers to separate meaningful digit groups, like the typical thousands separator.

It's a feature of languages including C++, Java, Python, Ruby, and Typescript.

One particular use case would be for bytes representing DMG colors: `ld a, %00011011` versus `ld a, %00_01_10_11`.

**Comment by ISSOtm** [comment]
This would indeed be useful, but it causes a problem in that [`\@`'s output](https://github.com/rednex/rgbds/blob/79f293c3d70f58a7810ed36d6ef28353595011f2/src/asm/macro.c#L114) becomes a valid numeric, so its format should be changed. I hope that wouldn't break anyone's workflow.

**Comment by Rangi42** [comment]
If the very first character is an underscore, it would still be a label, not a number.

**Comment by ISSOtm** [comment]
Not if used after a number!

**Comment by aaaaaa123456789** [comment]
I don't think `46\@` would have ever produced anything that would be valid for RGBASM, so that's not a very relevant case.

**Comment by ISSOtm** [comment]
I think the point is for it not to generate unique numbers. Also, not *that* unique, and it shouldn't be relied on to be an incrementing counter.
