### ISSUE TITLE
__FILE__ breaks if filename contains a quote

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#546]
That's about it. The quote(s) need(s) to be escaped.

**Comment by JL2210** [comment]
Fixed by #566

**Comment by ISSOtm** [comment]
I added a regression test that'll ensure that the new lexer will have to implement it.

**Comment by AntonioND** [comment]
That's great, and that's why we need more tests. With enough coverage it becomes far less scary to make big changes...

**Comment by ISSOtm** [comment]
There is however one unintended consequence of adding this test: [Windows is not feeling too great about it](https://github.com/gbdev/rgbds/runs/1138887906?check_suite_focus=true#step:2:354) due to... the quote. I'm not sure how to solve this...

**Comment by AntonioND** [comment]
I think that we shouldn't have that test, probably. I mean, we should have the test, but the file could be generated by the test scripts, and it could be skipped on Windows. Having weird file names is a bad idea.

**Comment by ISSOtm** [comment]
Well, I tried generating the test from within the test script, and [it somehow still gets generated](https://github.com/ISSOtm/rgbds/runs/1146657358?check_suite_focus=true#step:6:11). How? Beats me. Guess it should only be generated when not on Windows, but how is that detectable reliably? I tried [`uname`](https://github.com/ISSOtm/rgbds/runs/1146665817?check_suite_focus=true#step:5:12), but it returns "MinGW", which is probably not suitable...

**Comment by AntonioND** [comment]
Oh, of course, you need to skip the test on Windows. I think that using uname and checking for MinGW is fine, actually. We can always add other strings if needed in the future.

**Comment by ISSOtm** [comment]
Fixed it in 9742fa7, then.
