### ISSUE TITLE
@ is output in map files

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#549]
RGBLINK gets to see `@` somehow... this, in itself, is a bug.

**Comment by NieDzejkob** [comment]
I'm not sure about that, RGBLINK does have some special handling for `@`: https://github.com/rednex/rgbds/blob/cb4fbdfcd534e43a5f8504b405acd7b8b29f5001/src/link/patch.c#L355

**Comment by ISSOtm** [comment]
I meant that the symbol is defined, not that it's used in expressions. It's due to that very handling that no RGBASM object files should contain a definition of `@`.

**Comment by ISSOtm** [comment]
This was fixed by #557, probably bt 5a65188ca94f2ebaa6ffabac4e7d04cb166de4d6
