### ISSUE TITLE
[Feature request] WHILE loops

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#560]
This:

```
x = 0
WHILE x < 10
    db x
x = x + 1
ENDW  ; or reuse ENDC if that's easier
```

would have equivalent output to this:

```
x = 0
REPT 10
    db x
x = x + 1
ENDR
```

The `WHILE` condition could involve string operations or other complex expressions that a `REPT` or macro tricks cannot.

It would be the user's responsibility to not create infinite loops; or have a maximum loop iteration value, past which it halts with an error message.

**Comment by JL2210** [comment]
damn, you're fast :)

**Comment by ISSOtm** [comment]
Good ole #485 locks this again...

**Comment by ISSOtm** [comment]
I think the inclusion of #687 obsoletes this. Arguably, it doesn't, since a `REPT`'s number of iterations is bounded; however, note that RGBASM tries its best to ensure termination somehow, by bounding the recursion depth—which is currently the "shim" for `while` loops.

Thus, I believe that `REPT -1` with an inner `BREAK` could be considered a suitable alternative to these loops.

**Comment by aaaaaa123456789** [comment]
You're not supposed to trigger safeguards.

What this means is that a safeguard doesn't invalidate the feature. If a loop is supposed to run 4,294,967,295 times at most, then `while` is just syntax sugar for `rept -1`, and there is no problem. But if a loop is supposed to exceed that, then the safeguard is the problem, and neither `rept -1` nor a safeguarded `while` would be adequate.

Of course, it would be possible to overcome this limitation by using nested `rept` blocks in ways they're really not designed to be used. But this would simply be working around the lack of a feature, which would in turn _encourage_ writing code that could be broken by a later release.

**Comment by ISSOtm** [comment]
I'm not sure there is a reasonable use case for a loop *within RGBASM* that would loop more than that amount.

**Comment by ISSOtm** [comment]
Closing for now, but feel free to keep discussing, and it may get reopened if a reason to is brought up.

**Comment by Rangi42** [comment]
[Sjasm](http://www.xl2s.tk/sjasmman10.html#s1) also has `while` loops as well as a `continue` statement.
