### ISSUE TITLE
Adding too many charmap nodes crashes RGBASM

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#564]
```
n = 0
rept $4000
    charmap "{X:n}", $0
n = n + 1
endr
```

This was obviously added by 0778959e986928a08d55729626e200fcbefa2569, and the proper fix is to grow the array as needed. @daid also pointed out that creating a new `charmap` is ~4 KiB, which this could help alleviate.

**Comment by daid** [comment]
~8MiB, not ~4KiB.

**Comment by ISSOtm** [comment]
Fixed by 4cfed3c98f014445d07ccdf7b91dc1c1f2ba0eaf.
