### ISSUE TITLE
Incorrect documentation of symbol and section types

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#565]
[Current documentation](https://github.com/rednex/rgbds/blob/d2285953d715d3feec9595abcc82687d4173a7e0/src/rgbds.5#L51-L52) misplaces the section unionization bit in the *symbol*'s type field. (It also means that [this `&`](https://github.com/rednex/rgbds/blob/d2285953d715d3feec9595abcc82687d4173a7e0/src/rgbds.5#L54) is misplaced as well.

Additionally, bit 6 (for section fragments) is not mentioned either.

**Comment by Tawishi** [comment]
I would like to work on this issue.

**Comment by ISSOtm** [comment]
No problem! The file to edit is the same one I linked to in the top post; since I'm not sure we mention it anywhere, [the syntax used](https://mandoc.bsd.lv/man/mdoc.7.html) is [`mandoc`](https://mandoc.bsd.lv/)'s.

**Comment by ISSOtm** [comment]
Welp, looks like that has actually already been fixed in ec5a1bc71f66d133dff23784ff97ca627bcd68b6 :T
