### ISSUE TITLE
Allow 'dw' to apply to characters of strings

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#568]
This is orthogonal to widechar support (#97); it's potentially useful even if charmaps remain 8-bit.

`db "ABC", -1, "{dee}EF"` with `charmap "{dee}", $42` outputs 7 bytes, since each character post-charmap lookup gets handled by `db`.

`dw "ABC", -1, "{dee}EF"` could output 14 bytes, just as if it had been written `dw "A", "B", "C", -1, "{dee}", "E", "F"`.

This can't be done with a macro, because even if the new lexer resolves the current issues around quotes and commas (consider `mydwstring "AB, C{dee}", "EF, GH"`), macro arguments would still see the individual characters `{` `d` `e` `e` `}`.

Currently:
- `dw "...PQ"` acts like `db "Q", "P"`
- `dw "X"` works as expected
- `dw ""` acts like `dw 0`, although `db ""` just outputs no bytes

**Comment by aaaaaa123456789** [comment]
> Currently:
> 
> * `dw "...PQ"` acts like `db "Q", "P"`
> * `dw "X"` works as expected
> * `dw ""` acts like `dw 0`, although `db ""` just outputs no bytes

In summary, `dw expr` acts like `dw (expr)`. (You'd see similar results from `db` using a parenthesized expression, I assume.)
