### ISSUE TITLE
[Feature request] Pretty-printing format specifiers

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#570]
As of right now, symbol interpolation allows one to do `"{d:FOO}"` to get the value of `FOO` in a string. This is probably useful mostly for printing messages to debug output.
However, when inserting messages in an actual in-game screen, the number of characters might be very relevant. There's no way to readily zero-pad or space-pad the value, or control in any way the number of digits that are printed. If you want to print a number to three digits' precision, you have no recourse but to write this ugly block:

```
if FOO < 100
  db "0"
endc
if FOO < 10
  db "0"
endc
db "{d:FOO}"
```

It would thus be nice to have a set of flags to control this behavior. I'd suggest a `printf`-inspired syntax, in the form `{<sign><pad><align><width><base>:<symbol>}`, where:

* `<sign>` is `+`, ` ` or omitted, indicating that positive numbers are respectively prefixed by a `+` sign, a space or nothing (negative numbers are always prefixed by a `-` sign);
* `<align>` is `-` or omitted, indicating that the number is left-aligned or right-aligned respectively;
* `<pad>` is `0` or omitted, indicating that the number is padded to length using zeros or spaces respectively;
* `<width>` is an integer that doesn't start with a 0 or omitted (defaults to 1), indicating the minimum length that the number should be padded to; and
* `<base>` is one of the current base characters, `d`, `x`, `X` and `b` (you might want to introduce `o` for octal and perhaps `u` for unsigned numbers)

Note that this is a strict subset of `printf` format specifiers, and in fact could be easily implemented by calling `sprintf` once the format string has been validated. (Note that the actual `printf` specification allows the `<sign>`, `<align>` and `<pad>` fields to appear in any order. This is not really necessary, but it could be allowed if it doesn't introduce any complexity to the implementation.)

While there's not much need for examples here (`printf` is extremely well known), for the sake of clarity I'll say that if `FOO` equals 46, `"{+05d:FOO}"` would become `"+0046"` and `"{-4x:FOO}"` would become `"2e  "` (with two spaces, except GitHub seems to be deleting them...).

* * *

Someone might suggest that the above pad example can be solved by a macro. This is, indeed, true:

```
padded_number: MACRO
  ; \1: value, \2: pad to, \3: padding character
___next_limit = 1
  rept (\2) - 1
___next_limit = ___next_limit * 10
    if (\1) < ___next_limit
      db (\3)
    endc
  endr
  db "{d:\1}"
ENDM
```

However, this only solves the very particular problem of using a string in a `db`. The proposed solution is much more general.

**Comment by Rangi42** [comment]
Using strings in a `db` is not particularly sensitive to zero-padding or base, since only the final value matters; whereas I *have* wanted at least a subset of this feature for generating label names.

```
n = 1
REPT NUM_TMS
IF n < 10
MOVE_FOR_TM EQUS "TM0{d:n}_MOVE"
ELSE
MOVE_FOR_TM EQUS "TM{d:n}_MOVE"
ENDC
	db MOVE_FOR_TM
PURGE MOVE_FOR_TM
n = n + 1
ENDR
```

This would be cleaner as:

```
n = 1
REPT NUM_TMS
MOVE_FOR_TM EQUS "TM{02d:n}_MOVE"
	db MOVE_FOR_TM
PURGE MOVE_FOR_TM
n = n + 1
ENDR
```

(And #269 would avoid even the need for a temporary `MOVE_FOR_TM` symbol.)
