### ISSUE TITLE
Alignment / address specification of section fragments may work unexpectedly

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#571]
In their current form, [the attributes need to be identical for all fragments](https://github.com/gbdev/rgbds/blob/66784b7122217c0f133a2e7e49cffbe88a374b0f/src/asm/section.c#L251), and they're only applied globally to the section. This is actually not useful; it would be better to instead have an implicit `ALIGN` there with the corresponding parameters, as in [the mid-section keyword](https://github.com/gbdev/rgbds/blob/66784b7122217c0f133a2e7e49cffbe88a374b0f/src/asm/section.c#L379). Also edit [RGBLINK's merging algorithm](https://github.com/gbdev/rgbds/blob/66784b7122217c0f133a2e7e49cffbe88a374b0f/src/link/section.c#L118) accordingly.

The requirement for all-identical attributes made sense when the order of fragments was intended to be undefined, but that has changed since then, so aligning the behavior to what unionized sections do would be better.

Likewise, a fixed address can also be checked for (subtract the current offset from it, check if it conflicts with the current org, and use that if not).

---

@AntonioND I think this should be beginner-friendly, what do you think?

**Comment by AntonioND** [comment]
> @AntonioND I think this should be beginner-friendly, what do you think?

Hmmm not so sure. This has the potential of involving a lot of code because to make it work generically you need to allow the linker to resize sections, and that will make the placement of sections an iterative process.

For sections with fixed base address it should be really easy, though.

**Comment by ISSOtm** [comment]
Section fragments are all concatenated before any assignment takes place; alignment is known at all points in the section from previous alignment points; if the new alignment mask is larger than the current one, then any bits not covered by the original one can be considered as undefined, and treated as we please.
