### ISSUE TITLE
Use CMake in CI as well

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#574]
[I tried adding CMake to the CI matrix as well](https://github.com/ISSOtm/rgbds/runs/1139272783?check_suite_focus=true#step:8:67), but it fails on macOS. It seems we have the same problem as [this guy's](https://stackoverflow.com/questions/36523911/osx-homebrew-cmake-libpng-version-mismatch-issue), but no solution is given. I don't know how to fix this, lacking both CMake and macOS experience, sadly.

**Comment by AntonioND** [comment]
In the CMakeLists.txt you could replace ``find_package(PNG 1.2 REQUIRED)`` by ``find_package(PNG 1.6 REQUIRED)``.

Yeah, that increases the version of the dependency, but it will fix the issue.

**Comment by ISSOtm** [comment]
Well, [that didn't work](https://github.com/ISSOtm/rgbds/runs/1153333724#step:5:15). The same problem remains...

**Comment by AntonioND** [comment]
Okay, that's anoying...

**Comment by JL2210** [comment]
This should be possible now without macOS failing.
