### ISSUE TITLE
LOAD sections allow specification of a non-RAM type

### ISSUE THREAD

**Issue by SuperDisk** [gbdev/rgbds#576]
`rgbasm` doesn't complain when assembling this program:

```
SECTION "Hello", ROM0
ld a, 1
LOAD "Wello", ROM0
ld a, 2
ENDL
```

but it produces nonsensical output when linked:

![Screenshot 2020-09-25 103654](https://user-images.githubusercontent.com/1688837/94280142-0e757500-ff1b-11ea-9c6a-c4f007d4a72d.png)

I corresponded with @ISSOtm and he indicated that a `LOAD` section that doesn't use a RAM type should be a parse error.

**Comment by ISSOtm** [comment]
There simply isn't a use case for `LOAD` into ROM sections; the `LOAD`-created section is still placed like usual, but would only contain empty space.

As for the nonsensical output, can you try with latest master instead? This looks awfully like 9d62b4b9bbff03398bfb44a05195e09aa246392b; you should get `3E 01 3E 02` in one section, and probably two bytes of garbage in the other one, which should by default be placed right after.

**Comment by Rangi42** [comment]
With `master` as of 1d9cc01ae1f1c0493f53fb9fb018b7a924455dd7, that test case does now output `3E 01 3E 02` followed by `00 00` and then padding `00`s.
