### ISSUE TITLE
[Feature request] Multi-line string literals

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#589]
Python has `"""triple"""` `'''quotes'''`, bash has `<< HEREDOC`, and ES6 has `` `template literals` ``. Any multi-line string literal syntax would be useful, particularly for metaprogramming.

When a macro defines another macro, the inner macro definition is just skipped over until it reaches an `ENDM` token; this prevents the outer macro from controlling just how the inner one is defined. For that, it needs to use an `EQUS`. For example:

```
make_rep: MACRO
REP EQUS "\n\1: MACRO\nREPT \2\n\tdb \\1\nENDR\nENDM"
  REP
  PURGE REP
ENDM

  make_rep double, 2
  make_rep triple, 3
  double $20  ; db $20, $20
  triple $42  ; db $42, $42, $42
```

Something like this would be more legible:

```
make_rep: MACRO
REP EQUS """
\1: MACRO
REPT \2
	db \\1
ENDR
ENDM"""
  REP
  PURGE REP
ENDM
```

Even if the inner macro has to be built up from some `STRCAT`s, the pieces would benefit from multi-line formatting.

**Comment by Rangi42** [comment]
(I can try implementing this if a particular syntax is decided on. Backticks are already used for graphic literals, but triple quotes would work; and single quotes are not yet used for anything. Maybe `''double''` or `'''triple'''` single quotes?)

**Comment by JL2210** [comment]
maybe backslashes at the ends of lines?

**Comment by JL2210** [comment]
Sounds like a good candidate

**Comment by Rangi42** [comment]
Actually this already works with the new lexer:

```
REP EQUS "\n\
\\1: MACRO\n\
REPT \\2\n\
	db \\\\1\n\
ENDR\n\
ENDM"
```

But it requires escaped backslashes and explicit newlines, so I think multiline would still be worthwhile:

```
REP EQUS '''
\1: MACRO
REPT \2
	db \\1
ENDR
ENDM'''
```

**Comment by aaaaaa123456789** [comment]
Heredocs are generally more readable than triple quotes because (1) you can put the delimiters in their own lines and (2) you can choose the delimiters, so they don't blend into the string (which is rarely what you want). The Bash heredoc syntax also has the bonus feature of allowing disabling substitutions, which would probably be helpful in some contexts.

**Comment by ISSOtm** [comment]
The main problem of a bash-style heredoc is having to lex a user-defined token. Well, a new lexer mode could be made for it, I guess. I'd prefer heredoc anyways, even with a fixed ending token; the feasability of a custom one is to be assessed.

**Comment by Rangi42** [comment]
A fixed ending token would need a way to be escaped inside the string, and the typical backslash escape would look odd on an alphabetical token. Example:

```
    mymacro <<<SDOC
Hello!
\SDOC
Goodbye!
SDOC

; equivalent to

    mymacro "Hello!\nSDOC\nGoodbye!"
```
