### ISSUE TITLE
[Feature request] An escape sequence that expands to all remaining macro arguments

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#596]
This would have the same utility as `__VA_ARGS__` in C or `*args` in Python, allowing the remaining (un`SHIFT`ed) macro arguments to be passed on, possibly to another macro.

Candidates:

- `\0`: Not used for anything else; detected as a valid macro argument up until `expandMacroArg` explicitly fails it
- `\#`: It's a valid identifier character like `\@`; the number sign could be taken to mean "all numbers"
- `\*`: Star means "everything" in wildcards and regexes

Example usage:

```
items: MACRO
    db _NARG
    rept _NARG
        db \1
        shift
    endr
ENDM

; simplifies to :

items: MACRO
    db _NARG, \#
ENDM
````

```
; old way: person_event Y, X, (more than 10 more arguments, not necessarily a constant quantity)
; new way: object_event X, Y, (the rest of the arguments same as before)
; declare this for backwards compatibility
person_event: MACRO
Y = \1
X = \2
    shift 2
    ; no need to copy+paste the logic from object_event for the rest
    object_event X, Y, \#
ENDM
```

**Comment by aaaaaa123456789** [comment]
This is a great idea.

There are two questions to answer:

* How is the case with no elements at all handled? (See: the common `, ## __VA_ARGS__` compiler extension in C.)
* What spacing would be applied around commas?

**Comment by Rangi42** [comment]
1. Let's assume that with no remaining arguments `\#` would become an empty string. Inputting that to `db`/`dw`/`dl`, e.g. `db _NARG, \#`, will warn with `-Wempty-entry` but otherwise works as expected (outputs `db 0`). Inputting it to a macro fails with `syntax error`; this could go hand-in-hand with allowing macros to have trailing commas (but warning about it) just like `db`/`dw`/`dl`.
2. If possible, the original spacing. If not, I don't know whether space-after-comma or no-space would have any particular advantages.

**Comment by Rangi42** [comment]
Regarding point 1, I think even the current `syntax error` would be tolerable. The user of `\#` can always check for the zero case themselves. For instance:

```
items: MACRO
    db _NARG
    if _NARG
        db \#
    endc
ENDM
```

The second example would remain as-is, because the `object_event` macro that `person_event` forwards to is expecting nonzero further arguments, so an empty `\#` is just as bad as typing `object_event 13, 37,` without anything further in the first place.

**Comment by ISSOtm** [comment]
Considering that `_NARG` exists, I see no need for special handling of no arguments, as Rangi pointed out.

Spacing does not matter, since macro args ignore spaces anyways. I'd leave the spacing undefined, as it'd be largely dependent on how `\#` would be internally handled.

**Comment by aaaaaa123456789** [comment]
Spaces do matter because the escape sequence might appear in a string. I don't have any reason to prefer any specific way of handling them, but 'undefined' is less than ideal.

**Comment by ISSOtm** [comment]
`\#` is either going to be passed to a macro, which trims spaces, or printed if used in a string, which would very likely be a debug print anyways.

**Comment by aaaaaa123456789** [comment]
> `\#` is either going to be passed to a macro, which trims spaces, or printed if used in a string, which would very likely be a debug print anyways.

I agree, which is why I don't think it matters much how you handle it exactly, but it should be documented for the odd case we're not thinking of where it does matter.

**Comment by ISSOtm** [comment]
I'd say we document it as undefined, to give us some leeway, and if a good use case emerges that requires either, we'll reconsider and update the documentation. It's easier to make some behavior defined than to re-define one.
