### ISSUE TITLE
rgbasm(5) does not explain what exporting does

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#608]
An example such as the following, or an explanation to that effect, would go a long way.
```
issotm@sheik-kitty /tmp% cat a.asm
SECTION "RAM", WRAM0
RAMLabel:
issotm@sheik-kitty /tmp% cat b.asm
SECTION "Exported RAM", WRAM0
ExportedRAMLabel::
issotm@sheik-kitty /tmp% cat c.asm
SECTION "Imports", ROM0[0]
	dw RAMLabel
	dw ExportedRAMLabel
issotm@sheik-kitty /tmp% rgbasm -o a.o a.asm
issotm@sheik-kitty /tmp% rgbasm -o b.o b.asm
issotm@sheik-kitty /tmp% rgbasm -o c.o c.asm
issotm@sheik-kitty /tmp% rgblink a.o b.o c.o
error: c.asm(2): Unknown symbol "RAMLabel"
Linking failed with 1 error
```

**Comment by Rangi42** [comment]
This is more verbose, but I think would be more helpful for if the current "Exporting and importing symbols" section wasn't clear enough:

> For example, if you have the following three files:
> 
> `a.asm`:
> 
> ```
> SECTION "a", WRAM0
> LabelA:
> ```
> 
> `b.asm`:
> 
> ```
> SECTION "b", WRAM0
> ExportedLabelB1::
> ExportedLabelB2:
> 	EXPORT ExportedLabelB2
> ```
> 
> `c.asm`:
> 
> ```
> SECTION "C", ROM0[0]
> 	dw LabelA
> 	dw ExportedLabelB1
> 	dw ExportedLabelB2
> ```
> 
> Then `c.asm` can use `ExportedLabelB1` and `ExportedLabelB2`, but not `LabelA`, so linking them together will fail:
> 
> ```
> $ rgbasm -o a.o a.asm
> $ rgbasm -o b.o b.asm
> $ rgbasm -o c.o c.asm
> $ rgblink a.o b.o c.o
> error: c.asm(2): Unknown symbol "LabelA"
> Linking failed with 1 error
> ```
