### ISSUE TITLE
Segmentation fault in rgblink

### ISSUE THREAD

**Issue by daid** [gbdev/rgbds#613]
Just got a segmentation fault in rgblink (master), managed to reduce it to the following minimal test:
```SECTION "mainMenuData", ROMX
mainMenuLoadData:
N = 0
REPT 16
    dw   load8TilesToWRAM, mainMenuGraphics + N, $9000 + N
N = N + $80
ENDR

    dw temp

load8TilesToWRAM:
mainMenuGraphics:
```
rgblink seems to recursive forever in `dumpFileStack` because `node->parent == node`. Pretty sure the actual bug is in rgbasm and it's just the result of bad data in the object file.

The trigger is the temp label which isn't defined, and then it wants to dump the file stack. But the REPT before it seems to cause problems/corruption with the filestack.

**Comment by ISSOtm** [comment]
Fixed by b6bf7ae
