### ISSUE TITLE
CI fails with MSVC

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#616]
Happened since #615; the MSVC CI job emits a bunch of warnings, originating from the C library itself (!?), whic @JL2210 could *not* reproduce on his machine. I should look into reproducing this, perhaps GitHub provides VM images for their CI machines?

**Comment by AntonioND** [comment]
The MSVC standard library and the compiler are developed by different people, and I'd guess that sometimes the compiler team introduces new warnings that the library team hasn't had time to fix, or things like that.

I'd say that most likely a MSVC update would fix that, or you could disable the warning on MSVC:

```
if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
   add_compiler_options(/wd5105)
endif()
```

https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5105?view=msvc-160

**Comment by AntonioND** [comment]
Or you could try to get information about the version of the compiler and compare that to the one that @JL2210 has.

But yeah, that PR is very unlikely the reason for the errors.

**Comment by JL2210** [comment]
I would add that I couldn't reproduce on Linux... at the time, I didn't exactly know what I was being asked for. I might be able to go check my MSVC installation sometime today and see if it works there or not.

**Comment by ISSOtm** [comment]
[The pile of garbage is higher than expected...](https://github.com/ISSOtm/rgbds/runs/1524781150#step:6:46)

**Comment by Rangi42** [comment]
A lot, if not all, of the errors are caused by `char buf[static MAXSYMLEN + 1]`: the two failing builds' MSVC versions must not support that from C99.
