### ISSUE TITLE
Weird behaviour with transparent pixels in `rgbgfx`

### ISSUE THREAD

**Issue by matanui159** [gbdev/rgbds#618]
I've been using `rgbgfx` to generate graphics data and palettes from PNGs. In the documentation it says that "Transparent pixels are set to palette index 0." However, I quickly noticed that it does not _uniquely_ set them as palette index 0. If there is a color bright enough it will also be given palette index 0 creating transparent pixels in the sprite. The only solution I've found is to set the background to white instead of transparent but its not a perfect solution.

Can there at least be a flag to change this behaviour such that if there is transparency and 3 other colors, it uses transparency for color index 0 and uses the colors for indices 1-3?

**Comment by ISSOtm** [comment]
Well, fixing this would fall under the scope of the planned RGBGFX rewrite... it's poorly written, and needs a lot of behavior changes. I'm sorry to say that this is a bug you'll have to live with for now... until someone finds enough motivation and time to re-do RGBGFX essentially from scratch. :/
