### ISSUE TITLE
Translate the documentation

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#627]
RGDBS' output is currently entirely in English. This is mostly fine, but it may be interesting to respect the user's locale whenever possible.

This would be split into several steps:
1. Decide what should be localized, and what shouldn't be
2. Provide translations
3. Integrate these somehow

Step 2 is the most **beginner-friendly** part, not necessarily needing any knowledge of the codebase.

As for step 3, what about [`gettext`](https://www.gnu.org/software/gettext/manual/html_node/index.html#Top)?

**Comment by AntonioND** [comment]
As it has been metioned on discord, the biggest problem with translating the tools themselves is that this makes "googling for the error" really hard. I remember having my system in Spanish and getting GCC errors in spanish, and finding it very tricky to find a solution for them. As soon as I switched to English it was much easier.

Manuals and documentation, sure, that's fine. However, that creates problems when the English documentation is updated and the translations stay out of date. You'd need commitment from the original translators to not let this happen.

**Comment by aaaaaa123456789** [comment]
The biggest issue with translations is that they are often very bad, and that's very hard to verify unless you speak the language yourself. For almost all of us who speak English well, and for most people who speak it at least passably (and that tends to include almost everyone into hobby programming), good English is a hundred times better than broken native text.

**Comment by AntonioND** [comment]
Not to mention that sometimes other languages don't have words to express computer terms, so it ends up being half English anyway.

**Comment by pinobatch** [comment]
Now that the scope of this issue has been limited to documentation:

It's been suggested to provide a linter to enforce prefixes for labels by what memory region they're in: `s` for $A000-$BFFF`, `w` for $C000-$DFFF, `h` for $FF80-$FFFE, `r` for other values in $F000-$FFFF. One user even suggested prefixing ROM symbols with the data format (e.g. `pb16` for compressed using PB16). If that lands, I'd suggest that documentation about this sort of Hungarian notation be translated at least into Hungarian.

**Comment by Rangi42** [comment]
Translating the man pages would be impractical, so any internationalization we do should go in https://github.com/gbdev/rgbds-www.
