### ISSUE TITLE
[Feature request] An EVAL function to look up strings as symbols

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#629]
Issues #269 and #556 requested `{symbol}` interpolation outside of `"strings"`, which is explicitly not supported in the new lexer. The current alternative is to use temporary string definitions:

```
MOVE_FOR_TM EQUS "TM{d:n}_MOVE"
	db MOVE_FOR_TM
PURGE MOVE_FOR_TM
```

```
TMP equs "{STRUCT_NAME}_field{d:CUR_FIELD_ID}_name"
CONFLICTING_FIELD_NAME equs TMP
PURGE TMP
```

With an `EVAL` function, these could be written as:

```
	db EVAL("TM{d:n}_MOVE")
```

```
CONFLICTING_FIELD_NAME equs EVAL("{STRUCT_NAME}_field{d:CUR_FIELD_ID}_name")
```

Ideally `EVAL` should also be allowed as an lvalue. So you could replace this:

```
_NUM_WARPS EQUS "_NUM_WARPS_1"
_NUM_WARPS = 5
_WARP_TO_NAME EQUS "_WARP_TO_NUM_{d:{_NUM_WARPS}}"
_WARP_TO_NAME EQUS "warp_to 1, 2, _WARP_TO_WIDTH"
PURGE _WARP_TO_NAME
```

with this:

```
_NUM_WARPS EQUS "_NUM_WARPS_1"
_NUM_WARPS = 5
EVAL("_WARP_TO_NUM_{d:{_NUM_WARPS}}") EQUS "warp_to 1, 2, _WARP_TO_WIDTH"
```

(Usage examples adapted from [pokecrystal](https://github.com/pret/pokecrystal/blob/master/data/moves/tmhm_moves.asm), [rgbds-structs](https://github.com/ISSOtm/rgbds-structs/blob/master/structs.asm), and [pokered](https://github.com/pret/pokered/blob/master/macros/scripts/maps.asm).)

**Comment by Rangi42** [comment]
One way this would *not* be equivalent to previous proposals: it would not be valid anywhere in the grammar, only in places where a literal string or number is accepted. (As well as before an `EQU`/`EQUS`, with the bonus lvalue suggestion.) So:

```
; valid
tiles EQUS "* 16"
    ld a, 4 tiles

; previously valid with the old lexer
tiles EQUS "* 16"
    ld a, 4 {tiles}

; not valid
tiles EQUS "* 16"
    ld a, 4 EVAL("tiles")
```

**Comment by ISSOtm** [comment]
Arguably, the point is to make it return a symbol name, so it could be added to a new `symbol` production instead.
