### ISSUE TITLE
Overlays via LOAD UNION

### ISSUE THREAD

**Issue by pinobatch** [gbdev/rgbds#632]
Say I have one part of the program, such as one game mode, that loads one self-modifying subroutine into RAM, and another part of the program that loads a different self-modifying subroutine into RAM. Because each part of the program uses only its own routine, I don't want to have both in the 8192-byte RAM at all times.

Thus I want to set up [overlays]. Each part of the program copies its own subroutine into RAM when it starts, and enough RAM is allocated under a section name to hold the largest of them. Looking through the RGBASM manual, I find these keywords:

- `SECTION`: An area of ROM or RAM
- `SECTION UNION`: An area of RAM that overlaps other `SECTION`s with the same name
- `LOAD`: An area of RAM to which data in a `SECTION` is copied
- ???: An area of RAM to which data in a `SECTION` is copied that overlaps other `LOAD`s with the same name
- `LOAD UNION`: Logical name for this sort of area, but a syntax error as demonstrated in [loadunion.asm.zip](https://github.com/gbdev/rgbds/files/5676828/loadunion.asm.zip)

What keyword should I be using?

[overlays]: https://en.wikipedia.org/wiki/Overlay_(programming)

**Comment by ISSOtm** [comment]
I didn't implement `LOAD UNION` because `LOAD` was fucky enough on its own (and I still need to check e.g. the semantics of `ALIGN`), but these could be implemented.
