### ISSUE TITLE
Make RGBASM behavior locale-independent

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#638]
RGBASM currently relies on some locale-dependent behavior, such as `toupper` and `tolower`.

Do we want to force the C locale globally for the whole programs, or use the `_l` functions?

**Comment by aaaaaa123456789** [comment]
All programs start on the C locale. In other words, you're already using the C locale unless you explicitly call `setlocale`.

**Comment by ISSOtm** [comment]
Doesn't it depend on environment variables?

**Comment by aaaaaa123456789** [comment]
Not at all. That's a completely explicit opt-in behavior that most POSIX programs have.

**Comment by ISSOtm** [comment]
My bad, then. Given the discussion in #627, we don't want locale-dependent behavior in e.g. output messages, either, correct?
