### ISSUE TITLE
[Feature request] String-escape macro argument characters within a string literal

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#643]
Historically `{string interpolation}` has escaped characters during expansion, since it was only intended for within string literals anyway:

```
name equs "John \"Danger\" Smith"
greeting equs "Hello, {name}!"
; now 'greeting' is "Hello, John \"Danger\" Smith!"
```

Now `{interpolation}` is allowed outside of strings, but within string literals it keeps the old implementation, to avoid this misbehavior:

```
; (not how rgbasm actually behaves)
name equs "John \"Danger\" Smith"
greeting equs "Hello, {name}!"
; syntax error since it would get parsed as:
; greeting equs "Hello, John "Danger" Smith!"
```

Currently macro arguments still have that sort of (arguably a) misbehavior:

```
greet: macro
greeting equs "Hello, \1!"
endm
    greet John "Danger" Smith
    ; syntax error
```

I think it would be more useful to special-case this like interpolation: inside `readString`, disable macro args as well as interpolation, and let `readString` call `expandMacroArg` itself and just append the expanded arg to `yylval.tzString`.

One use case would be for debugging: `printt "arg 1 = \1\n"` would show the argument value before being processed (e.g. `2+2` instead of `4`).

It would also have avoided the need for this fix in pokecrystal: https://github.com/pret/pokecrystal/commit/e0b783bb7b9b73ff48b079a50156e0efdbf08be3
That was only because `STRSUB("\2", 1, 1)` was a syntax error when `\2` was a string (it could be a constant, including a single-character string, or a label).

**Comment by ISSOtm** [comment]
I don't like special-casing macro arg expansion, but since brace expansion already is, I'm okay with backpedaling for the sake of compatibility.
