### ISSUE TITLE
Allow longer strings

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#650]
Right now `MAXSTRLEN` is 255. I think that a larger limit, like 1024 or even 4096, would be helpful.

- `PRINTV`/`PRINTI`/`PRINTF` emitting trailing newlines (#624) mean that `PRINTT` with `STRFMT` (#646) (or just `{formatted:interpolation}`) will be the obvious choice for complex printing. These strings could get pretty long, especially if formatted values use wide padding.
- Now that macros can't be nested, the "official" solution to define one macro within another is by putting the whole inner `MACRO ... ENDM` definition in an `EQUS`. These are likely to be multi-line strings, so even if 255 is a reasonable length limit per line, the whole macro could be longer than that.

**Comment by ISSOtm** [comment]
What we really need is to remove that hardcoded limit. Raising the limit would cause lvalues to become stupidly large; note also that strings get `strcpy`d *every time* they change parser contexts. This is utterly stupid, and perhaps a source of performance loss.
Compared to `malloc`? I dunno. I believe there are known solutions to that, though...

**Comment by Rangi42** [comment]
With longer strings, test/asm/quine.asm could be reduced further:

```
N:MACRO
FOR R,_NARG
SHIFT R
PRINT STRSUB("\n\"\\ FIRSTN,1ABCDEGHLMnOPU_:(+-)#",\1+1,1)
SHIFT-R
ENDR
PRINTLN"\#"
ENDM
 N 9,26,20,12,14,6,22,0,4,22,6,3,6,10,25,9,12,6,17,0,7,18,5,4,8,3,6,0,23,6,5,9,8,3,7,8,6,7,24,13,27,1,2,21,2,1,2,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,1,10,2,11,28,11,10,11,30,0,7,18,5,4,8,29,6,0,16,9,15,6,0,23,6,5,9,8,19,9,1,2,31,1,0,16,9,15,20,0,3,9,3
```

**Comment by ISSOtm** [comment]
By the way, according to some `perf` profiling, copying lvalues *is* currently the largest bottleneck in RGBASM by far. A WIP implementation of heap-stored strings can be found [in my fork](https://github.com/ISSOtm/rgbds/tree/strings).
