### ISSUE TITLE
dbgPrint output always reports col=0

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#656]
The line=N tracking is correct, but not the column value.

**Comment by ISSOtm** [comment]
Does it? It used to be right, though, so it must have been broken somehow?

**Comment by Rangi42** [comment]
`shiftChars` does not update `colNo` if `isMmapped` is true. Also `lexer_OpenFileView` sets `isMmapped` to true ("It's not *really* `mmap()`ed, but it behaves the same").

**Comment by Rangi42** [comment]
@ISSOtm I'm not sure what the appropriate fix is here. Should `shiftChar` always update `colNo`, even for actually `mmap()`ed files as opposed to lexer expansions?

**Comment by ISSOtm** [comment]
Yes, `mmap()`ed files should get correct column tracking, just not lexer expansions.

**Comment by Rangi42** [comment]
It looks like `colNo` is meant to report the literal column number that a text editor would report, not the column number in a single conceptual line. For example:

```
printt \
 "Hello!\n"
```

The string `"Hello!"` starts at line 2 col 1 and ends at line 2 col 11. (This agrees with how it's already reported to be on line 2, not line 1.)

**Note:** Should this also make column numbers 1-based instead of 0-based, to match with line numbers starting at 1?

**Comment by ISSOtm** [comment]
IIRC `lineNo` also starts at 0 and is pre-incremented; the intent is for error reporting to match what an editor would display, as that's the primary use.

**Comment by Rangi42** [comment]
If that's the intent, then this is fine: I think more editors start at column 1 than column 0 (emacs being the exception), and `colNo` unlike `lineNo` is not incremented that way, so it starts at its real value.
