### ISSUE TITLE
[Feature request] BYTE and WORD functions that warn about signed overflow

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#657]
Currently `-x` and `~x` do 32-bit negation, so instructions like `ld a, ~%11110000` or `ld hl, -$cd20` give a `-Wtruncation` warning. This can be avoided with manual masking, like `ld a, LOW(~%11110000)` or `ld hl, (-$cd20) & $ffff`, but that's a blunt approach which will hide even valid truncation warnings, like for `ld a, LOW(-300)`.

My draft suggestion is `BYTE` and `WORD` functions that act like `LOW`, masking o the low 8 or 16 bits respectively, but warn if their argument would have any set bits masked out, *if* the argument is not within the valid signed or unsigned range. So `BYTE(300)` and `BYTE(-300)` would both print a warning, but `BYTE(-120)` and `BYTE(255)` would not. (Neither would `BYTE($ffffff88)`, but such high 32-bit values are unlikely to be seen at all, versus seeing them as two's-complement negated lower values.)

**Comment by Rangi42** [comment]
Note that this would (a) supersede #561, and (b) justify implementing it not as a user-defined function, since `BYTE` and `WORD` would have internal `-Wtruncation` awareness.

**Comment by Rangi42** [comment]
Alternatively, change all `-Wtruncation` warnings to only apply when the value would be truncated no matter whether it's signed or unsigned. So `ld a, 256` and `ld a, -129` would warn, but `ld a, 255` (a valid unsigned byte) `ld a, -128` (a valid signed byte) would not. This would no longer warn for values like `ld a, $ffffff80`, but again, those are unlikely to be seen as actual positive 32-bit values.

**Comment by aaaaaa123456789** [comment]
> Alternatively, change all `-Wtruncation` warnings to only apply when the value would be truncated no matter whether it's signed or unsigned. So `ld a, 256` and `ld a, -129` would warn, but `ld a, 255` (a valid unsigned byte) `ld a, -128` (a valid signed byte) would not. This would no longer warn for values like `ld a, $ffffff80`, but again, those are unlikely to be seen as actual positive 32-bit values.

This is already the case. The issue is that this warns for things like `ld a, ~$80`, since `~$80` results in `$ffffff7f`.

**Comment by ISSOtm** [comment]
Considering that this is already the default behavior, and I'm not hot for adding yet more functionality to RGBASM, I don't think this is a good idea.
Besides, it's just a warning, you can easily ignore it.

**Comment by Rangi42** [comment]
> I'm not hot for adding yet more functionality to RGBASM

Alright, never mind `BYTE` and `WORD`. What about special-casing values in the range `$FFFFFF00`–`$FFFFFF7F` (negative or negated 128–255) to be allowed as 8-bit values, and likewise for `$FFFF0000`–`$FFFF7FFF` as 16-bit (negative or negated `$8000`−`$FFFF`)?

**Comment by Rangi42** [comment]
This was discussed and rejected in #279.
