### ISSUE TITLE
[Feature request] Operators and fixed-point functions related to exponents and logarithms

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#659]
- [x] `POW(b, p)` for fixed-point exponents and roots (`POW(x, 0.5)` == `sqrt(x)`)
- [x] `LOG(n, b)` for fixed-point logarithms
- ~~`CEIL(n)` and `FLOOR(n)` (useful in combination with logarithms)~~
- [x] `**` for integer exponents ([as used by](https://en.wikipedia.org/wiki/Exponentiation#In_programming_languages) Bash, Python, Ruby, Perl, Javascript, PHP, and others) (`<<` only covers raising 2 to a power)
- If integer roots are really needed, they can be calculated by going to+from fixed-point, or eventually with user-defined functions for particular Nth roots

**Comment by Rangi42** [comment]
Suggesting these since (except for `**`) they're not practical to add even with user-defined functions given the available built-in operations.

**Comment by aaaaaa123456789** [comment]
> Suggesting these since (except for `**`) they're not practical to add even with user-defined functions given the available built-in operations.

`FLOOR(n)` is trivial (`n & $ffff0000`); `CEIL(n)` wouldn't be much harder. The other two functions are definitely hard to add using built-in operations.

**Comment by Rangi42** [comment]
True. Never mind them then, I'd just mentioned them as an afterthought to make `LOG` more useful for integer roles like with pokecrystal's `maskbits`.

```
def floor(n) := n & $ffff_0000
def ceil(n) := floor(n) + (n & $ffff ? n < 0.0 : -1.0 : 1.0 : 0.0)
```

**Comment by aaaaaa123456789** [comment]
> True. Never mind them then, I'd just mentioned them as an afterthought to make `LOG` more useful for integer roles like with pokecrystal's `maskbits`.
> 
> ```
> def floor(n) := n & $ffff_0000
> def ceil(n) := floor(n) + (n & $ffff ? n < 0.0 : -1.0 : 1.0 : 0.0)
> ```

`def ceil(n) := floor(n - 1) + 1.0`
Make your life easier!

**Comment by Rangi42** [comment]
Not quite: `ceil(-4.2)` should be `-4.0`, not `-5.0`. ...which actually means the definition of `floor` needs editing, since `floor(-4.2)` *should* be `-5.0`. `n & $ffff_0000` acts like `trunc()`.

**Comment by aaaaaa123456789** [comment]
> Not quite: `ceil(-4.2)` should be `-4.0`, not `-5.0`. ...which actually means the definition of `floor` needs editing, since `floor(-4.2)` _should_ be `-5.0`. `n & $ffff_0000` acts like `trunc()`.

`-4.2` becomes `$fffbcccd`, and `$fffbcccd & $ffff0000` is `$fffb0000` — i.e., `-5.0`.
