### ISSUE TITLE
[Feature request] STRREP function for replacing substrings

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#660]
Currently [rgbds-structs](https://github.com/ISSOtm/rgbds-structs/blob/master/structs.asm) defines a `strreplace` macro for this. It has limitations: it can only replace one character with one character; it has to replace within an `EQUS`, not any string expression; and it is slow (probably not a big deal since string replacing shouldn't be the bottleneck in anyone's asm program, but still).

A `STRREP(str, a, b)` would replace each occurrence of substring `a` with `b`, scanning from the left. So:

- `STRREP("1.2.3", ".", ",")` → `"1,2,3"`
- `STRREP("lolol", "lol", "heh")` → `"hehol"` (the second "`lol`" was overwritten by the first replacement)
- `STRREP("{code}", "[hli]", "[hl+]")` → `code` replacing `"[hli]"` with `"[hl+]"`
- `STRREP(" s  p ac  e d  ", " ", "")` → `"spaced"`

Potentially this could also support a *max* parameter to limit how many replacements it does. So `STRREP("name|1|2|3", "|", ":: ", 1)` → `"name:: 1|2|3"`.

**Comment by aaaaaa123456789** [comment]
I'm not entirely sure of what the point of a max parameter would be. What is it meant to be used for?

**Comment by Rangi42** [comment]
- If your string looks like "`A = <content>`", and `<content>` may have literal "`=`"s in it, then you'd want to replace only the first "`=`" with "`EQU`"
- If your string looks like "`fname,lname,country,address`", and `address` may have literal "`,`"s in it, then you'd want to replace only the first three "`,`"s with "`\t`"
- It's simple enough to add if the basic `STRREP` exists, and I recall using it often enough, that it's probably worth adding the parameter

**Comment by ISSOtm** [comment]
I'd implement 3-arg `REPLACE` (`STRREP` could be "REPeat", especially given `REPT`) first, and add the 4th optional arg later, if there was a strong need for it. (Replacing the *last* N ones sounds equally as useful, for example. Yes, negative amounts could take care of it, but again, not too sure how often it'd be useful.)
