### ISSUE TITLE
New RGBDS syntax error

### ISSUE THREAD

**Issue by Reminiscon** [gbdev/rgbds#666]
else    xor a

^ On the same line, this is now being identified as a syntax error.

**Comment by aaaaaa123456789** [comment]
Always has been, though? This is not valid; the documentation has always clearly required one directive per line, like any other assembler.

**Comment by ISSOtm** [comment]
This is not supposed to be valid syntax, but the old lexer (yes, not the parser) allowed it. This isn't a bug, and doesn't seem problematic enough that it'd warrant being introduced back?

**Comment by aaaaaa123456789** [comment]
I'd say that if it used to be allowed, disallowing it is a bug fix. No good reason to reintroduce something this broken.

**Comment by ISSOtm** [comment]
I am not against reintroducing "broken" behavior if it has a use case that can't easily be worked around.

**Comment by aaaaaa123456789** [comment]
Isn't the workaround hitting the Enter key?

**Comment by Rangi42** [comment]
I would not expect code on the same line as `else` to ever have worked; the old lexer was over-permissive.

**Comment by ISSOtm** [comment]
Closing for now, will reopen if @Reminiscon has an objection.
