### ISSUE TITLE
Deprecate _PI

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#670]
The fixed-point trigonometry functions do not use radians; they use 65536ths. The fixed-point value 3.14159, or $3243F, is insignificant, and its existence may confuse people about the domain and range of the trig functions.

- sin(0) = 0, and `SIN(0.0) == SIN(0) == 0.0 == 0`
- sin(π/2) = sin(τ/4) = 1, and `SIN(16384.0) == SIN($4000_0000) == 1.0 == $1_0000`
- sin(π) = sin(τ/2) = 0, and `SIN(32768.0) == SIN($8000_0000) == 0.0 == 0`
- sin(−π/2) = sin(−τ/4) = −1, and `SIN(-16384.0) == SIN($C0000_0000) == -1.0 == $FFFF_0000`
- sin(2π) = sin(τ) = 1; `65536.0 == $1_0000_0000` is above the maximum fixed-point value, but it overflows to `0.0` and is correct
- `SIN(_PI) == 0.00029 == $13`, which clashes with the documentation saying `_PI` is "Fixed point π"

~~If any value is to be defined, I'd suggest one in fixed-point units: `_FIXED_PI == 32768.0` (or change the value of `_PI`, which would be backwards-incompatible but I'd be surprised if anyone actually uses `_PI`).~~

**Comment by aaaaaa123456789** [comment]
Defining `_FIXED_PI` as $80000000 would probably constitute the single worst and most confusing name in the entire toolchain. I know your country has a history of [attempting to redefine pi](https://en.wikipedia.org/wiki/Indiana_Pi_Bill), but that doesn't mean it's a good time to try again! Jokes aside, pi is a mathematical constant, not just the arccosine of -1.
The trigonometric functions are unusual in that they are essentially composite functions, but that's something that should be documented. (And perhaps the actual trigonometric functions could be introduced eventually, although user-defined functions would make that a non-issue.)

(The documentation for the trigonometric functions could be greatly improved. The functions basically take a 0.32 fixed point argument that is multiplied by 2pi. That could be interpreted as a scaled-down fixed point number, as the documentation says, but it's also useful as an integer argument scaled down by 32 positions. But this is a completely separate topic.)

**Comment by Rangi42** [comment]
More explicit documentation would also be fine. Though I would still support deprecating/removing `_PI`, because it's as useless for Game Boy assembler as `_E` or `_PHI` or other such fixed-point values.

**Comment by aaaaaa123456789** [comment]
What harm have those poor, innocent transcendental numbers done to you?
If someone wants to add constants like e, √2 or ln 10/ln 2, I don't see any harm...

**Comment by Rangi42** [comment]
It's trivial to define `PI EQU 3.14159` if you need it; it's just misleading as a built-in value. Arguably we're stuck with it since it exists already, but the docs should be clear that it has no significance to the trig functions.

**Comment by aaaaaa123456789** [comment]
I'll admit I don't have years of teachers drilling trigonometric function evaluation charts into my head, and thus I see pi as 3.14159... and not as something that only appears when measuring angles. But it might be worth checking if anyone is using `_PI` for anything at all.

**Comment by ISSOtm** [comment]
Then it'd be safe to deprecate it, and see if anyone storms into here yelling. Oh, and to make it clear: no, this is not done in order to introduce `_TAU`.

**Comment by aaaaaa123456789** [comment]
> Oh, and to make it clear: no, this is not done in order to introduce `_TAU`.

I'd then assume it's done in order to introduce `_LAMBDA`, equal to half pi.
