### ISSUE TITLE
[Feature request] A way to explicitly re-assign an EQU or EQUS constant

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#677]
Unlike `SET` constants, `EQU` and `EQUS` ones can't be reassigned, which is convenient to prevent changing one by accident that you didn't know already existed. However, it means that intentionally reassigning one has to do it step-by-step with `PURGE`:

```
TMP EQUS "{FOO}, more"
    PURGE FOO
FOO EQUS "{TMP}"
    PURGE TMP
```

I'd appreciate a keyword to intentionally reassign a name. Like:

```
FOO RE_EQUS "{FOO}, more"

FOO UPDATE EQUS "{FOO}, more"

FOO EQUS FORCE "{FOO}, more"
```

(Haven't thought of a good keyword for it though.)

**Comment by ISSOtm** [comment]
The keyword must prefix the operation, otherwise `EQUS` expansion can't be prevented, which is the entire reason why `EQUS` can't be reassigned.

`EQU` shan't ever be re-assigned (if you need that, use `SET`), but I agree with new functionality `EQUS`. `REDEF`?

**Comment by Rangi42** [comment]
If it doesn't need to work with both `EQU` and `EQUS`, then it may as well be an alternative to `EQUS`, not a modifier for it.

"`REDEF`" would look related to the upcoming "`DEF`" for user-defined functions.

Maybe "`REQUS`"? ("r**e-e**qual**s-s**tring" vs "equal**s-s**tring")

**Comment by ISSOtm** [comment]
`REDEF`'s behavior could be extended later, depending on the symbol type and/or more keywords?
