### ISSUE TITLE
Combining interpolation and macro args during raw lexer mode fails

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#683]
Test case `test.asm`:

```
myprintln: MACRO
	println \#
ENDM

test: MACRO
	println "{\1#{d:x}}"
ARG1 EQUS "\1"
	myprintln "{{ARG1}#{d:x}}"
PURGE ARG1
	myprintln "{\1#{d:x}}"
ENDM

FOO#42 EQUS "Hello!"
NAME EQUS "FOO"
x = 42
	test FOO
```

In `println "{\1#{d:x}}"`, the interpolation happens correctly and it prints "Hello!", since it was lexing in normal mode and `readString` did the interpolation. In `myprintln "{{ARG1}#{d:x}}"`, it also happens correctly.

In `myprintln "{\1#{d:x}}"`, the `myprintln` macro starts lexing its arguments in raw mode, and it gives these errors:

```
ERROR: test.asm(16) -> test.asm::test(10):
    Interpolated symbol "\1#42" does not exist
ERROR: test.asm(16) -> test.asm::test(10) -> test.asm::myprintln(2):
    Missing }
ERROR: test.asm(16) -> test.asm::test(10) -> test.asm::myprintln(2):
    Interpolated symbol "" does not exist
ERROR: test.asm(16) -> test.asm::test(10) -> test.asm::myprintln(2):
    Unterminated string
```

**Comment by Rangi42** [comment]
This is due to `yylex_RAW`'s inconsistent concept of being "inside a string".

On the one hand, it tracks `insideString` based on seeing quote marks, so it can read semicolons as string characters or as starting comments.

On the other hand, no other characters get special treatment. Seeing a comma when `insideString` is true still starts the next macro argument, leaving an unclosed string as the first one. Which also means that it can mix up whether it's outside or inside a string. For example:

```
mymacro: MACRO
    println "Message:"
    println \#
    println "Over."
ENDM

    mymacro "Hello, world; bye!" ; comment
```

You might expect this to print:

```
Message:
Hello,world; bye!
Over.
```

Actually, it fails:

```
Message:
ERROR: test.asm(7) -> test.asm::mymacro(3):
    Unterminated string
Hello,world
Over.
error: Assembly aborted (1 errors)!
```

It reads the first argument as `"Hello`, and then reads the second argument as `world; bye!" ; comment`: the chars `world` followed by a comment `; bye!" ; comment`.

**Comment by Rangi42** [comment]
To fix this, I propose that the lexer's raw mode be more consistent and more strict about reading string literals. While it's inside one, it should act just like `readString` (just call `readString` if possible to read the string-literal part of its argument). This would mean:

- `mymacro "Hello, world!"` would get one argument: `\1` is `"Hello, world!"`.
- `mymacro "Hello {X}!"` would use `readString`-style interpolation for `{X}`, so if `X EQUS "X"`, it would not enter an infinite loop; it would just evaluate to `"Hello X!"`.
- `mymacro "unclosed string` could print an error, and then just go ahead and let `\1` expand to the unclosed partial string literal.

Thoughts? Are there any projects with macros that would be disturbed by this?

**Comment by Rangi42** [comment]
The only other consistent solution I can see for this is to remove the `insideString` checks entirely, without any concept of "string literals" in macro arguments, just raw characters with the `{interpolations}` and `\1`-`\9` args expanded.

The major downside to that would be needing to escape semicolons when you want them inside string literals. For example:

```
greet: MACRO
    println "Clippy says:"
    println \1
ENDM

    greet "Hello\, world\; bye!"  ; comment
```

```
Clippy says:
Hello, world; bye!
```

**Comment by aaaaaa123456789** [comment]
Honestly, I've always seen the non-atom behavior of strings as a bug. `mymacro "Hello, world!"` should be one argument — it's what literally everyone expects, and the current behavior is a harsh violation of the principle of least astonishment.
I can't think of anything useful that could be done using the current behavior, too. This would be a net positive.

**Comment by Rangi42** [comment]
I'd be surprised/disturbed if any actual projects depend on the current lexer behavior for macro args with incomplete strings. :P

**Comment by Rangi42** [comment]
Another way to write this would be separate 'normal' and 'raw' functions for reading string literals, and handling interpolations or macro args within them. That may or may not be neater than the current approach here of a boolean flag.

**Comment by Rangi42** [comment]
Note that this bug does not exist in 0.4.2: it's a result of how `master` has changed `{interpolation}`.

```
myprintt: MACRO
	printt \1
ENDM

test: MACRO
	printt "{\1#{d:x}}\n"
ARG1 EQUS "\1"
	myprintt "{{ARG1}#{d:x}}\n"
PURGE ARG1
	myprintt "{\1#{d:x}}\n"
ENDM

FOO#42 EQUS "Hello!"
NAME EQUS "FOO"
x = 42
	test FOO
```

In 0.4.2 this prints:

```
Hello!
Hello!
Hello!
```

So regarding the discussion in #668, fixing this with #685 would be less of a breaking change, since part of the fix only changes not-yet-released behavior. The main possibility for breakage is if someone was relying on passing unbalanced quotes to macros.
