### ISSUE TITLE
[Feature request] `BREAK` keyword to early exit a macro or REPT/FOR block

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#684]
Some use cases:

```
FOR idx, 1, N+1
  IF ITEM_{d:idx} == $42
    PRINTLN "Found $42 at index {d:idx}"
    BREAK
  ENDC
ENDR
; now idx == the index of $42 in the ITEM_1--ITEM_N,
; or idx == N if $42 wasn't found
```

```
; alternative 1, with `break`
printitem: MACRO
valid = 1 <= (\1) && (\1) <= N
  assert valid, "Invalid index: \1"
  if !valid
    break
  endc
  print ITEM_\1 ; pretend there's a lot of code here
ENDM
```

```
; alternative 2, with the main code wrapped in an `if/endc`;
; sometimes this looks too nested 
printitem: MACRO
valid = 1 <= \1 && \1 <= N
  assert valid, "Invalid index: \1"
  if valid
    print ITEM_\1 ; pretend there's a lot of code here
  endc
ENDM
```

**Comment by aaaaaa123456789** [comment]
This seems useful overall. I wonder how complex it would be? It also turns a `rept $7FFFFFFF` block into essentially a `while` loop, so it might be worth adding those too.

**Comment by ISSOtm** [comment]
I implemented `BREAK` fairly simply:
```c
void fstk_Break(void)
{
    dbgPrint("Breaking out of REPT/FOR");
    if (contextStack->fileInfo->type != NODE_REPT) {
        error("BREAK can only be used inside REPT/FOR blocks");
        return;
    }

    // Force exiting the current (REPT) context, by setting its max iteration count to 0,
    // and then wrapping.
    contextStack->nbReptIters = 0;
    yywrap();
}
```
But this fails to account for any `IF`s that it may be inside of.

It would be possible to count the `IF` nesting level since the beginning of the loop block, and pretend that we exit them, but that would allow otherwise invalid syntax:
```asm
REPT 1
    ; ...
    IF 1
        BREAK
ENDR
```

The proper thing to do would be to parse the rest of the block, except that we skip executing all statements, but that would be a major change, essentially gating all rules behind `if (!skipped)`. Consider the following:
```asm
REPT 1
    BREAK
    ld a, 1 / 0
ENDR
```

**Comment by Rangi42** [comment]
I revised mine so `yylex_SKIP_TO_ENDR` keeps `nIFDepth` up-to-date as it skips ahead to the matching `ENDR`. This gives expected results for balanced and unbalanced `IF`/`ENDC`, but still has the issue with pipes.

**Comment by ISSOtm** [comment]
Yes, `ENDR` is specifically omitted from the `REPT` capture block after it is scanned.

I will check your code later when I have some time, but keep in mind that only `ENDC` at BOL (= only whitespace before it) should count. Further, are there other constructs that would need to be kept track of similarly.

**Comment by Rangi42** [comment]
Some invalid syntax is already allowed inside unexecuted blocks:

```
if 0
foo: macro ; no endm
  rept 42 ; no endr
    ; can't do unbalanced if/elif/endc, it would affect skipping to the else
else
bar: macro
  println "okay"
endm
endc
  bar
```

So if your `yywrap` solution otherwise works, then it's arguably okay to use. It's much simpler than parse-without-execute until the `ENDR`, and usually a `BREAK` wouldn't happen on the very first loop anyway, in which case the parser would have a chance to see+validate the whole loop body.

**Comment by Rangi42** [comment]
Actually, the `fstk_Break`-calls-`yywrap` solution also isn't complete: on break.asm, it outputs:

```
ERROR: break.asm(9):
    syntax error
error: Assembly aborted (1 errors)!
1, 2, 3, 4, 5 stop!
```

**Comment by ISSOtm** [comment]
Yeah, I haven't checked if newlines are handled properly, I didn't consider it worth if we weren't going to roll with it. It did work with my test file, which was more generous with them, so I'll look further into that.
