### ISSUE TITLE
CMake builds should be optimized

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#693]
Neither `-O3` nor `-flto` are applied for CMake builds. Makefile builds use `-O3` but not `-flto`.

**Comment by JL2210** [comment]
They are. As is standard for CMake projects, `-DCMAKE_BUILD_TYPE=Release` is required for an optimized build.

**Comment by ISSOtm** [comment]
CMake only applies `-O3` by default, but not `-flto`.

**Comment by daid** [comment]
Note that I've had issues with -flto and mingw64, where it would create compile errors.

**Comment by ISSOtm** [comment]
> Note that I've had issues with -flto and mingw64, where it would create compile errors.

[Apparently not here](https://github.com/ISSOtm/rgbds/runs/1674440013?check_suite_focus=true#step:6:9)
