### ISSUE TITLE
[Feature request] Specify an expected quantity of macro args

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#695]
`foo: MACRO 3` would define `foo` to take 3 arguments. Then when `foo` is used, if `nbArgs` is not 3, it would print an error. (This could be a fatal error; a non-fatal one but don't run the macro; or a non-fatal one and try running it anyway.)

`foo: MACRO 1, 3` would define `foo` to take between 1 and 3 arguments. So `foo: MACRO 0, 3` would take at *most* 3 arguments.

Since `nbArgs` is unsigned, the new `minArgs` and `maxArgs` could be too. That would make `MACRO 3, -1` a convenient way to specify at *least* 3 arguments, since `-1` wraps around to `UINT32_MAX`.

If the second number is less than the first, that should report an error; but then it could either swap the two numbers, or ignore the second one, or ignore both.

**Comment by aaaaaa123456789** [comment]
Isn't this something trivial to do already?

```
foo: MACRO
  assert _NARG == 3, "This macro takes 3 arguments"
  ; do whatever
ENDM
```

**Comment by Rangi42** [comment]
Well, yes; but "how many args does this take" is a pretty fundamental check that can apply to the majority of macros. It would be simpler to add one or two numbers to a bunch of macros than to give each one an `assert`.

**Comment by aaaaaa123456789** [comment]
It looks confusing to me, for the same reason I argued against `rept 200, X` back then: nothing in the syntax hints at what's going on. I'd be much happier with argument _names_, if we could use those names somehow...

**Comment by Rangi42** [comment]
Named macro args would probably wait at least until the [symbol "layering" system](https://github.com/gbdev/rgbds/discussions/662).

**Comment by Rangi42** [comment]
Closing this one. Named macro args could be their own issue if/when symbol layering is added, although I don't think they're necessary either: `@foo EQUS "\1"` would work already instead of `mac: MACRO @foo` (with an initial `@` so it would be local to the macro, as in #342).
