### ISSUE TITLE
Macro and REPT/FOR body capture bugs

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#697]
- [ ] Any text between `MACRO` and the newline is included in the macro body, and breaks line numbers by 1:

```
foo: MACRO println "this is handled {__LINE__}"
    println "foo {__LINE__}"
ENDM this is ignored
println "start {__LINE__}"
    foo
println "done {__LINE__}"
```

```
start $3
this is handled $1
foo $2
done $5
```

- [ ] Text from `ENDM` or `ENDR` to the newline is ignored:

```
println "start {__LINE__}"
REPT 3
    println "rept {__LINE__}"
ENDR this is ignored
println "done {__LINE__}"
```

```
start $1
repeat $3
repeat $3
repeat $3
done $5
```

**Comment by aaaaaa123456789** [comment]
I think the only sane way to handle this is to make both things hard errors — putting code there is nonsense to begin with, and the few projects that do can easily fix this. (See: similar issues with conditionals.)

**Comment by Rangi42** [comment]
Yes, those should be syntax errors. (Ideally using the parser's own syntax error handling, not having to do some special-casing in the lexer's reading of `ENDM`/`ENDR`.)

**Comment by Rangi42** [comment]
#698 deals with both points by parsing the newlines as part of the `MACRO/REPT` and `ENDR/ENDM` lines, similar to how `IF/ELIF/ENDC` were treated already.
