### ISSUE TITLE
My Installing Issue

### ISSUE THREAD

**Issue by P0W3** [gbdev/rgbds#699]
I put a folder, rgbds-0.4.2-win64 (with the files), in C:\, and I do not know how to specifically run RGBDS.

![image](https://user-images.githubusercontent.com/18279115/104401778-dffbc400-5522-11eb-94f1-ebcdf001a7e8.png)

Using Cygwin, I tried to run RGBDS, and it did not work.

![image](https://user-images.githubusercontent.com/18279115/104401345-fbb29a80-5521-11eb-944f-957c88374c45.png)

Using MSYS2, I tried to run RGBDS, and it did not work.

![image](https://user-images.githubusercontent.com/18279115/104401692-b2af1600-5522-11eb-883a-77c5e841eb50.png)

**Comment by Rangi42** [comment]
GitHub issues are for things to fix *in* rgbds, not for usage of it.

Follow the [install guide for Windows](https://rgbds.gbdev.io/install/windows) to use rgbds.

**Comment by aaaaaa123456789** [comment]
Let me copy from your own error screen:

> This problem is probably due to using incompatible version of the cygwin DLL.
> Search for cygwin1.dll using the Windows Start->Find/Search facility and delete all but the most recent version. The most recent version \*should\* reside in x:\\cygwin\\bin, where 'x' is the drive on which you have installed the cygwin distribution. Rebooting is also suggested if you are unable to find another cygwin DLL.

**Comment by Rangi42** [comment]
(Although you don't need to `make` the programs anyway; you just downloaded them.)

**Comment by ISSOtm** [comment]
Closing as unrelated to RGBDS itself, though I won't mind a few more posts if you need more help setting up.
