### ISSUE TITLE
[Feature request] UNSHIFT for macro args

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#700]
This would occasionally be convenient, especially since backslash args can only access nine of them.

If a macro needs to do multiple passes over all its arguments, that currently has to use `\#`; but the expansion of `\#` has to fit in a 255-char-limited string.

```
submac: MACRO
	rept _NARG
		print STRSUB("ABCDEFGHIJKLMNOPQRSTUVWXYZ ", \1, 1)
		shift
	endr
ENDM

mac: MACRO
	submac \#
	for i, _NARG
		print \1
		shift
		if _NARG > 0
			print ", "
		else
			print "\n"
		endc
	endr
ENDM

	mac $d, $1, $3, $1b
```

vs.

```
mac: MACRO
n = _NARG
	rept n
		print STRSUB("ABCDEFGHIJKLMNOPQRSTUVWXYZ ", \1, 1)
		shift
	endr
	unshift n
	for i, n
		print \1
		shift
		if i < n - 1
			print ", "
		else
			print "\n"
		endc
	endr
ENDM

	mac $d, $1, $3, $1b
```

**Comment by ISSOtm** [comment]
That's better handled as just removing the limit on string lengths, which needs to happen anyway.

**Comment by Rangi42** [comment]
I mean, `\#` is a solution for passes like that, but you may also want to skip ahead some args, work with a later subset, then go back where you left off. Or while you're iterating through args, there's an arg with a sentinel value that means you need to reuse some earlier values.

**Comment by ISSOtm** [comment]
Having to shift back and forth seems just the X when the Y problem is that only 10 args can be accessed at a given time. Named args would solve the problem.

**Comment by aaaaaa123456789** [comment]
> Having to shift back and forth seems just the X when the Y problem is that only 10 args can be accessed at a given time. Named args would solve the problem.

...or a way to access more than 9 arguments at the same time and to use something other than a hardcoded constant as an index, since this also solves the iteration problem (which named arguments don't). This is the kind of scenario I had in mind when I made #460...

**Comment by ISSOtm** [comment]
Named arguments à la `__VA_ARGS__` but with an "index" syntax should fulfill that use case.

**Comment by aaaaaa123456789** [comment]
How would that work?

**Comment by Rangi42** [comment]
[Sjasm](http://www.xl2s.tk/sjasmman11.html)'s `rotate` statement is its equivalent to `shift` and allows negative values.

**Comment by Rangi42** [comment]
Since the last variable-macro-arg proposal (#460) was closed, and allowing `shift -N` would be trivial to implement, can this be done anyway?
