### ISSUE TITLE
Modulo misbehaves with negative numbers

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#703]
The modulo operator uses C's semantics, where for example `-1 % 256 == -1`. It would be more useful to have Python's semantics, where `-1 % 256 == 255`. (See https://stackoverflow.com/questions/3883004/the-modulo-operation-on-negative-numbers-in-python and https://en.wikipedia.org/wiki/Modulo_operation for some comparison.)

**Comment by Rangi42** [comment]
(I noticed this when testing [bf.asm](https://pastebin.com/k0Tva4ux); I'd expected `mem_p = (mem_p - 1) % mem_len` to wrap around correctly but it doesn't.)

**Comment by aaaaaa123456789** [comment]
I'm not sure if this is really "misbehaving". Also, true remainders are useful, but only if division also rounds down (e.g., -7 / 3 = -3), ensuring that p / q \* q + p % q = p.

**Comment by Rangi42** [comment]
Currently `-7 / 3 == -2`, not `-3`. Which is also a C-ism; in Python `-7 // 3 == -3`. (Using C and Python as representatives of many other languages, of course.)

**Comment by aaaaaa123456789** [comment]
In a low-level language like C, the choice of division is definitely wrong, as the alternative is much faster.
In other cases, though, it doesn't matter, as it is very simple to convert one into the other. For the sake of compatibility, I'd leave this alone; Python-like division can be easily implemented as a user-defined function if needed.

**Comment by Rangi42** [comment]
At least both ensure that `p / q * q + p % q = p`:

- C-style: `-7 / 3 == -2`; `-7 % 3 == -1`; `-7 == -2 * 3 + -1`
- Python-style: `-7 // 3 == -3`; `-7 % 3 == 2`; `-7 == -3 * 3 + 2`

However, I'd also expect `p % q == (p + q * k) % q` for any integer `k`, which the current style does not ensure. (It's not exactly "C"-style, since in C the sign here is "implementation defined".)

Likewise I'd expect `n % 256 == n & $FF == LOW(n)`, which is not currently the case. (`-2 % $FF == 254`, but `-2 % 256 == -2`; at least `LOW(-2 % 256) == 254`.)

**Comment by Rangi42** [comment]
[This `comp.std.c` discussion](https://groups.google.com/g/comp.std.c/c/hjGK3cx_I-o/m/_zB17QyViDgJ) is relevant; apparently the behavior of `/` and `%` *used* to be implementation-defined, but was standardized in C9x because "it's how Fortran does it".

> > Plus it's how Fortran does it. And I agree that it's a pain.
> That was in fact the main argument for C9x requiring truncation toward zero. I drafted the wording for the change, because it was the committee consensus, not because I personally think it is a wise choice. (I would have preferred that integer division act as a regular "step function" as zero is crossed, i.e. % would be better as a true modulo operator.)

**Comment by aaaaaa123456789** [comment]
I think virtually everyone (outside of the committee) agrees that C made the wrong choice there...
That being said, as I said before, this is breaking compatibility, so it's probably better to leave it alone, particularly since user-defined functions can easily patch the gap.

**Comment by Rangi42** [comment]
IMO this is a case like changing the behavior of macro args, where projects are very unlikely to be depending on the broken case, and the non-broken case solves itself. (That is, if someone is doing `a/b-(a%b<0)` or `(a%b+abs(b))%b` in rgbasm code to get the "standard mathematical" div/mod behavior, that workaround won't break if rgbasm's internal div/mod behavior changes.)

**Comment by ISSOtm** [comment]
Imo, the semantics should only be changed if `p / q * q + p % q ≠ p`.

**Comment by Rangi42** [comment]
`p / q * q + p % q == p` is true for either case. `p % q == (p + q) % q` or `p % q == (p - q) % q` is not currently always true, nor is `p % 2**n == p & (2**n - 1)`.

**Comment by Rangi42** [comment]
The current possibility that `p % q != (p ± q) % q` in particular surprises me, since that's a [fundamental property](https://en.wikipedia.org/wiki/Modular_arithmetic#Congruence) of modular arithmetic. "Indeed, *b* mod *n* denotes the unique integer *a* such that 0 ≤ *a* < *n* and *a* ≡ *b* (mod *n*) (i.e., the remainder of *b* when divided by *n*."
