### ISSUE TITLE
\@ can inadvertently create duplicate labels

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#717]
Since `\@` expands to `_u%d`, where `%d` is an incrementing ID starting at 1, users can define labels that clash with it.

```
def_foo_u1: MACRO
foo\@:
ENDM

SECTION "test", ROM0
foo_u1:
  def_foo_u1
```

```
ERROR: main.asm(7) -> main.asm::def_foo_u1(2): 'foo_u1' already defined at main.asm(6)
```

This may be unavoidable; but I'd suggest using the uncommon character "`#`" in the generated value of `\@` instead of "`_u`". ("`@`" is also allowed in label names, but per #342, it might gain a special meaning of defining local symbols. "`#`" has no such plans.) (I can't tell why either one was ever allowed in label names... other assemblers allow "`$`", but that's used in rgbasm for the hex prefix...)

**Comment by ISSOtm** [comment]
Given that `\@` is expanded *before* label lexing is performed, it can't expand to characters that are otherwise invalid in symbols, so I'm pretty sure this is unavoidable.

**Comment by Rangi42** [comment]
Once scope-local symbols are implemented, it might be worth deprecating `\@`. Until then, yeah, it's unavoidable.

**Comment by ISSOtm** [comment]
Perhaps. Anonymous labels may also obsolete them for label purposes, less so for constants, but scope-local symbols cover those, I guess.

**Comment by Rangi42** [comment]
An anonymous label inside a macro would affect the distances of prior/subsequent anonymous label references.

```
wait_vblank: MACRO
:   ldh a, [rLY]
    cp 145
    jr c, :-
ENDM

Foo:
    some code
:   more code
    jr z, :+
    wait_vblank
    jp :-
:   cleanup code
    ret
```

**Comment by ISSOtm** [comment]
Macros are just leaky as hell, I guess!

**Comment by Rangi42** [comment]
There's ultimately no solution here -- even if `\@` were somehow context-aware and avoided creating duplicate labels in one RGBASM run, a second translation unit still could alias it. Anyway, anonymous labels are a good alternative for this sort of thing.

**Comment by aaaaaa123456789** [comment]
> There's ultimately no solution here -- even if `\@` were somehow context-aware and avoided creating duplicate labels in one RGBASM run, a second translation unit still could alias it. Anyway, anonymous labels are a good alternative for this sort of thing.

Generating identifiers that are very unlikely to clash even without synchronizing with other generators has been a solved problem for decades... how come there is no solution here?

**Comment by ISSOtm** [comment]
This tends not to be a problem in RGBASM, because `\@` is rarely used outside of unexported local labels, which are inherently namespaced by their parent label.

**Comment by Rangi42** [comment]
> Generating identifiers that are very unlikely to clash even without synchronizing with other generators has been a solved problem for decades... how come there is no solution here?

The problem I opened this issue for was *adverserial* name clash; a user who knows that `\@` expands to `_u12345` and defines their own symbol to clash with it, just for funsies.

There's never a reason to export an identifier generated with `\@`, since other translation units can't predict it and so can't refer to it, so we're also safe from accidental clash with other object files.

(Of course, you could export your `Foo\@` symbol anyway, and then, knowing the IDs are sequential, export a different one from another object; and have a third object manually refer to a `Foo_u42` label. But this is the "adverserial for the fun of it" example again. The solution is "stop doing that".)
