### ISSUE TITLE
Document the process of creating a release

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#718]
All the steps involved with a new release: updating version numbers in code and docs; creating the Git tag and the GitHub release; building and uploading all the assets; etc.

**Comment by Rangi42** [comment]
The create-release-artifacts.yaml and create-release-docs.yml workflows will automatically create releases. You have to push a Git tag starting with `v` and a number, and if the tag name contains `-rc`, the release will automatically be marked as pre-release.

You should first update the version numbers in `include/version.h`, commenting out `PACKAGE_VERSION_RC` if it is not a release candidate/pre-release.

**Comment by ISSOtm** [comment]
I have automated as much of it as possible, I think what we have now is the strict minimum human action (and knowledge) required.

The question is now to find a place to document this.

**Comment by Rangi42** [comment]
RELEASE.md?

**Comment by ISSOtm** [comment]
Sounds good!
