### ISSUE TITLE
[Feature request] Negate conditions

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#719]
Many times, when writing a macro, you'd want to emit a condition that is the _opposite_ of the condition you receive as a macro argument. What I'm asking for, then, is to be able to negate a condition with an operator, like `!`.
For instance, `jr !z, .foo` would be the same as `jr nz, .foo`, and `call !nc, MyFunc` would be the same as `call c, MyFunc`.
(Ideally, multiple `!` operators should cancel each other: `jr !!nz, .foo` = `jr nz, .foo`. This would make nested macros simpler.)

**Comment by Rangi42** [comment]
Since this is a jump condition related issue: I've also considered requesting support for `cy` as an alternative to `c` for the carry flag. It's already written that way in some (GB)Z80 documentation, and could help avoid confusion with the `c` register. (Similarly, supporting `hl+`/`hl-` is IMO more obvious to beginners than `hli`/`hld`.)

**Comment by aaaaaa123456789** [comment]
`hl+` and `hl-` are already supported, though.

**Comment by Rangi42** [comment]
Yeah, I was comparing `cy` to them.

**Comment by ISSOtm** [comment]
That'd be more adapted for token-level macros (à la C)

**Comment by Rangi42** [comment]
Some macros are written expecting particular tokens as input. For instance, you can do `HIGH(\1)` and `LOW(\1)` to decompose `hl/bc/de`.

**Comment by ISSOtm** [comment]
Put differently, I don't think this is common enough to be worth adding to the syntax.

**Comment by Rangi42** [comment]
What about `CY`?

**Comment by aaaaaa123456789** [comment]
> Put differently, I don't think this is common enough to be worth adding to the syntax.

I have a large enough number of macros that are written in very awkward ways due to this. I _could_ define an enum and use the numeric values of the instructions, but the whole point of instruction-like macros is that they look like instructions — `checkxyz nc, .foo` looks a lot better than `checkxyz COND_NC, .foo`.

**Comment by Rangi42** [comment]
Even if it's only a feature used for uncommon advanced macros, I think it's worth adding. `z/nc` and `c/nc` have a logical relationship, like `hl/h/l`, `bc/b/c`, and `de/d/e`, that the `!` operator would make available at the parsing level. (No need to do `!STRCMP(STRLWR("\1"), "nc")`, which would still fail if `\1` had any leading/trailing whitespace.)

**Comment by ISSOtm** [comment]
> `checkxyz nc, .foo` looks a lot better than `checkxyz COND_NC, .foo`.

It's still possible to pattern match and invert manually:
```
    IF !STRCMP(STRLWR(STRSUB("\1", 1, 1)), "n")
INV_COND equs STRSUB("\1", 2, 1)
    ELSE
INV_COND equs "n\1"
    ENDC
```

> Even if it's only a feature used for uncommon advanced macros, I think it's worth adding. `z/nc` and `c/nc` have a logical relationship, like `hl/h/l`, `bc/b/c`, and `de/d/e`, that the `!` operator would make available at the parsing level.

I don't like that it makes the conditions look like expressions, which they aren't, and may confuse readers, especially inexperience. This is why I am pushing for keeping a separate syntax.

> (No need to do `!STRCMP(STRLWR("\1"), "nc")`, which would still fail if `\1` had any leading/trailing whitespace.)

Macro args are stripped of leading and trailing whitespace for this very reason, so this is not an issue. (Brace expansions may cause this not to be the case, but then that'd be a bug.)

**Comment by ISSOtm** [comment]
> What about `CY`?

It's outdated syntax, as much as `ldi a, [hl]` or `jp [hl]`. Everybody agrees on the z80 syntax now; and if you are desperate for a shim, you can always `cy equs "c"` and/or `CY equs "C"`.

**Comment by aaaaaa123456789** [comment]
Pattern matching and inverting is at the very least an annoyance, and a lot harder to read.

Also, conditions _are_ expressions — on flags. `z` is a test for `z == 1`, after all.

**Comment by ISSOtm** [comment]
Except they're hardcoded in the instruction byte, and not part of an expression *per se*.

**Comment by Rangi42** [comment]
> Except they're hardcoded in the instruction byte, and not part of an expression _per se_.

You could say the same for the `rst` values, but it's convenient to allow `rst <expression>` instead of separate `rst8`, `rst10`, etc.

I was personally confused by `c` and `nc` when I first started with GBZ80, but that's not an rgbasm problem; they're well-documented in gbz80(7). If someone doesn't understand `!nc`, they would go to that same doc and see that ** ! *cc* ** is a negated *cc*, no other operators allowed.

**Comment by ISSOtm** [comment]
> You could say the same for the `rst` values, but it's convenient to allow `rst <expression>` instead of separate `rst8`, `rst10`, etc.

Well, that's why some assemblers only allow literally `0x38` etc. as operands, and why RGBASM used to require compile-time constness. Further, they're addresses, which are still somewhat expression-like.

> I was personally confused by `c` and `nc` when I first started with GBZ80, but that's not an rgbasm problem; they're well-documented in gbz80(7). If someone doesn't understand `!nc`, they would go to that same doc and see that **! _cc_** is a negated _cc_, no other operators allowed.

Imo, that would be an extension to the gbz80 syntax, not part of the syntax per se.

**Comment by aaaaaa123456789** [comment]
> Imo, that would be an extension to the gbz80 syntax, not part of the syntax per se.

You could say the same about `ld HIGH(de), HIGH(bc)`.

**Comment by Rangi42** [comment]
This use of `!` is also supported by [Sjasm](http://www.xl2s.tk/sjasmman5.html).

**Comment by Rangi42** [comment]
A concrete example of a macro that could benefit from this:

```
MACRO do_if
    jr ! \1, :+
    shift
    \#
:
ENDM

    ; hl += a
    add l
    ld l, a
    do_if c, inc h

    ; wrap around MIN to MAX
    cp MIN
    do_if c, ld a, MAX
```

Admittedly this could use `STRCMP` to create the right jump; but the `do_if` macro would look more complicated that way than it really is, and *if* I were using `cy EQUS "c"`, that would need explicit support by `do_if` and any other macro that wants to negate conditionals.
