### ISSUE TITLE
[Feature request] File-related functions

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#724]
- [ ] `FEXISTS("file")` to check if a file exists (inspired by [tniASM](http://www.tni.nl/products/tniasm.html)'s `IFEXIST`)
- [ ] `DEXISTS("dir")` to check if a directory exists
- [ ] `FSIZE("file")` to get the size of a file in bytes (-1 if an error occurs, e.g. it doesn't exist, is a directory, can't be read, etc)

Example use case for `FEXISTS`: internationalization.

```
LANG EQU "de"

resbin: MACRO
; \1: file to include
; \2: source that the file gets built from (optional)
  if fexists(strcat("{LANG}/", \1)) || _NARG > 1 && fexists(strcat("{LANG}/", \2))
    incbin strcat("{LANG}/", \1)
  else
    incbin \1
  endc
ENDM

OverworldText: resbin "data/overworld.dat"
OverworldGFX: resbin "gfx/overworld.2bpp", "gfx/overworld.png"
```

Example use case for `FSIZE`: [polishedcrystal](https://github.com/Rangi42/polishedcrystal/) stores up to 384 tile graphics in a single PNG. The Makefile converts this to a 2bpp with rgbgfx, then splits into three pieces with `head` and `tail` (the first 128 tiles as 2bpp.vram0, the next 128 as 2bpp.vram1, the last 128 as 2bpp.vram2), and finally compresses each piece separately. So the code can have `INCBIN "gfx/overworld.2bpp.vram0.lz"` and it will automatically be converted+split+compressed from the source gfx/overworld.png. However, most tilesets aren't large enough to have all three pieces, and I'd like to be able to do this:

```
if FSIZE("gfx/overworld.2bpp") > $1000
OverworldGFX2LZ: INCBIN "gfx/overworld.2bpp.vram2.lz"
else
OverworldGFX2LZ EQU 0
endc
```

**Comment by aaaaaa123456789** [comment]
All of this can be solved with a single `FILESIZE` function, really. If the size can't be obtained, you can assume the file doesn't exist or is not readable. Perhaps return -2 for a directory so that can be tested for — or, if we ever have directory enumeration, have a `DIRSIZE` function that returns the number of elements in a directory or -1.

**Comment by Rangi42** [comment]
I think a separate `DIRSIZE` function would be more clear than a magic `-2` return value, even though there isn't a clear use case for counting the files in a directory.

**Comment by aaaaaa123456789** [comment]
> I think a separate `DIRSIZE` function would be more clear than a magic `-2` return value, even though there isn't a clear use case for counting the files in a directory.

It's only useful if you have a directory enumeration function, say `DIRFILE(dir, index)`, that returns the name of the index'th entry in a directory. Something like that could be used to include an entire directory, for instance.

**Comment by Rangi42** [comment]
I'd be fine with an initial PR that just adds `FILESIZE()` with a -1 return code on failure. If anyone needs to check whether a directory exists, or enumerate one's contents, that can be a separate issue.

**Comment by ISSOtm** [comment]
RGBASM needs not support this, [as this can be supported by the build system instead](https://github.com/ISSOtm/quartet-intro/blob/c90fdf9534be5bd1c705db1d06761509ed5b3356/Makefile#L121-L123). Again, I'm wary of bloat.

**Comment by Rangi42** [comment]
I don't see how a build system could support this case:

```
; the code to load <Tileset>GFX<#>LZ skips null pointers
if FILESIZE("gfx/overworld.2bpp") > $1000
OverworldGFX2LZ: INCBIN "gfx/overworld.2bpp.vram2.lz"
else
OverworldGFX2LZ EQU 0
endc
```

**Comment by ISSOtm** [comment]
```asm
INCLUDE "gfx/overworld.2bpp.size"
if SIZE > $1000
OverworldGfx2LZ: INCBIN "gfx/overworld.2bpp.vram2.lz"
else
OverworldGfx2LZ EQU 0
endc
```

**Comment by Rangi42** [comment]
Interesting; that is more flexible than adding filesystem-related functions to rgbasm.
