### ISSUE TITLE
SECTION FRAGMENTs do not cooperate with PUSHS/POPS

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#730]
```
SECTION FRAGMENT "A", ROM0
    ld hl, Foo
PUSHS
SECTION FRAGMENT "A", ROM0
    ret
POPS
    ld de, Bar
Bar:
    rrca
Foo:
    nop
```

This example omits the `ret` in its output; no `C9` byte:

```
21 07 00 11 06 00 0F 00
```

**Comment by ISSOtm** [comment]
I'm pretty sure this is because the `ret` fragment is concat'd with the "outer" one, but the offset is overwritten at the `POPS`, so it gets overwritten with the `ld de, Bar`.

**Comment by Rangi42** [comment]
I'd be fine with just not allowing `SECTION [UNION|FRAGMENT] "X"` when a section `"X"` is already on the stack.

**Comment by ISSOtm** [comment]
I guess this makes sense due to unclear semantics. I'll be open to define that behavior if some use case arises later on.
