### ISSUE TITLE
Empty macro args freeze the assembler

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#739]
Uncommenting either of those final lines gives an error and stops assembling at that point, without exiting the process.

```
mac: MACRO
  for i, _NARG
    println "arg ", i+1, ": <\1>"
    shift
  endr
  println
ENDM

  mac ,1,2   ; arg $1: <1> arg $2: <2>
;  mac 3,4,  ; syntax error, unexpected newline, expecting string
;  mac 5,,6  ; syntax error, unexpected ",", expecting string
```

It's also surprising that the leading '`,`' in '`mac ,1,2`' has no effect.

**Comment by ISSOtm** [comment]
Shouldn't empty macro args produce a `-Wextra` warning?

**Comment by Rangi42** [comment]
I'll add a `-Wempty-arg` warning for them, sure.
