### ISSUE TITLE
INCLUDing a file without a trailing newline can cause a syntax error

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#742]
`foo.inc`:

```
FOO EQU 42 ; no trailing newline
```

`test.asm`:

```
INCLUDE "foo.inc"
BAR EQU 100
	println FOO
	println BAR
```

This fails with an `ERROR: test.asm(2): syntax error, unexpected label`.

Adding a newline to the end of `foo.inc`, or a blank line after "`INCLUDE "foo.inc"`" in `test.asm`, fixes it. However, the newline after "`INCLUDE "foo.inc"`" already ought to be starting a new line.

**Comment by Rangi42** [comment]
One solution would be to go back to injecting a `T_NEWLINE` at EOF. That would also solve a related issue: the parser's `line_directive`s cause syntax errors if they're at the end of the file without a trailing newline. For example, this:

```
if 1
 println "inside"
endc ; no trailing newline
```

fails with a `FATAL: test.asm(3): Ended block with 1 unterminated IF construct` even though it does lex and parse the `endc`.

**Comment by Rangi42** [comment]
@ISSOtm :

> An artificial newline needs to be injected at EOB when not at top level  
> Alternatively, have the lexer return an "`EOB`" token  
> So `asmfile` would become a series of `buffer`s, and each `buffer` would be `lines`, a possibly empty `last_line`, and a `EOB`  
> (We could also use this occasion to make macro bodies and `REPT` blocks not end with a newline, so that syntax errors would report `unexpected <end of input>`

**Comment by Rangi42** [comment]
Injecting a newline at the end of buffers affects the reported line numbers in some test results. An `EOB` token sounds like the appropriate solution.

**Comment by ISSOtm** [comment]
Remind me to add a test case for `INCLUDE` at EOB without a newline, after this gets fixed.

**Comment by ISSOtm** [comment]
Currently, all `endc`s must be followed by a newline, due to being `line_directive`s. Why is that?

**Comment by Rangi42** [comment]
Probably because if anything is on the same line after them, line "`endc println 2 + 2`", then not parsing a newline would either skip that without a syntax error, or execute it as if it's a separate line. Likewise for `endr` and `endm`; they're all tokens that get scanned to by skipping ahead.

**Comment by ISSOtm** [comment]
I mean that the `endc` could be part of `directive`s instead of being a `line_directive`, since it doesn't switch the lexer mode. This would allow it to be at EOF w/o newlines, which is currently not allowed.

**Comment by Rangi42** [comment]
As long as the change doesn't introduce a bug like that, sure.

**Comment by ISSOtm** [comment]
I was asking if there was a specific reason for it to be in `line_directives`; a comment states that it's because the lexer state must be switched *after* the newline has been read, so I wanted to know if there is another reason for `endc` to be there.

**Comment by Rangi42** [comment]
I don't think there is, no.
