### ISSUE TITLE
[Feature request] Deprecate empty entries in db/dw/dl, and thus allow trailing commas

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#753]
Currently empty `db`/`dw`/`dl` entries are treated as padding bytes (and give a `-Wempty-entry` warning). Furthermore, a trailing comma creates an empty final entry.

Empty entries could be deprecated (warn with `-Wobsolete` first), and single trailing commas could then be allowed. This would match most other languages and might make data-generating tools a bit simpler. (`print "db "; for each byte { print byte; print ","; }`)

**Comment by ISSOtm** [comment]
I would implement this by separating "solo" `db`/etc. from one with a "constlist", and prevent empty entries.

**Comment by Rangi42** [comment]
Macro arguments, `print` arguments, and other comma-separated lists should also allow single trailing commas.

(Empty `db` entries act like padding bytes and will be deprecated; empty macro arguments are allowed with a warning; empty `print` arguments will still be a syntax error.)
