### ISSUE TITLE
[Feature request] Label name enhancement suggestions

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#758]
- [ ] Allow `$` within label names, like `#` and `@`. Some other assemblers also allow this (typically with a trailing `$` to make local labels instead of leading `.`). A use case: interpolating numbers into labels like `person{x}` instead of `person{d:x}`. Potentially breaking change: `mac$12` without space between would parse as one token, not two.
- [ ] Allow `#` to start label names, not just within them. A use case: a `#define` macro to define constants compatibly with C or asm.

**Comment by ISSOtm** [comment]
I don't like allowing `$` for that reason. You can use `{x:` if you really want hex.

`#define` is madness, the languages aren't even remotely compatible.

**Comment by Rangi42** [comment]
If `foo` is 42 then `person{foo}` expands to `person$2A`, an invalid label name. I was just thinking that could become valid to save typing two characters in `person{x:foo}` or `person{d:foo}`.

You're right that a `#define` macro wouldn't be some trivial wrapper around `EQU`, partly since `#define foo 42` has no comma separator. I had in mind how pokeemerald reuses the same files full of numeric `#define`s in its C and asm files. Also had other use cases in mind, like allowing `#THINGS` instead of `_NTHINGS`, `NUM_THINGS`, `SIZEOF_THINGS`, etc.

But yeah, neither of these is a strongly-wanted feature.

**Comment by ISSOtm** [comment]
I think that `#define` could be solved by instead running `cpp`. We also talked about giving `#symbol` special meaning, like `@symbol` for #342.

I would also like to reserve dollars for future use.
