### ISSUE TITLE
"." should not be a valid local label

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#760]
A `.` without any subsequent characters is a valid label:

```
section "test", rom0
foo:     db 1
.        db 2
.loc     db 3

bar:     db 4
bar.     db 5
bar.loc  db 6

baz:
    add sp, .  ; no error with assembly, only "Unknown symbol" with linking
```

I think this should be disallowed:

- It's not a label anyone's likely to want. Even if a function does use a single `.` label, it's better off as an anonymous `:`.
- Only one `.` is allowed in a local label anyway, so it's more like the separator between the global and local parts, than a character in its own right.
- It frees up a bare `.` to be a token used for something else.

**Comment by AntonioND** [comment]
Agreed, it shouldn't be valid.
