### ISSUE TITLE
Use Bison's "tracking locations"

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#778]
[Tracking locations](https://www.gnu.org/software/bison/manual/html_node/Tracking-Locations.html) might be more flexible than the current lexer's line+col tracking.

**Comment by Rangi42** [comment]
I'm not sure this can work given the way `INCLUDE` works.

**Comment by ISSOtm** [comment]
I think it *could* work, since we can really use custom types, and could probably use fstack handles in there.

But I think that would only be useful to try printing source code in errors, and personally I've given up on doing that in C(++).
