### ISSUE TITLE
[Feature request] Functions for working with charmapped values from strings

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#786]
- `CHARLEN("string")` returns the length of `"string"` in charmap entries
- `CHARSUB("string", n)` returns the *n*th charmap substring of `"string"`

This would make `db/dw/dl "{S}"` equivalent to:

```
for n, 1, CHARLEN("{S}") + 1
db/dw/dl CHARSUB("{S}", n)
endr
```

For example:

```
    charmap "A", $10
    charmap "B", $20
    charmap "C", $30
    charmap "Bold", $88

    assert CHARLEN("XBoldABC") == 5
    assert !STRCMP(CHARSUB("XBoldABC", 2), "Bold")
    assert CHARSUB("XBoldABC", 2) == "Bold" ; numeric conversion makes them both $88
    assert CHARSUB("XBoldABC", 1) == $58 ; ASCII for "X"
    println CHARSUB("XBoldABC", 2) ; prints "Bold"
```

If charmaps gain multi-byte support, a third function would also be useful, to get the length of a charmapped string in output bytes.

**Comment by ISSOtm** [comment]
No, `CHARSUB` should return the *slice* corresponding to the Nth byte. That way, it can be otherwise processed (e.g. printed), but the byte still obtained, though numeric conversion.

**Comment by Rangi42** [comment]
Updated the proposal to do that.

**Comment by Rangi42** [comment]
One use case of this will be verifying data lengths:

````
dname: MACRO
; declares a name (max 12-character string, terminated by 0x00)
    assert CHARLEN(\1) < 12, "name longer than 12 characters: \1"
    db \1, $00
ENDM
```
