### ISSUE TITLE
[Feature request] Suppress warnings for a single line

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#792]
Sometimes you know that some operation will result in a warning, but the operation is still correct. This is particularly common with warnings such as `-Wshift` or `-Wtruncation`, which are raised on operations that have well-defined results.
Of course a possible solution is to disable the relevant warning, but this is a global solution to a local problem.

An alternative would be to indicate that errors should be suppressed for a specific line only. For instance, let's assume that a trailing `!` is used for this purpose: something like `ld a, 400!` or `db -$30 >> 2!` would raise no warnings for that line only. (Why would these things happen? Macros, for instance.) If the line in question is a macro invocation, warnings should be suppressed for the entire expansion of the macro.

**Comment by Rangi42** [comment]
Issue #768 would cover this.
