### ISSUE TITLE
[Feature request] Let UNION apply to _RS values

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#797]
To have overlapping structure offset constants, you have to manually `RSSET` back to an earlier constant, much like the now-removed `ds wPreviousSymbol - @` hack:

```
rsreset
...
MON_CAUGHTDATA         rb 3
rsset MON_CAUGHTDATA
MON_CAUGHTTIME         rb
MON_CAUGHTGENDER       rb
rsset MON_CAUGHTDATA
MON_CAUGHTLEVEL        rb
MON_CAUGHTLOCATION     rb
MON_CAUGHTBALL         rb
...
```

goes with this struct-definition macro:

```
box_struct: MACRO
...
\1CaughtData::
\1CaughtTime::
\1CaughtLevel::    db
\1CaughtGender::
\1CaughtLocation:: db
\1CaughtBall::     db
...
ENDM
```

But just as a `UNION` could be used to define the struct:

```
box_struct: MACRO
...
UNION
\1CaughtData::     ds 3
NEXTU
\1CaughtTime::     db
\1CaughtGender::   db
NEXTU
\1CaughtLevel::    db
\1CaughtLocation:: db
\1CaughtBall::     db
ENDU
...
ENDM
```

It could also be allowed in the `RS` set:

```
rsreset
...
UNION
MON_CAUGHTDATA         rb 3
NEXTU
MON_CAUGHTTIME         rb
MON_CAUGHTGENDER       rb
NEXTU
MON_CAUGHTLEVEL        rb
MON_CAUGHTLOCATION     rb
MON_CAUGHTBALL         rb
ENDU
...
```

Spec: any `UNION` stores two numbers, the initial value of `_RS` and the maximum value. The `UNION` keyword initializes both to `_RS`; the `NEXTU` keyword resets `_RS` to the stored initial value. Any `RB`, `RW`, `RL`, `RSSET`, or `RSRESET` inside a union update the maximum value. The `ENDU` keyword sets `_RS` to the stored maximum.

**Comment by ISSOtm** [comment]
I think at this point, implementing this feature correctly would be best done by #98 and ensuring that it interacts correctly with `UNION`...

**Comment by Rangi42** [comment]
Is that a "no" to adding this in a minor update like 0.5.1? I expect just planning the spec for #98 to take more time, and then implementing+debugging it.

**Comment by ISSOtm** [comment]
`UNION` is only meant to affect memory declarations, so I'm not fond of giving it extra unrelated meaning. Plus, it could cause some breakage, and is mostly a hack—I'm definitely not opposed to giving `UNION` a different meaning within a `STRUCT` block, just not main scope.
