### ISSUE TITLE
Output USED instead of FREE space in the .map file?

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#808]
rgblink 0.5.0 so far is going to print "`FREE`" space at the end of the .map file, summing up the slack space for all sections.

```
FREE:
    ROM0: $7ffb bytes in 1 bank
    SRAM: $1ffb bytes in 1 bank
```

The issue with this is that it doesn't count banks which rgbfix would add as padding. So you have to manually account for those.

It might be more useful to print the "`USED`" space:

```
USED:
    ROM0: $0005 bytes in 1 bank
    SRAM: $0005 bytes in 1 bank
```

This quantity doesn't depend on rgbfix padding, and can be subtracted from whatever the user thinks the correct ROM should be. (So if they plan for a 2 MB ROM, and there are $200001 bytes, rgbfix would pad it out to a 4 MB ROM. A printout of free space, whether or not it includes all those padding banks, would not accurately represent "there's 1 byte more than you want".)

**Comment by pinobatch** [comment]
This'll need a release note in case people are writing ROM usage analysis tools that parse map files.

**Comment by Rangi42** [comment]
It's mentioned in 0.5.0-rc2: "RGBLINK outputs `USED` space at the end of a .map file"
