### ISSUE TITLE
peekInternal: Assertion `ofs < expansion->len' failed.

### ISSUE THREAD

**Issue by NieDzejkob** [gbdev/rgbds#813]
The following code

```
test: MACRO
v equs "X"
X equs ""
\1
ENDM
	test v 0
```

Results in this crash when compiled with assertions enabled:

```
rgbasm: src/asm/lexer.c:836: peekInternal: Assertion `ofs < expansion->len' failed.
Aborted (core dumped)
```

**Comment by Rangi42** [comment]
Building `master` with Cygwin `gcc`, I don't get a core dump, but it does fail:

```
ERROR: foo.asm(6) -> foo.asm::test(4):
    syntax error, unexpected number
ERROR: foo.asm(6) -> foo.asm::test(4):
    Unknown character 0x00
error: Assembly aborted (2 errors)!
```

**Comment by NieDzejkob** [comment]
> Building `master` with Cygwin `gcc`, I don't get a core dump, but it does fail:
> 
> ```
> ERROR: foo.asm(6) -> foo.asm::test(4):
>     syntax error, unexpected number
> ERROR: foo.asm(6) -> foo.asm::test(4):
>     Unknown character 0x00
> error: Assembly aborted (2 errors)!
> ```

To be clear, is that with `make develop`?

**Comment by NieDzejkob** [comment]
The assertion can still get triggered by this example:
```
v equs "v"
test:MACRO
\#v equs "v"
ENDM
        test v 0
```

**Comment by Rangi42** [comment]
Given how macros are supposed to work, that *should* be equivalent to:

```
v equs "v"
v 0v equs "v"
```

which has the infinite-recursion issue #696, but does not trigger the assertion.

**Comment by Rangi42** [comment]
This test case also triggers the assertion:

```
v equs "v"
MACRO test
 \1
ENDM
 test v 0
```

So does changing it to `v equs " v"`. Changing it to `v equs "v "` avoids the assertion, and fails with the expected "Recursion limit (64) exceeded" (since `\1` becomes `v 0` becomes `v  0` becomes `v   0` etc).

**Comment by Rangi42** [comment]
I think the problem might be that `lexerState->expansionOfs`, which is supposed to be the "Offset into the current top-level expansion (negative = before)", is being incremented even when nested expansions get expanded. It should only increment for the top-level expansion.

**Comment by Rangi42** [comment]
PR #799 does not happen to fix this issue yet, but it might help to simplify the relevant code.

**Comment by NieDzejkob** [comment]
> It might help, can't hurt. What fuzzer are you using?

I am using AFL++. After minimization and deduplication, it's 53 tests.
[dedup-crashes.tar.gz](https://github.com/gbdev/rgbds/files/6239223/dedup-crashes.tar.gz)

**Comment by Rangi42** [comment]
Edited the test case with `,time_10113382,`; it seems that neither `\#` nor recursive `EQUS` nor single-character symbols are essential to this issue. This fails the assertion with `make develop`:

```
def foo equs "bar"
def bar equs "qux"
MACRO test
	\1
ENDM
	test foo 0
```

But doing just `test foo` without anything after the `foo`, or doing `def foo equs "bar "` so `bar` expands within `foo`, does not trigger the assertion.

Hypothesis: an `EQUS` needs to be expanded inside a macro arg, in a situation where if it weren't for #696 the `EQUS` would be expanding inside a parent `EQUS`.

**Comment by Rangi42** [comment]
Some of the syntax errors in the tests are not relevant to the issue. For instance, `,time_4727754,` can be reduced to this:

```
s equs"s"
{-2s:s}
```

(Doing just `{-2:s}` gives an "Invalid format spec" error but doesn't change the assertion failure; however doing `{-1s:s}` or `{2s:s}` avoids it.)

**Comment by NieDzejkob** [comment]
On Wed Mar 31, 2021 at 10:52 PM CEST, Rangi wrote:
> Some of the syntax errors in the tests are not relevant to the issue.
> For instance, `,time_4727754,` can be reduced to this:
>
> ```
> s equs"s"
> {-2s:s}
> ```
>
> (Doing just `{-2:s}` gives an "Invalid format spec" error but doesn't
> change the assertion failure; however doing `{-1s:s}` or `{2s:s}` avoids
> it.)
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gbdev/rgbds/issues/813#issuecomment-811457181

Yes, the minimizer will remove all characters it can get away with, this
includes terminators like these.

**Comment by Rangi42** [comment]
Yeah, I'm not complaining, the test cases are great. Just noting it for debug purposes.

**Comment by Rangi42** [comment]
This looks suspicious:

```
MACRO m
;foo equs "_\\@\\1"
;foo
_\@\1 = 42
println "_\@\1 == {_\@\1}"
ENDM
	m xxxxxx
```

The commented two lines are an assertion-failing case. The bottom two lines do not fail. But in both cases, it seems that `_u1` (the expansion of `_\@`) and `xxxxxx` (the expansion of `\1`) are expanded separately, instead of expanding a single identifier `_u1xxxxxx`.

**Comment by Rangi42** [comment]
If this issue ends up being fundamentally tied to the same thing as #696 (expanding an EQUS/interpolation from the very end of another expansion, such that it doesn't count as being nested) then I'd suggest releasing 0.5.0 without fixing this, and save a proper fix for a second major lexer update.
