### ISSUE TITLE
Inconsistent requirements on section alignment

### ISSUE THREAD

**Issue by NieDzejkob** [gbdev/rgbds#818]
Here, the alignment allowed is `<= 16`:

https://github.com/gbdev/rgbds/blob/61a9bfd33cf9e620a39c337291adc69b9558ff57/src/asm/section.c#L327-L330

However, `mergeSections` asserts `alignment < 16`:

https://github.com/gbdev/rgbds/blob/61a9bfd33cf9e620a39c337291adc69b9558ff57/src/asm/section.c#L107

This means that the following code:

```
SECTION UNION "X", WRAM0
SECTION UNION "X", WRAM0, ALIGN[16]
```

crashes on `make develop` with

```
ERROR: 000007(2):
    Section "X"'s alignment cannot be attained in WRAM0
rgbasm: src/asm/section.c:107: mergeSectUnion: Assertion `alignment < 16' failed.
Aborted (core dumped)
```

Should the alignment be `< 16`, or `<= 16`?

**Comment by NieDzejkob** [comment]
(note: `mergeFragments` also has an equivalent assertion)

**Comment by Rangi42** [comment]
User-declared `ALIGN[16]` is valid but `getSection` is meant to change that to 0: "`Treat an alignment of 16 as being fixed at address 0`". However the "`alignment cannot be attained in WRAM0`" warning runs *instead* of the 16-to-0 fix, not in addition to.

@ISSOtm Should an alignment of 16 be allowed at all? Or even 15? No section type can attain those alignments. And if an alignment cannot be attained, should it be treated "as being fixed at address 0", or just don't align it at all?

**Comment by NieDzejkob** [comment]
Wouldn't VRAM be able to attain alignment 15?

**Comment by ISSOtm** [comment]
`ROM0` can attain any alignment, as it contains `$0000`, which has an "infinite" amount of bits reset. (Air quotes because the addresses are only 16-bit, so it's debatable.)

**Comment by Rangi42** [comment]
Okay, I'll change the "cannot be attained" branch to act like the "alignment == 16" branch and fix it to address 0.

**Comment by Rangi42** [comment]
(The `align-16` and `align-large` tests confirm that alignments ≥ 16 are okay for ROM0.)
