### ISSUE TITLE
[Feature request] Syntax compatibility mode

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#821]
The most recent release candidate, [v0.5.0-rcCar](https://github.com/gbdev/rgbds/releases/tag/v0.5.0-rcCar), provides some new and very welcome syntax to the RGBDS toolchain. This achieves parity with more modern instruction sets, such as x86, whose [MOV instruction](https://www.felixcloutier.com/x86/mov) is powerful enough to [write entire programs using it](https://github.com/xoreaxeaxeax/movfuscator).

The new syntax also comes with improved link-time instruction resolution capabilities, such as by allowing complex expressions in instructions like  `ld ime, <expr>`, which would otherwise have to be written as the ugly `db $fb - 8 * !(<expr>)`. Likewise, nice instructions like `ld nz pc, b <expr>` would otherwise require complex macros to conceal the computations making them writable.

However, since the new syntax introduces a breaking change, this new release is unlikely to be maintained moving forwards, as the pushback from existing projects would force the toolchain to undo such an important change and switch back to the traditional instruction forms. Updating existing projects to use the new syntax exclusively is guaranteed to be a long and painful process, and as such, a hard compatibility break would be too unwelcome to allow these new instruction forms to exist.

In the light of that issue, what I'd request is for the new syntax to be kept as an alternative, thus allowing new code to be written using this improved syntax while continuing to interoperate with legacy code as projects will undoubtedly begin the long transition process. This would add to existing instruction alternatives, such as `ld [c], a` for `ld [h c], a` (currently known as `ldh [c], a`).

I think that the benefits of the new instruction syntax are obvious, and I'm really looking forwards to seeing these instruction variants in the final 0.5.0 release. Thank you very much for your hard work.

**Comment by ISSOtm** [comment]
After some debate, we chose to follow a similar vein as for INTERCAL.

You can test at compile time which syntax is being run under:
- either by assembling a test file and relying on the return status, though that might yield false positives if another error occurs
- or by checking which version you're running under; note that RC car is mistakenly reported as 0.5.0-rc2, but you can always blame the user for using the latter

Then, you can define macros that translate the "traditional" syntax into the modern `ld` one.

Therefore, this is a user problem, and none of our business. Locking, and reporting for racism.
