### ISSUE TITLE
`__UTC_YEAR__` and friends are declared as EQUS, not EQU

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#827]
Test: something like `print "{02d:__UTC_SECOND__}\n"` doesn't work and results in an error and a space-padded value.

**Comment by aaaaaa123456789** [comment]
Apparently they also expand to blank strings (instead of strings with a zero in it) if the value is zero.

**Comment by Rangi42** [comment]
This is a bug; the documentation claims they're all `EQU`.
