### ISSUE TITLE
Support rgbds as a CMake dependency

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#828]
CMake's "[Using Dependencies Guide](https://cmake.org/cmake/help/v3.20/guide/using-dependencies/index.html)" says "The most convenient way for a third-party to provide library binaries for use with CMake is to provide [Config-file Packages](https://cmake.org/cmake/help/v3.20/manual/cmake-packages.7.html#config-file-packages)." Then `find_package` could detect `rgbds`.

It looks like this would involve having `make install` create a `rgbds-config.cmake` file and `install` it to the [appropriate location](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure).

**Comment by Rangi42** [comment]
Do we really need to change anything? After installing RGBDS, does `find_program(RGBASM rgbasm)` and so on work as expected?

**Comment by ISSOtm** [comment]
You have a point that it should. I know @ZoomTen has be toying with CMake; unless they have any specific input, I think it's fair to close this.

**Comment by ZoomTen** [comment]
I suppose `find_program()` works, yeah, but would having a FindRGBDS module (as in #1454) enable checks *during* build script generation? For example, `rgbdscheck.asm` files often rely on `__RGBDS_MAJOR__` etc. being defined, which works only for version 0.3.10+. It might also enable version-specific defines, if such a thing is even necessary.

**Comment by Rangi42** [comment]
Maybe? I'm not sure what we'd need to add the cmakelists for that though. Also, I think you can count on the runtime version constants being defined now; we only introduced those constants (and the `-V` flag) in 0.3.3 anyway, only 0.3.9 omitted them, and 0.3.x didn't support cmake anyway.
