### ISSUE TITLE
src/check_bison_ver.sh in release tarball uses crlf line endings

### ISSUE THREAD

**Issue by mid-kid** [gbdev/rgbds#841]
What it says on the tin. This prevents the script from running.

This is probably due to git auto-converting any text file to the host's line ending format, unless specified in .gitattributes.

**Comment by ISSOtm** [comment]
It's weird that no downstream has been affected, though; all release tarballs were made the same since 0.5.0-rc1, and nobody complained.

To clarify, you're talking about the manually-uploaded one, not the GitHub-generated one, yes?

**Comment by ISSOtm** [comment]
Confirmed this to happen with the manual tarball. I rebuilt it on my system, this should be okay. I'll have to update the RCs', just in case, and fix the CI script also.
