### ISSUE TITLE
Support TPP1 mapper

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#846]
[SameBoy 0.14.3](https://sameboy.github.io/changelog/#newimproved-features) and [BGB 1.5.9](https://bgb.bircd.org/bgb-159-released.html) added support for [the TPP1 mapper](https://github.com/TwitchPlaysPokemon/tpp1/blob/master/specification.md). It may be useful to add support for it in RGBDS, which should amount of changes in RGBFIX.
(RGBASM and RGBLINK already support 31-bit bank IDs, way over TPP1's 16-bit; TPP1 keeps the same ROM layout as the MBCs, making this independent of #524; and any constants for the MR\* regs would be handled in a hardware.inc fork or "add-on")

The changes to be made to RGBFIX:
- Support `-m TPP1_1.0` (or similar syntax, to indicate the spec's version); possibly with `+BATTERY`, `+RUMBLE` etc. flags to specify what to write to $0153
- No changes need to be made to ROM padding or ROM size patching
- $0147, $0149 and $014A must be set to the control values
- The mapper version must be written to $0150 and $0151
- The SRAM size calculation is identical, but must be written to $0152 instead

**Comment by ISSOtm** [comment]
Additionally, @aaaaaa123456789's spec mentions that the test ROM needs to be compiled with TPP's fork of RGBDS. What features are required?

**Comment by aaaaaa123456789** [comment]
> Additionally, @aaaaaa123456789's spec mentions that the test ROM needs to be compiled with TPP's fork of RGBDS. What features are required?

The only special feature that thing supports is setting the control values and the custom fields in the header, and some minor changes to RGBASM and RGBLINK to increase the bank limit.

**Comment by ISSOtm** [comment]
Don't they support 32-bit bank IDs?

**Comment by aaaaaa123456789** [comment]
No, the max valid bank for TPP1 is $FFFF for ROM and $FF for SRAM.

**Comment by ISSOtm** [comment]
I'm talking about RGBASM and RGBLINK, which use `uint32_t` for banks.

**Comment by aaaaaa123456789** [comment]
I don't know how RGBDS does bank types now, but that version used the same value for bank type and bank number (using different ranges to tell the bank types apart), so it had to support $10000 (ROM) + 2 (VRAM) + $100 (SRAM) + 8 (WRAM) + 1 (OAM) + 1 (HRAM) = $1010c banks, requiring more than 16 bits.
