### ISSUE TITLE
[Feature request] Allow REDEF for all kinds of DEF assignments

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#853]
Currently `REDEF` is only allowed for `EQUS`. `EQU` and `RB`/`RW`/`RL` constants are also not redefinable, and have to be `PURGE`d to change their value. Although wanting to redefine those numeric constants is less common than string constants, it may still occur. (For example, rgbds-structs updates some constant values as it goes, but when it's done the user is not supposed to change them, so `EQU` is more appropriate than `SET`.)

`SET`/`=` is already variable, so `DEF` can redefine them without needing a special keyword. However, some people may want to be explicit about which assignments are updates to an existing value, as in `redef x = x + 1` or `if n > 100 / redef n = 100 / endc`.

**Comment by Rangi42** [comment]
One advantage of `REDEF` versus two-line `PURGE` and redefine: it ensures that the type stays the same. `DEF foo EQU 42 / REDEF foo = 100` or `REDEF foo EQUS "6x7"` is an error.

**Comment by ISSOtm** [comment]
Right.
