### ISSUE TITLE
Make error reporting more consistent

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#856]
- [x] Get rid of BSD-style `err` functions (their usage is very lackluster, and we should use our own error-reporting facilities anyway)
- [x] Sync error message format between RGBASM and RGBLINK (example: "FATAL:" or "fatal:"?)
- [ ] Sync error messages between RGBASM and RGBLINK

**Comment by ISSOtm** [comment]
Since that's likely to end up being the last item on the 0.5.2 milestone, and the other two PRs are very close to being merged, we should start discussing what we want to do regarding the latter two bullets.

Do we want to uppercase "FATAL" etc?

**Comment by Rangi42** [comment]
Yeah, I think uppercase FATAL etc would stand out more, especially since rgbasm's own keywords are often uppercase.
