### ISSUE TITLE
Mac OS 11.2.1 “Big Sur”: Installation fails immediately

### ISSUE THREAD

**Issue by halian** [gbdev/rgbds#862]
When I attempt to run `make install`, I immediately get the following error:

```
DEFS=
/Library/Developer/CommandLineTools/usr/bin/bison: invalid option -- W
Try `/Library/Developer/CommandLineTools/usr/bin/bison --help' for more information.
make: *** [src/asm/parser.c] Error 1
```

**Comment by ISSOtm** [comment]
The Bison version you have is the one installed by default, which is a 2.x version from 2012 or earlier. RGBDS needs at least 3.0 (from 20**13**) to compile, which you can get via Homebrew, or compile yourself. (Why Apple is releasing 2021's macOS with a version not updated for upwards of 8 years is beyond me, but that's how it is. :I)

That said, RGBDS is also freely available to obtain on Homebrew (`brew install rgbds`).
