### ISSUE TITLE
Inconsistent documentation of `OPT L`

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#867]
[rgbasm(5)](https://github.com/gbdev/rgbds/blob/ca36422ac94e1a1313ff508987f494c7ffaa7520/src/asm/rgbasm.5#L1956) implies  that `-L` enables `ldh` optimization, when in reality it inhibits it.

This should be corrected, but what about the actual behavior? Should `OPT L` act like `-L` and disable optimizations, or should it do the "positive" action and enable them?
I'm for the former for consistency with the "`OPT` acts like CLI options" principle.

**Comment by Rangi42** [comment]
I agree that `OPT L` should act like passing `-L` (and `OPT !L` acts like omitting `-L`). The documentation example comment should be corrected.
