### ISSUE TITLE
rgblink-combined `FRAGMENT`s calculate wrong `jr` offsets

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#869]
This gives an error "`jr target out of reach (expected -129 < -24576 < 128)`":

```
SECTION "ROM CODE", ROM0
LOAD FRAGMENT "RAM CODE", SRAM
    ds 128
ENDL

SECTION "ROM CODE 2", ROM0
LOAD FRAGMENT "RAM CODE", SRAM
label:
    jr nz, label2
label2: 
ENDL
```

**Comment by Rangi42** [comment]
I can reproduce this with rgbds-live, which is using rgbds 0.5.0-rc1, but not with 0.5.0 or `master`.

**Comment by Rangi42** [comment]
This is not unique to `LOAD FRAGMENT`: these `SECTION FRAGMENT`s have the same issue, when each is built as its own object:

```
SECTION FRAGMENT "ROM CODE", ROM0
    ds 128

SECTION FRAGMENT "ROM CODE", ROM0
label:
    jr nz, label2
label2:
```

**Comment by ISSOtm** [comment]
`LOAD FRAGMENT` needs to be removed anyway, as its semantics are buggy.
All sections in RGBDS are assumed to be contiguous; this is the basis for a *lot* of the implied behavior. `LOAD FRAGMENT` breaks that assumption.

`LOAD` causes a "RAM" section to mirror (size-wise and label-wise) a segment of a "data" section. This makes sense. `LOAD UNION` merely allows the RAM block of data to share space with others, like the well-known "overlay" feature present in a lot of systems.

`LOAD FRAGMENT`, however, enables breaking the RAM section's *actual* contents across several, non-contiguous ROM sections. This breaks the implicit assumption that there is a 1:1 mapping between the ROM and "RAM" sections.

**Comment by Rangi42** [comment]
Where does rgbds need to assume that a fragmented RAM section's intended contents are also contiguous in ROM?

**Comment by ISSOtm** [comment]
When it comes to label position calculation.

**Comment by Rangi42** [comment]
What I mean is, since labels in a `LOAD FRAGMENT` are defined within RAM not ROM, they don't need to be contiguous in ROM.

```
SECTION "ROM 1", ROM0
LOAD FRAGMENT "RAM", SRAM
label1:
    scf
    ret
ENDL

SECTION "ROM 2", ROM0
LOAD FRAGMENT "RAM", SRAM
label2:
    jr z, label1
    xor a
    ret
```

Maybe this is split up in ROM because it's meant to be contiguous in RAM but needs to be copied one fragment at a time. (A poor example here, but some large data in Pokémon GSC gets copied in SRAM that way.)
