### ISSUE TITLE
`rgbfix` warns about overwriting non-zero padding bytes

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#889]
```
; foo.asm

SECTION "Header", ROM0[$100]
	di
	jp Start
	; ds $4c, 0 ; uncomment this to work around the warnings

SECTION "Start", ROM0[$150]
Start::
	halt
	jr Start
```

```
$ rgbasm -p 0xff -o foo.o foo.asm
$ rgblink -p 0xff -o foo.gb foo.o
$ rgbfix -p 0xff -v foo.gb
warning: Overwrote a non-zero byte in the Nintendo logo
warning: Overwrote a non-zero byte in the header checksum
```

**Comment by aaaaaa123456789** [comment]
Working as designed, I'd say. RGBFIX doesn't know if a byte is padding or not. Encouraging users to explicitly allocate space for the header is a good thing.

**Comment by Rangi42** [comment]
Even when it matches the `-p` value given to `rgbfix`?

**Comment by ISSOtm** [comment]
Yes, RGBFIX is written with the assumption that all header bytes it doesn't overwrite are $00. This is why there are `-c` and `-C`, but no equivalent DMG switch: that's $00.
