### ISSUE TITLE
`STARTOF("Known Section")` is not a constant value

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#890]
```
; define a later section before an earlier one so its location is known
SECTION "Start", ROM0[$150]
Start::
	halt
	jr Start

SECTION "Header", ROM0[$100]
Header::
	di
	jp Start

	; some alternatives below
	ds $150 - @, 0             ; OK
	ds Start - @, 0            ; OK
	ds STARTOF("Start") - @, 0 ; Section "Start"'s start is not known
```

**Comment by Rangi42** [comment]
(This should also be resolved for `SIZEOF`.)

**Comment by ISSOtm** [comment]
`SIZEOF` is only known if:
- Not the current section (nor LOAD section)
- Not on the stack
- Plain type

Is it worth the trouble?

**Comment by Rangi42** [comment]
I think it might be. `SIZEOF("Section X")` substitutes for `XEnd - X`, and I expect that to sometimes be useful in constant expressions. Like maybe `wSomeBuffer:: db SIZEOF("Data Section")`.
