### ISSUE TITLE
Unintentional change to macros that causes a different result

### ISSUE THREAD

**Issue by VariantXYZ** [gbdev/rgbds#894]
Using rgbasm v0.5.1-17-g0c8cdd9, I've found a change in behavior that seems like a bug, but if I'm wrong please let me know (I didn't notice anything immediately obvious in the changelogs).

To save space in a certain translation project, we have a macro that maps a tile address and address to draw text to with a single 16-bit load instruction:

```
psbc: MACRO
  ld bc, (((\2&$FF)*$100)+((((\1-$20)>>1)&$F0)+((\1-1)&$F)))
  ENDM
```

This looks strange, but within our constraints, this was working great with our custom routines when building on rgbasm v0.3.3-779-gcb4fbdf (our automation uses this version, so our release builds are OK).

```psbc, $9841, $c6```
would normally turn into:
```ld bc, $c610```

However, on v0.5.0 this is turning into:
```ld bc, $41ff```

It looks like it's parsing the arguments incorrectly, but I'm not quite sure. Any ideas?

**Comment by VariantXYZ** [comment]
(Seems to work fine on v0.4.2 as well)

**Comment by aaaaaa123456789** [comment]
It might be a good idea to try with some parentheses to isolate the macro arguments, particularly since the lack of spaces might cause the lexer to get confused:

```
psbc: MACRO
  ld bc, (LOW(\2) << 8) | ((((\1) - $20) >> 1) & $f0) | (((\1) - 1) & $f)
ENDM
```

If this works, you've most likely successfully found a lexer bug.

**Comment by Rangi42** [comment]
v0.5.0 allows empty macro arguments. `psbc, $9841, $c6` has `\1` as empty, `\2` as `$9841`, and `\3` as `$c6`. Write `psbc $9841, $c6`. Also pass `-Wempty-macro-arg` to `rgbasm` to get a warning about that (or ideally `-Weverything` to enable all warnings).

**Comment by VariantXYZ** [comment]
I see, thanks! That was indeed the issue.

**Comment by aaaaaa123456789** [comment]
![xkcd #1172](https://www.explainxkcd.com/wiki/images/b/b5/workflow.png)
