### ISSUE TITLE
[Bug] Multiple dots in identifiers behave inconsistently

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#913]
This is currently a legal program:

```
SECTION "test", ROM0[0]
Main:
	db 0
.local1:
	db 1
Main.local2:
	db 2
Main....local3:
	db 3
....local4
	db 4
Main.:
	db 5
```

```
$ rgbasm -Weverything -o foo.o foo.asm
$ rgblink -o foo.gb -n foo.sym foo.o
$ cat foo.sym
; File generated by rgblink
00:0000 Main
00:0001 Main.local1
00:0002 Main.local2
00:0003 Main....local3
00:0004 Main....local4
00:0005 Main.
```

However, the odd label cannot be referenced. `dw Main....local3` fails to assemble with "`FATAL: 'Main....local3' is a nonsensical reference to a nested local symbol`". `dw .local3` assembles but fails to link with "`error: Unknown symbol "Main.local3"`".

Furthermore, this assembles:

```
Main:
	db 0
.local1:
	db 1
Main.local2:
	db 2
Main.abc.local3:
	db 3
```
```
00:0003 Main.abc.local3
```

But "`Main.abcd.local3`" fails with "`'Main.abcd.local3' is a nonsensical reference to a nested local label`".

Short-term, I think any identifier with more than one `.` in it, or with a trailing `.`, or with a starting `.` and no parent scoped label, should be rejected. So `Main....local3`, `....local4`, and `Main.abc.local3` would all fail as "nonsensical reference"s right away.

Long-term, it might be useful to allow nested scopes, but I doubt it. For one thing, there's no simple way to go up a scope except by starting a new non-local label in the main scope.

**Comment by ISSOtm** [comment]
They *are* supposed to be rejected, this is a legit bug.

**Comment by aaaaaa123456789** [comment]
> Long-term, it might be useful to allow nested scopes, but I doubt it. For one thing, there's no simple way to go up a scope except by starting a new non-local label in the main scope.

If nested scopes are ever implemented, `..foo` to define a label in the second-level nested scope would be some simple syntax that could be used. Like so:

```
Main:
  dw 1234
: ..label isn't allowed here (nonsensical nested label; no parent)
.foo
  dw 5678
..bar ; defines Main.foo.bar
  dw 9012
.baz ; defines Main.baz (up a level because it only has one dot)
  dw 34567
```

Naturally, `...label` would be a third level, etc.

**Comment by Rangi42** [comment]
Interesting. Possibly it could autofill each upper level separately: so appending `Main..bar` there would become `Main.baz.bar`, appending `.baz.qux` would become `Main.baz.qux` (and then appending `.baz..spam` would become `Main.baz.qux.spam`).
