### ISSUE TITLE
[Feature request] Shorthand operators for mutating `=` constants

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#943]
It's common to do `def p = p + 1`, `def q = q - 1`, `def r = r << 1`, etc. Shorthand operators would further justify having separate `EQU` and `=` constants.

Arithmetic:

- [ ] `+=`
- [ ] `-=`
- [ ] `*=`
- [ ] `/=`
- [ ] `%=`

Bitwise:

- [ ] `&=`
- [ ] `|=`
- [ ] `^=`
- [ ] `<<=`
- [ ] `>>=`

(We don't really need `**=`, `&&=`, or `||=`.)

Examples: `def p += 1`, `def q -= 1`, `def r <<= 1`, etc.

**Comment by aaaaaa123456789** [comment]
While there's no apparent need for the few operators you mention at the end, if they are trivial to implement, you might as well. For someone who is starting to use a toolchain, "every operator has an `<op>=` form" is an easier rule to remember than knowing which operators are valid and which ones aren't; likewise, even for non-beginners, it's a simpler rule to remember and document.
