### ISSUE TITLE
[Proposal] Standardize terminology for EQU/=/EQUS constants

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#945]
Now that `SET` is deprecated, it doesn't make to call them "`SET` constants", "`sym_AddSet`", "`SYM_SET`", etc. Also "mutable constants" sounds like an oxymoron. How about:

- Symbols defined with `=` are "*variables*" (thus "`sym_AddVar`", "`SYM_VAR`", etc)
- Symbols defined with `EQU` are "*numeric constants*" (not "EQU constants", although "Equ" in the source code is fine)
- Symbols defined with `EQUS` are "*string constants*" (not "EQUS constants", although "Equs" in the source code is fine)
- Symbols defined with `RB`/`RW`/`RL` are "*offset constants*" (internally identical to numeric constants)
- Character values defined with `charmap` are "*character constants*"
- The terms for "*labels*" and "*macros*" are already fine

@ISSOtm What do you think?

**Comment by ISSOtm** [comment]
Yep, this makes more sense.
