### ISSUE TITLE
Tests fail on github release archive

### ISSUE THREAD

**Issue by mid-kid** [gbdev/rgbds#955]
Steps to reproduce:
```
wget https://github.com/gbdev/rgbds/releases/download/v0.5.2/rgbds-0.5.2.tar.gz
tar xf rgbds-0.5.2.tar.gz
cd rgbds
make
cd test/fix
./test.sh
```

Errors appear, like:
```
/home/mid-kid/rgbds/test/fix/version.gb out.gb differ: char 333, line 3
./test.sh: ./gbdiff.bash: /bin/bash^M: bad interpreter: No such file or directory
```

How to fix in repo:
```
for x in contrib/gbdiff.bash test/fix/*.flags; do
  cat "$x" | tr -d '\r' > tmp; cat tmp > "$x"; rm tmp
done
```

Though it probably should be fixed in gitattributes.

**Comment by ISSOtm** [comment]
I guess the fix would be to disable auto-CRLF in [our CI script](https://github.com/gbdev/rgbds/blob/20a26599a3de9fa7c24f8daef7310721b2c2958a/.github/workflows/create-release-artifacts.yaml#L11), as well as re-generating all affected tarballs.

**Comment by mid-kid** [comment]
Regenerating tarballs after this long is kinda evil since most packaging scripts rely on it staying the same for verification. And failing tests is super minor.
But if you want a list, it's just 0.5.1 and 0.5.2.

**Comment by mid-kid** [comment]
Also why not fix the gitattributes?

**Comment by ISSOtm** [comment]
Because it appears to work fine on Windows installs despite using CRLF, if I am to believe our CI.

**Comment by ISSOtm** [comment]
As for regenerating the tarballs, you're right.
