### ISSUE TITLE
[Feature request] IEEE 754 floating point math

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#956]
As recently discussed in `#tools`, floating-point math would sometimes be convenient for its greater range even though Q16.16 fixed point is already built-in. The fixed-point range is around +/- 65,536, whereas 32-bit floating-point is around +/- 3.4 × 10^38.

I think this could be added to rgbasm without conflicting with existing features.

**Formatting:**

`%f` is taken for fixed point, but `%p` is available (***f***-ixed point, floating ***p***-oint). All the same modifiers would still apply (e.g. `%+08.3p`).

**Literals:**

C/C++ allow `p` as well as `e` for scientific notation, which would also (a) match the `%p` letter, and (b) not be confused with a hex digit. We could allow:

- Just scientific notation: `3.14p0`, `1.2345p+2 == 123.45p0 == 1234.5p-1`, etc.
- Just a suffix: `3.14p`, `123.45p`, `0.00001p`
- Scientific notation, but an empty/missing power acts like 0: `3.14p == 3.14p0` (so `3.14p0` would tokenize differently from `3.14p 0`)

**Functions:**

- `ROUNDF`, `SINF`, etc complement the fixed-point `ROUND`, `SIN`, etc.
- `ADDF`, `MULF`, etc complement the fixed-point `ADD`, `MUL`, etc.
- We could add some kind of prefixed/suffixed operators, like `'+` for floating-point addition, but IMO that looks obscure and would waste available punctuation on a niche use case.

**Edge cases:**

No need to support infinity/NaN as literals; in the unlikely event somebody wants them, `$7F800000` is +infinity, `$FF800000` is -infinity, plus various other patterns for NaNs.

Floating-point operations that result in infinity or NaN could print a warning (toggle-able with some `-W` flag).

**Comment by ISSOtm** [comment]
Floating-point is not desirable because of being way far removed from what is desirable on the GB. It would be much more useful, however, to support arbitrary-precision fixed-point, i.e. not hardcoding the Qx.y format. This could be achieved using lazy expressions and a form such as `FLOOR[.8](16.0 * 1.75)` (floor the result of multiplying Q23.8 16.0 by 1.75, i.e. $0F00 and $01C0).

**Comment by ISSOtm** [comment]
What use cases for more than 32 bits have arisen so far?

**Comment by Rangi42** [comment]
> What use cases for more than 32 bits have arisen so far?

I don't know if what rondnelson was saying in `#tools` would be covered by better fixed-point like #957 or not. I agree better fixed-point would be a higher priority, especially if it's simpler than adding a new literal format and a whole new set of built-in functions.

**Comment by Rangi42** [comment]
Note that 32-bit floats would not perfectly cover all use cases. [This table](https://github.com/aaaaaa123456789/gb-norm-vector/blob/master/normvector.asm#L45) of Q16.16 unit vectors can be exactly generated with 64-bit doubles, but not 32-bit floats (nor rgbasm's fixed-point math). Anything except double precision gives slight differences in the values.

**Comment by aaaaaa123456789** [comment]
That's Q0.16 if you want to be fully accurate, but yes, that's correct. I didn't test the precision loss, but I'm not surprised by it at all.

**Comment by Rangi42** [comment]
Yeah. Given that people will almost certainly not run floating-point math on the Game Boy itself, and that if fixed-point math gives imprecise results then 32-bit floating-point probably would too, and that we wouldn't expand rgbasm numeric values to 64-bit just for this feature, I think it can be rejected.
