### ISSUE TITLE
[Feature request] Unsigned right shift operator `>>>`

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#960]
Like Java, `>>>` would shift a number right as unsigned. This would not do sign extension and would not trigger the "Shifting right negative value" warning.

**Comment by Rangi42** [comment]
A use case:

```
MACRO print_bin
	println STRFMT("%08x = %08b_%08b_%08b_%08b", \
		(\1), LOW((\1) >> 24), LOW((\1) >> 16), LOW((\1) >> 8), LOW(\1))
ENDM
```

This warns about printing numbers `$8000_0000` and above because of the `>>` shifting them as signed `int32_t`.

**Comment by aaaaaa123456789** [comment]
+1 from me; haven't we discussed this before?

**Comment by ISSOtm** [comment]
Yup, and so +1 as well.
