### ISSUE TITLE
JR $2 - Target out of reach (expected -129 < -297 < 128). 

### ISSUE THREAD

**Issue by fizaan** [gbdev/rgbds#961]
![image](https://user-images.githubusercontent.com/27024481/146809132-8b56203d-0612-423d-a70f-a55375e00172.png)

Why is 0x2 out of range?

![image](https://user-images.githubusercontent.com/27024481/146809209-d6572c53-4db1-4bbd-95a9-38d5f2997043.png)

**Comment by GreenAndEievui** [comment]
`jr` is not meant to be given relative offsets, even though that's how it shows up in ROM. Instead, RGBDS expects a full address, and will calculate the offset for you. So in this example, RGBDS thinks you're trying to jump all the way to `$0002`, which is too far away from the `jr`. You *could* do `jr @ + $2` instead to get the intended behavior, but it would be best to use a label instead.

**Comment by fizaan** [comment]
Thanks! That was helpful.

**Comment by Rangi42** [comment]
`@` is relative to before the two-byte `jr` instruction; the offset in ROM is relative to *after* it. So you'd want `jr (@ + 2) + 2` to skip the two bytes after the `jr` instruction:

```
    jr (@ + 2) + 2
    ld b, 17 ; this gets skipped
    ret
```

Although again, a label or anonymous label is better:

```
    jr .skip
    ld b, 17
.skip
    ret
```
```
    jr :+
    ld b, 17
:   ret
```
