### ISSUE TITLE
[Feature request] Allow `&` to potentially be constant at assembly time

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#965]
Currently `-` is special-cased to be constant for `sym1 - sym2` when `sym1` and `sym2` are both in the same section, since even if their particular values aren't known, their difference is.

We could do the same with `&`. If `sym` is in a section aligned to N bits, then its low N bits can be known. So `sym & K` could be constant if `0 <= K < (1 << N)`.

**Comment by aaaaaa123456789** [comment]
The true condition is `k & ($10000 - (1 << N))` being zero.
Might seem irrelevant, but an expression expanding to something like `~$fffc` would meet this one and not that one.
