### ISSUE TITLE
[Feature request] Allow `ld hl, sp` to mean `ld hl, sp + 0`

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#966]
This would be syntax sugar similar to `stop` for `stop 0` or `ld a, [c]` for `ld a, [$ff00 + c]`, and would avoid the redundant-looking "add zero" operation.

**Comment by ISSOtm** [comment]
Duplicate of #276, see the discussion there.

**Comment by Rangi42** [comment]
Alright, I see your and AntonioND's reasons against `ld hl, sp`. It makes sense, and unlike `stop`, isn't [weird enough](https://gbdev.io/pandocs/Reducing_Power_Consumption.html#using-the-stop-instruction) to just hide the second byte.

**Comment by aaaaaa123456789** [comment]
If that's the reason to not hide it, I still don't get the argument against doing it the way every single assembly language in the world does it, which is `add hl, sp, 0`...

**Comment by ISSOtm** [comment]
Because it doesn't mesh well with the rest of RGBDS' syntax (e.g. `[$ff00 + c]`).

**Comment by aaaaaa123456789** [comment]
That's legacy for a good reason; hasn't `ldh a, [c]` been the recommended syntax for years?
