### ISSUE TITLE
[Feature request] `SWITCH`

### ISSUE THREAD

**Issue by aaaaaa123456789** [gbdev/rgbds#968]
The syntax should be self-explanatory. Useful for cases where a macro argument changes behavior: this would make it simpler to use constants instead of string comparisons.

```
SWITCH (foo + bar)
CASE 0
Message: db "Hello, world!", 0
RandomFunction:
  add a, 3
  ret
CASE 1
Message: db "Hi!", 0
RandomFunction:
  sub 2
  ret
CASE 2, 3
Message: db "Welcome.", 0
RandomFunction:
  add a, a
  ret
CASE ELSE ; borrowed from Visual Basic to avoid introducing a "default" keyword
  fail "Invalid value"
ENDC
```

**Comment by Rangi42** [comment]
This would only work for integers, right? So I'm not sure what you mean about this making it simpler to not use string comparisons.

The current way would be a temporary variable (or just repeat the expression):

```
DEF temp = foo + bar
IF temp == 0
  ...
ELIF temp == 1
  ..
ELIF temp == 2 || temp == 3
  ..
ELSE
  fail "Invalid value"
ENDC
```

I don't know if it's worth reserving two new keywords for the sake of slightly more terse conditionals on one value. It would be different if switch-cases were significantly more powerful than if-elses, like if they had pattern matching (not that I'm suggesting rgbasm get pattern matching, its data types aren't complex enough to really benefit).

Can you link to some code that would be improved by `switch`? The closest I can find is this in pokecrystal, which would just end up being one line longer from `switch`+`case`:

```
givepoke: MACRO
if _NARG == 2
	givepoke \1, \2, NO_ITEM, FALSE
elif _NARG == 3
	givepoke \1, \2, \3, FALSE
else
	db givepoke_command
	db \1 ; pokemon
	db \2 ; level
	db \3 ; item
	db \4 ; trainer
if \4
	dw \5 ; trainer_name_pointer
	dw \6 ; pkmn_nickname
endc
endc
ENDM
```

**Comment by aaaaaa123456789** [comment]
> This would only work for integers, right? So I'm not sure what you mean about this making it simpler to not use string comparisons.

Any macro with a keyword argument can use a constant instead of a keyword argument. Right now there's not much benefit in doing it either way.

And that macro is written in a particularly silly way. This would be better (dropping the unnecessary fourth argument):

```
givepoke: MACRO
  db givepoke_command
  db \1 ; pokemon
  db \2 ; level
  SWITCH _NARG
  CASE 2
    db NO_ITEM ; item
    db FALSE ; trainer
  CASE 3
    db \3 ; item
    db FALSE ; trainer
  CASE ELSE
    db \3 ; item
    db TRUE ; trainer
    db \4 ; trainer name pointer
    db \5 ; pokemon nickname
  ENDC
ENDM
```

I'm not sure if it's _shorter_, but it looks more readable to me, without the recursive invocation.

**Comment by Rangi42** [comment]
(Good point about the boolean `db` being implied by the `_NARG`; I'll start a pokecrystal issue for it.)

I think the other refactorings are what improve that macro, not `switch`. Compare (re-indented for pokecrystal's admittedly outdated style):

```
givepoke: MACRO
	db givepoke_command
	db \1 ; pokemon
	db \2 ; level
if _NARG == 2
	db NO_ITEM ; item
	db FALSE ; trainer
elif _NARG == 3
	db \3 ; item
	db FALSE ; trainer
else
	db \3 ; item
	db TRUE ; trainer
	db \4 ; trainer name pointer
	db \5 ; pokemon nickname
endc
ENDM
```
