### ISSUE TITLE
The meaning of the recursion limit seems off by one

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#978]
Currently for `-r N` the value `N` is the recursion depth at which it fails. I think specifying the maximum valid recursion depth would be more intuitive. So currently `-r 0` is pointless and `-r 1` fails for any macro expansion; with this change `-r 0` would disallow any macro expansion and `-r 1` would disallow nested macro expansion.

**Comment by ISSOtm** [comment]
Careful that the limit is managed separately for "contexts" (macros, includes, etc.) and `equs`.

**Comment by Rangi42** [comment]
It's not currently managed separately for them all, though; that would be a separate issue from basically just allowing one further recursion than it does now.
