### ISSUE TITLE
[Feature request] An OPT for whether PRINT(LN) goes to stdout, stderr, or /dev/null

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#984]
In https://github.com/pret/pokecrystal/pull/882 we brought up this scenario: An .asm file whose `PRINTLN` output is meant to be in a meaningful format parse-able by custom tools; but which `INCLUDE`s a file declaring constants and macros, in which the user may have added `PRINT`s for whatever reason (maybe to check the value of a particular constant).

It would be neat if we could "silence" any printing from the `INCLUDE`d file. One way to do this would be a boolean toggle option for whether printing happens or not. Or, we could extend it to allow printing to go to stdout, stderr, or not happen at all. This would allow human-readable "debug" prints to go to stderr, and the rest to stdout, which gets redirected to some parsing tool. (This is a common setup in other command-line tools.)

**Comment by ISSOtm** [comment]
Why not simply skip including the file?

**Comment by Rangi42** [comment]
Because the file defines macros/constants that we need.

https://github.com/vulcandth/pokecrystal/blob/Vulcan-Virtual-Console/vc/vc_constants.asm

Conceivably we might have multiple tools that want to use this file and generate their own output, as well as the typical non-tool use of people including it in hand-written asm. So even though vc_constants.asm is written so its output will be tool-legible, it depends on a file which may not.

**Comment by ISSOtm** [comment]
```asm
IF DEF(PRINT_VC_SYMS)
	MACRO vc_const
		println "{d:\1} \1"
	ENDM
ELSE
	MACRO vc_const
	ENDM
ENDC
```

**Comment by Rangi42** [comment]
No, that's a solution for the opposite problem: preventing the file that we control from print, if it's INCLUDEd by some other user-written file.

We run `rgbasm vc_constants.asm > output.txt`, and then pass `output.txt` to a tool to be parsed; so anything send to stdout should be in the format the tool expects. But, vc_constants.asm depends on constants.asm, which just has a bunch of INCLUDEs for the constants and macros used by the entire project.

It's normal for constants.asm to be used in many contexts: if we had some `rgbasm other_file.asm | ./other_tool`, it might also use constants.asm even though it makes different output. And importantly, we can't expect everything included via constants.asm to play nicely with every tool that might use it. (Maybe I put a debug `println "Mew is {MEW}"` to see what value `MEW` is, and don't want to be surprised by `make` failing due to that.)

Another use case for this proposed OPT would be letting macros control whether they print to stdout or stderr. Right now `PRINT/PRINTLN` go to stdout and `ASSERT/WARN/FAIL` to stderr, but those come with extra printed details like `warn "foo"` printing `warning: main.asm(14): [-Wuser] foo`.

```
MACRO alert
  pusho
  opt <print goes to stderr>
  println \#
  popo
ENDM

  alert "foo" ; just prints "foo" to stderr
```

That could be useful if the user does `make >make.log 2>problems.log`.

**Comment by ISSOtm** [comment]
Then `constants` should detect such a variable; I do *not* want `opt` to start mucking with file descriptors, so I really don't want this.
