### ISSUE TITLE
Make the automatic `ld`-to-`ldh` optimization off by default, with a gradual switchover

### ISSUE THREAD

**Issue by Rangi42** [gbdev/rgbds#986]
Currently rgbasm optimizes `ld` to `ldh` when it can, with the `-L` flag disabling that behavior.

In the next release of rgbds (0.6.1), add a do-nothing `-l` flag. Add a deprecation warning on the first time that the `ld`-to-`ldh` optimization occurs, saying that it will be off by default in the next release, and you should then use `-l` to enable it.

In the release after that (0.7.0), change it from on by default to off by default, with `-l` turning it on. (`OPT` should support `l` same as it now supports `L`.) Add a deprecation warning on use of the `-L` flag, saying that it is now useless and will be removed or repurposed in the next release. Passing both `-L` and `-l` should be a fatal error.

In the release after *that* (0.8.0), remove the `-l` and `-L` flags.

We should have a similar transition for the `-h` flag, which stops rgbasm from automatically inserting `nop` after `halt`.

**Comment by QuinnPainter** [comment]
Do you mean the `-L` flag? `-h` is used for inserting nops after halts.

**Comment by Rangi42** [comment]
Docs in the 0.7.0 release:

> `-H`, `--nop-after-halt`  
> Inserts a `nop` instruction immediately after any `halt` instruction. This option is deprecated and will be removed in the next minor release.
> 
> `-h`, `--halt-without-nop`  
> This option is deprecated and will be removed in the next minor release.
> 
> `-L`, `--preserve-ld`  
> This option is deprecated and will be removed in the next minor release.
> 
> `-l`, `--auto-ldh`  
> Optimize loads of the form `LD [$FF00+n8],A` into the opcode `LDH [$FF00+n8],A`. This option is deprecated and will be removed in the next minor release.
