### ISSUE TITLE
Overlay feature doesn't work when there are 0xFF banks

### ISSUE THREAD

**Issue by VariantXYZ** [gbdev/rgbds#993]
Tested using Dragon Warrior 3 (US) which utilizes bank 0xFF with an empty source file:
(original is baserom_en.gbc)
```
touch main.asm
mkdir -p build/
rgbasm -o build/main.o main.asm
rgblink -O baserom_en.gbc -o dq3_en.gbc build/main.o
```

main is an empty file, but it doesn't matter what it has in it. This will generate a 4080 KB file (missing the last bank).

**Comment by VariantXYZ** [comment]
Actually, it seems like this issue is a bit weirder than I thought. 

Changes are being put in one bank earlier than they should (with or without my fix).

**Comment by VariantXYZ** [comment]
> Changes are being put in one bank earlier than they should

To clarify, putting a change in 2:403d instead puts them in 1:403d...

**Comment by aaaaaa123456789** [comment]
I have a hunch that ROM0 is somehow getting skipped..

**Comment by VariantXYZ** [comment]
> Though the other issues I'm seeing indicate some real weird stuff.

I tried with a different file (Medarot 3: Kabuto, and with the empty 'main' file it worked fine, but if I just went and modified bank FF, it copied over correctly in my original tree).

Maybe it would be good if anyone else could reproduce this with the steps I posted above?

**Comment by ISSOtm** [comment]
I can reproduce the issue, investigating.

**Comment by ISSOtm** [comment]
ROM0 is being skipped because its bank count is 0. Interesting.

**Comment by ISSOtm** [comment]
A workaround in the meantime: creating a ROM0 section, even if empty, should not trigger the bug.
