### ISSUE TITLE
Check tests' code coverage

### ISSUE THREAD

**Issue by ISSOtm** [gbdev/rgbds#996]
We should be able to use [`gcov`](https://gcc.gnu.org/onlinedocs/gcc/#toc-gcov---a-Test-Coverage-Program) and/or [LLVM's source coverage](https://clang.llvm.org/docs/SourceBasedCodeCoverage.html) for this.

**Comment by coltongit** [comment]
Could also use the GitHub extension `codecov` for this, whatever is preferred
