### ISSUE TITLE
Can't load values in RAM

### ISSUE THREAD

**Issue by nerix13** [gbdev/rgbds#998]
Hi, sorry for my english. Im a beginner in gameboy dev so i dont know if its my fault or its error of the page, 
I looked at the memory addresses and there's nothing stored there, im using the rgbds-live web page to write and run code. This is my code.

![Captura de pantalla (273)](https://user-images.githubusercontent.com/56384643/168941411-07507bb6-3d96-49d7-aacf-1a8fb5a97088.png)

**Comment by GreenAndEievui** [comment]
Hi! There are a few issues with this code, but this isn’t the place for help. If you’d like assistance, you should join the gbdev discord server here: https://gbdev.io/chat.html
